export const firstNames = [
    "Adam",
    "Albin",
    "Alfred",
    "Alma",
    "Alvar",
    "Alve",
    "Amir",
    "Anna",
    "Anton",
    "Aron",
    "Astrid",
    "August",
    "Axel",
    "Benjamin",
    "Bill",
    "Björn",
    "Charlie",
    "Christina",
    "Casper",
    "Dante",
    "Ebba",
    "Ebbi",
    "Eduard",
    "Elias",
    "Elina",
    "Ellie",
    "Emma",
    "Emil",
    "Erik",
    "Eva",
    "Filip",
    "Folke",
    "Frans",
    "Gabriel",
    "Gustav",
    "Hanna",
    "Harry",
    "Henry",
    "Hjalmar",
    "Hugo",
    "Ivar",
    "Jack",
    "Jan",
    "Johan",
    "Joel",
    "Julian",
    "Karin",
    "Karl",
    "Kerstin",
    "Kian",
    "Knut",
    "Lars",
    "Levi",
    "Liam",
    "Lena",
    "Leo",
    "Leon",
    "Lili",
    "Lina",
    "Linnéa",
    "Lisa",
    "Liva",
    "Loke",
    "Love",
    "Lucas",
    "Ludvig",
    "Lukas",
    "Luna",
    "Madeleine",
    "Malte",
    "Maria",
    "Marie",
    "Matheo",
    "Max",
    "Melker",
    "Melvin",
    "Mikael",
    "Milan",
    "Milo",
    "Milton",
    "Nils",
    "Noel",
    "Omar",
    "Oliver",
    "Olle",
    "Otis",
    "Otto",
    "Oskar",
    "Per",
    "Peter",
    "Philip",
    "Sam",
    "Sara",
    "Sigge",
    "Sixten",
    "Sophia",
    "Theo",
    "Thomas",
    "Valter",
    "Vera",
    "Viggo",
    "Vincent",
    "William",
    "Wilhelm",
    "Walter",
    "Xavier",
    "Ylva",
    "Åke"
];

export const lastNames = [
    "Abrahamsson",
    "Ahmed",
    "Ali",
    "Andreasson",
    "Arvidsson",
    "Axelsson",
    "Bengtsson",
    "Berger",
    "Berggren",
    "Bergkvist",
    "Bergman",
    "Bergström",
    "Blom",
    "Blomberg",
    "Blomkvist",
    "Blomquist",
    "Blomqvist",
    "Björk",
    "Björklund",
    "Björnsson",
    "Claesson",
    "Danielsson",
    "Dahlberg",
    "Ek",
    "Ekberg",
    "Ekblad",
    "Ekholm",
    "Ekström",
    "Eliasson",
    "Engström",
    "Eriksson",
    "Eklund",
    "Fallberg",
    "Fredriksson",
    "Fransson",
    "Frantzén",
    "Frisk",
    "Gunnarsson",
    "Gustafsson",
    "Gyllenhaal",
    "Hallberg",
    "Hansson",
    "Hedberg",
    "Hellström",
    "Henriksson",
    "Hermansson",
    "Holberg",
    "Holmgren",
    "Holmqvist",
    "Hultén",
    "Hägg",
    "Hällström",
    "Jakobsson",
    "Jansson",
    "Johansson",
    "Jonsson",
    "Jönsson",
    "Karlsson",
    "Klintberg",
    "Klingberg",
    "Klintström",
    "Knutsson",
    "Krüger",
    "Kullberg",
    "Kullén",
    "Kurck",
    "Larsson",
    "Lindberg",
    "Lindblad",
    "Lindell",
    "Lindgren",
    "Lindholm",
    "Lindkvist",
    "Lindner",
    "Lindroos",
    "Lindström",
    "Lindqvist",
    "Lindsten",
    "Lindwall",
    "Ljungberg",
    "Ljunggren",
    "Löfgren",
    "Lundberg",
    "Lundgren",
    "Lundkvist",
    "Lundmark",
    "Lundström",
    "Magnusson",
    "Mattsson",
    "Malmberg",
    "Malmgren",
    "Malmqvist",
    "Malmström",
    "Månsson",
    "Martinsson",
    "Melin",
    "Mellberg",
    "Mellgren",
    "Mellqvist",
    "Mellström",
    "Mohamed",
    "Molin",
    "Moller",
    "Mörner",
    "Mörtberg",
    "Mörtén",
    "Mörtstedt",
    "Norberg",
    "Nordin",
    "Nyberg",
    "Nyström",
    "Olsson",
    "Olofsson",
    "Persson",
    "Pettersson",
    "Pålsson",
    "Sandberg",
    "Sandström",
    "Sjögren",
    "Sjöberg",
    "Ström",
    "Strömberg",
    "Sundberg",
    "Sundström",
    "Söderberg",
    "Tage",
    "Viklund",
    "Wallin",
    "Åberg",
    "Åkesson",
    "Åström"
];

export const addresses = {
    "145 04": ["Big Laughsvägen", "Baj Linjen", "Dj. Toastmastergatan"],
    "145 08": ["Beror På Vad Man Röstar På I Valetgatan", "Marrevägen", "Maxgatan"],
    "145 09": ["King Finders Väg", "1p-gränd", "Och Nej Jag Har Inte Pruttat På De-stigen"],
    "145 10": ["Guy Huntervägen", "Visst Är Det Så Gatan", "Kommer Vid 22:00 allé"],
    "145 11": ["Naaah... Gatan", "Gordon Ramsey Kommer Vägen", "Alltid En Sunk Kommentarväg"],
    "145 12": ["Bah Uuuuhh Väg", "PT - Posten Tishagatan", "NBK - Nerbajasade Kallingarstig"],
    "145 33": ["Mr. Lemonvägen", "Kalla Föttergatan", "Siftpjvägen"],
    "145 34": ["LP Under Armarna Allé", "Blue Visionvägen", "Ah Steve Averygatan"],
    "145 35": ["Blue Balls Managementsgatan", "Jag Blir Outraged Gatan", "Med Gumman Torg"],
    "145 36": ["Fronten Väg", "Ah HB-gatan", "Ah Juste Väg"],
    "145 37": ["Skoja Bah Jellyvägen", "Bira I Pepsin Gatan", "Rough Start Väg"],
    "145 38": ["Dagge Idag Eller? Stigen", "Bubbavägen", "Ham-Rider Gatan"],
    "145 39": ["E Den Startklar Eller? Väg", "Big Nightgatan", "Lufta Doggevägen"],
    "145 40": ["Å Så 30 Egna Gatan", "Vilket Filter Gatan", "Rain Man Gatan"],
    "145 41": ["PDF På Det Här Väg", "King Väg", "Mr. Popcorn Väg"],
    "145 42": ["Ändå Fredag Gatan", "Kanske Står I Boken Väg", "Wizdomm Gatan"],
    "145 43": ["Han Är Rädd För Sågen Väg", "Saved By Jesus Gatan", "Hyundai Hyundai Bilen Gatan"],
    "145 44": ["Det Blir Inte Mer 80-Tal Än Det Här Väg", "Ska Hem Å Ride'a Väg", "Bra Yeah Väg"],
    "145 45": ["Jag Kör, Jag Kör Väg", "Cheers 4 Beers Gatan", "When Sesh Väg"],
    "145 46": ["POSTNORD Gatan", "IRL Väg", "Is It Pj Or Gatan"],
    "145 47": ["Ba Relli Väg", "Kör En Ray Gatan", "Roasted Maple Väg"],
    "145 48": ["When New Album Gatan", "When Part 1 Gatan", "Tard-Mode Väg"],
    "145 49": ["Jason Becker Och Farsan Gatan", "Biran På Kylning Väg", "Sunkväg"],
    "145 50": ["På Blocket Väg", "Löning På Fredag Gatan", "Birakungen Väg"],
    "145 51": ["Ah Nara Gatan", "De E Bald Väg", "PS4'an E På Väg"],
    "145 52": ["Han Kör Väg", "Att Nån Är Hemma Hos En Och Lägger Sång Gatan", "One Good Day At Väg"],
    "145 53": ["När Tas Första Biran? Väg", "Protsin Väg", "Mnaaa Väg"],
    "145 54": ["Fyyf Gatan", "Älskar Upplägget Väg", "Eeeeeeraaase My Life Gatan"],
    "145 55": ["ICA Nu Då Väg", "Näven I Köksluckorna Gatan", "Pajja Glajjerna Väg"],
    "145 56": ["GB Gatan", "BB Väg", "EZ Livin Väg"],
    "145 57": ["Med Gumman Väg", "Jag Ringer Skatteverket Gatan", "Harpermode Väg"],
    "145 58": ["Vindaloo Väg", "Avdrag Gatan", "Har Serafino Godkänt Det? Gatan"],
    "145 59": ["No Thanks! Gatan", "Vad Säger Polarno Om Det Då? Gatan", "Jag Bryr Mig Inte Väg"],
    "145 77": ["Ska Bara Ta En Kopp Väg", "GAY EXPOSED Väg", "*CAPS LOCK* VÄGEN", "Combo Stig"],
    "145 78": ["Rawdog Gatan", "Big Night Gatan", "Lufta Dogge Väg"],
};


export const defaultCity = "Stockholm";
export const defaultCounty = "Norsborg";
export const defaultCountry = "Sweden";

export const otherCities = ["Baghdad", "New York", "Uppsala", "Västerås"];
export const otherCountries = ["Afrika", "Indien", "Grekland", "Nigeria"];

export const messages = {
    labels: {
        name: "Name",
        street: "Street",
        zipCode: "Zip Code",
        county: "County",
        location: "Location"
    },
    title: "Mail Sorting Game",
    headerTitle: "MAIL SORTING SIMULATOR",
    instructions: "Sort letters by the two last digits in the ZIP code. You can get fired if you make too many mistakes, the timer runs out, or if you get caught stealing.",
    correctMessage: "Correct!",
    incorrectMessage: "Incorrect.",
    levelUpMessage: "Level Up! Welcome to {level} Mode!",
    inhalePowderFoundMessage: "You found Inhale Powder!",
    cashFoundMessage: "You found ${amount}! It's a power-up!",
    totalCashPocketedMessage: "Total Cash Pocketed: ${totalCash}",
    firedCaughtStealingMessage: "YOU'RE FIRED! You were caught stealing! Final Score: {score} | Total Cash Pocketed: $0",
    firedOutOfTimeMessage: "YOU'RE FIRED! Too slow! Final Score: {score} | Total Cash Pocketed: ${totalCash}",
    firedMistakesMessage: "YOU'RE FIRED! You made too many mistakes! Final Score: {score} | Total Cash Pocketed: ${totalCash}",

    scoreMessage: "Score: {score} | Cash: ${cash}",
    timerMessage: "Time remaining: {time} seconds",
    elementalMessage: "Poison: {poison} | Intoxication: {intoxication}",

    inhalePowderDialogMessage: "This letter contains a strange white powder. Do you want to inhale it?",
    inhalePowderActionText: "Inhale Powder",
    inhalePowderCancelText: "Decline",
    declineInhalePowderMessage: "You declined the Inhale Powder.",

    stealCashDialogMessage: "This letter contains cash. Do you want to steal $${amount}?",
    stealCashActionText: "Steal Cash",
    stealCashCancelText: "Decline",
    caughtStealingMessage: "You were caught stealing! Cash pocketed: $0",
    pocketCashMessage: "You pocketed ${amount}",
    declineStealMessage: "You declined the cash.",
    outLabel: "OUT",
    unknownZipCode: "???",
    outgoingLetterMessage: "This letter needs to be sorted as OUT",
};