export const messages = {

    labels: {
        name: "Name",
        street: "Street",
        zipCode: "Zip Code",
        county: "County",
        location: "Location"
    },
    headerTitle: "PIGEONHOLED",
    instructions: "",
    startGame: "Level 1",
    level1Dialog: "All Stockholm letters should be sorted by the last two digits in the zip code!",
    level2Dialog: "Other Swedish cities go in the SE box",
    level3Dialog: "Norway goes in NO",
    level4Dialog: "Dennmark goes in DK",
    level5Dialog: "Other European countries go in EU",
    level6Dialog: "Put American letters in USA",
    level7Dialog: "Put African letters in AFRICA",
    level8Dialog: "Put Asian letters in ASIA",
    level9Dialog: "You're doing great! Just keep an eye out for letters missing information. These should be put in BIN",
    correctMessage: "Correct!",
    incorrectMessage: "Incorrect.",
    firedOutOfTimeMessage: "YOU'RE FIRED! Too slow!",
    firedMistakesMessage: "YOU'RE FIRED! You made too many mistakes!",

    livesMessage: "Lives: {lives}",
    cashMessage: "Cash: ${cash}",
    timerMessage: "Time remaining: {time} seconds",
};

export const addresses = {
    "Level 1": [
        { zipCode: "126 20", county: "Hägersten", streets: ["Fleminggatan", "Hägersjövägen", "Hägersten Torg"], city: "Stockholm", country: "Sweden", sortAs: "20" },
        { zipCode: "145 23", county: "Vårby", streets: ["Vårby Gårdsvägen", "Vårby Allé", "Bäckvägen"], city: "Stockholm", country: "Sweden", sortAs: "23" },
        { zipCode: "147 24", county: "Rönninge", streets: ["Rönninge Allé", "Bergsvägen", "Solrosvägen"], city: "Stockholm", country: "Sweden", sortAs: "24" },
        { zipCode: "137 30", county: "Västerhaninge", streets: ["Haningeleden", "Söderbyvägen", "Hemmingegränd"], city: "Stockholm", country: "Sweden", sortAs: "30" },
        { zipCode: "143 31", county: "Vårby", streets: ["Vårby Allé", "Vårbergsplan", "Vårby Gårdsväg"], city: "Stockholm", country: "Sweden", sortAs: "31" },
        { zipCode: "126 34", county: "Hägersten", streets: ["Fleminggatan", "Västertorp", "Hägersköpingsvägen"], city: "Stockholm", country: "Sweden", sortAs: "34" },
        { zipCode: "143 40", county: "Vårby Gård", streets: ["Vårby Gårdsvägen", "Vårby Park", "Björksundsvägen"], city: "Stockholm", country: "Sweden", sortAs: "40" },
        { zipCode: "145 40", county: "Rönninge", streets: ["Solviksvägen", "Björkvägen", "Rönningebadet"], city: "Stockholm", country: "Sweden", sortAs: "40" },
        { zipCode: "117 41", county: "Liljeholmen", streets: ["Västertorp", "Liljeholmsvägen", "Hälsingegatan"], city: "Stockholm", country: "Sweden", sortAs: "41" },
        { zipCode: "117 44", county: "Liljeholmen", streets: ["Liljeholmsvägen", "Västerbroplan", "Hälsingegatan"], city: "Stockholm", country: "Sweden", sortAs: "44" },
        { zipCode: "128 51", county: "Högdalen", streets: ["Högdalsvägen", "Högdalstorget", "Högdalsparken"], city: "Stockholm", country: "Sweden", sortAs: "51" },
        { zipCode: "145 52", county: "Grödinge", streets: ["Gröndalsvägen", "Gröndalstorget", "Sundsvägen"], city: "Stockholm", country: "Sweden", sortAs: "52" },
        { zipCode: "143 53", county: "Vårby", streets: ["Vårby Allé", "Vårby Gårdsvägen", "Vårbyplan"], city: "Stockholm", country: "Sweden", sortAs: "53" },
        { zipCode: "137 54", county: "Västerhaninge", streets: ["Skogsbo Allé", "Västerhaningevägen", "Fältvägen"], city: "Stockholm", country: "Sweden", sortAs: "54" },
        { zipCode: "126 58", county: "Västertorp", streets: ["Västertorpsvägen", "Borgarskolan", "Västertorpstorg"], city: "Stockholm", country: "Sweden", sortAs: "58" },
        { zipCode: "126 60", county: "Hägersten", streets: ["Hägersjövägen", "Hägersjöplan", "Lillholmstorget"], city: "Stockholm", country: "Sweden", sortAs: "60" },
        { zipCode: "145 68", county: "Norsborg", streets: ["Bredängsvägen", "Norsborgsvägen", "Albyvägen"], city: "Stockholm", country: "Sweden", sortAs: "68" },
        { zipCode: "145 83", county: "Tumba", streets: ["Tumbavägen", "Gröndalsvägen", "Lilla Tumba"], city: "Stockholm", country: "Sweden", sortAs: "83" },
        { zipCode: "137 91", county: "Västerhaninge", streets: ["Västerbyvägen", "Lilla Skogsvägen", "Kungshällagatan"], city: "Stockholm", country: "Sweden", sortAs: "91" },
    ],

    "Level 2": [
        { zipCode: "753 10", county: "Uppsala", streets: ["Stora Torget", "Dragarbrunnsgatan", "Sankt Olofsgatan"], city: "Uppsala", country: "Sweden", sortAs: "SE" },
        { zipCode: "411 04", county: "Gothenburg", streets: ["Avenyn", "Lilla Torget", "Magasinsgatan"], city: "Gothenburg", country: "Sweden", sortAs: "SE" },
        { zipCode: "211 45", county: "Malmö", streets: ["Södra Förstadsgatan", "Pildammsparken", "Linnégatan"], city: "Malmö", country: "Sweden", sortAs: "SE" },
        { zipCode: "222 21", county: "Lund", streets: ["Stora Torget", "Mårtenstorget", "Kyrkogatan"], city: "Lund", country: "Sweden", sortAs: "SE" },
        { zipCode: "722 13", county: "Västerås", streets: ["Stora Gatan", "Sundbyvägen", "Fristadstorget"], city: "Västerås", country: "Sweden", sortAs: "SE" },
        { zipCode: "902 40", county: "Umeå", streets: ["Rådhusesplanaden", "Västerbottensvägen", "Storgatan"], city: "Umeå", country: "Sweden", sortAs: "SE" },
        { zipCode: "371 33", county: "Karlskrona", streets: ["Fiskaregatan", "Trossö", "Ronnebygatan"], city: "Karlskrona", country: "Sweden", sortAs: "SE" },
        { zipCode: "903 27", county: "Umeå", streets: ["Västra Esplanaden", "Björngårdsgatan", "Skolgatan"], city: "Umeå", country: "Sweden", sortAs: "SE" },
        { zipCode: "421 32", county: "Kungsbacka", streets: ["Storgatan", "Brogatan", "Södra vägen"], city: "Kungsbacka", country: "Sweden", sortAs: "SE" },
        { zipCode: "831 33", county: "Östersund", streets: ["Storgatan", "Prästgatan", "Kyrkgatan"], city: "Östersund", country: "Sweden", sortAs: "SE" },
        { zipCode: "611 31", county: "Nyköping", streets: ["Stora Torget", "Västra Storgatan", "Nyköpingsvägen"], city: "Nyköping", country: "Sweden", sortAs: "SE" },
        { zipCode: "444 31", county: "Alingsås", streets: ["Södra Ringgatan", "Västra Gatan", "Storgatan"], city: "Alingsås", country: "Sweden", sortAs: "SE" },
        { zipCode: "581 83", county: "Linköping", streets: ["Tullgårdsgatan", "Västra Storgatan", "Sankt Larsgatan"], city: "Linköping", country: "Sweden", sortAs: "SE" },
        { zipCode: "656 37", county: "Karlstad", streets: ["Västerlånggatan", "Stora Torget", "Torggatan"], city: "Karlstad", country: "Sweden", sortAs: "SE" },
        { zipCode: "753 35", county: "Uppsala", streets: ["Hälsingegatan", "Vaksalagatan", "Kungsgatan"], city: "Uppsala", country: "Sweden", sortAs: "SE" },
        { zipCode: "412 56", county: "Gothenburg", streets: ["Kungsportsavenyn", "Korsgatan", "Götabergsgatan"], city: "Gothenburg", country: "Sweden", sortAs: "SE" },
        { zipCode: "265 34", county: "Helsingborg", streets: ["Stortorget", "Kullagatan", "Norra Hamngatan"], city: "Helsingborg", country: "Sweden", sortAs: "SE" },
        { zipCode: "231 22", county: "Landskrona", streets: ["Södra Strandgatan", "Färjeleden", "Lilla Strandgatan"], city: "Landskrona", country: "Sweden", sortAs: "SE" },
        { zipCode: "801 05", county: "Gävle", streets: ["Södra Kungsgatan", "Stortorget", "Nygatan"], city: "Gävle", country: "Sweden", sortAs: "SE" },
        { zipCode: "263 39", county: "Ängelholm", streets: ["Storgatan", "Tågaborg", "Sundsgatan"], city: "Ängelholm", country: "Sweden", sortAs: "SE" },
        { zipCode: "781 30", county: "Borlänge", streets: ["Smedjegatan", "Stora Torget", "Vasagatan"], city: "Borlänge", country: "Sweden", sortAs: "SE" },
    ],


    "Level 3": [
        { zipCode: "4000", county: "Oslo", streets: ["Karl Johans Gate", "Akershus Festning", "Stortinget"], city: "Oslo", country: "Norway", sortAs: "NO" },
        { zipCode: "5000", county: "Bergen", streets: ["Bryggen", "Fløibanen", "Torgallmenningen"], city: "Bergen", country: "Norway", sortAs: "NO" },
        { zipCode: "6000", county: "Stavanger", streets: ["Vikingveien", "Sandnesgaten", "Torpveien"], city: "Stavanger", country: "Norway", sortAs: "NO" },
        { zipCode: "7000", county: "Trondheim", streets: ["Bakklandet", "St. Olavs Gate", "Torget"], city: "Trondheim", country: "Norway", sortAs: "NO" },
        { zipCode: "8000", county: "Tromsø", streets: ["Storgata", "Hurtigrutekaia", "Sjøgata"], city: "Tromsø", country: "Norway", sortAs: "NO" },
        { zipCode: "9000", county: "Bodø", streets: ["Storgata", "Rønvikveien", "Nyholmen"], city: "Bodø", country: "Norway", sortAs: "NO" },
        { zipCode: "3000", county: "Drammen", streets: ["Bragernes Torg", "Storgata", "Strømsø"], city: "Drammen", country: "Norway", sortAs: "NO" },
        { zipCode: "2000", county: "Lillestrøm", streets: ["Storgata", "Akershusveien", "Gågata"], city: "Lillestrøm", country: "Norway", sortAs: "NO" },
        { zipCode: "1500", county: "Sarpsborg", streets: ["Kirkegata", "Vesterøyveien", "Hafslundveien"], city: "Sarpsborg", country: "Norway", sortAs: "NO" },
        { zipCode: "1600", county: "Fredrikstad", streets: ["Brogata", "Storgata", "Folkets Hus"], city: "Fredrikstad", country: "Norway", sortAs: "NO" },
        { zipCode: "5001", county: "Haugesund", streets: ["Kirkegata", "Vågen", "Torggata"], city: "Haugesund", country: "Norway", sortAs: "NO" }
    ],


    "Level 4": [
        { zipCode: "1001", county: "Copenhagen", streets: ["Nyhavn", "Strøget", "Vesterbrogade"], city: "Copenhagen", country: "Denmark", sortAs: "DK" },
        { zipCode: "2001", county: "Aarhus", streets: ["Aarhus Ø", "Strandvejen", "Søndergade"], city: "Aarhus", country: "Denmark", sortAs: "DK" },
        { zipCode: "3001", county: "Odense", streets: ["Kongensgade", "Havnegade", "Vesterbro"], city: "Odense", country: "Denmark", sortAs: "DK" },
        { zipCode: "4001", county: "Aalborg", streets: ["Sankt Marie Gade", "Bollerslev", "Jens Bangs Stenhus"], city: "Aalborg", country: "Denmark", sortAs: "DK" },
        { zipCode: "5001", county: "Esbjerg", streets: ["Kongensgade", "Skolegade", "Grønningen"], city: "Esbjerg", country: "Denmark", sortAs: "DK" },
        { zipCode: "6000", county: "Kolding", streets: ["Helligkorsgade", "Vesterbrogade", "Slotssøvejen"], city: "Kolding", country: "Denmark", sortAs: "DK" },
        { zipCode: "7000", county: "Fredericia", streets: ["Vestre Ringvej", "Søndergade", "Jernbanegade"], city: "Fredericia", country: "Denmark", sortAs: "DK" },
        { zipCode: "8000", county: "Randers", streets: ["Niels Ebbesens Gade", "Vestergrav", "Glamsbjergvej"], city: "Randers", country: "Denmark", sortAs: "DK" },
        { zipCode: "9000", county: "Aarhus", streets: ["Langelandsgade", "Skovbakken", "Silkeborgvej"], city: "Aarhus", country: "Denmark", sortAs: "DK" },
        { zipCode: "1500", county: "Odense", streets: ["Jernbanegade", "Tårnvej", "Møllebakken"], city: "Odense", country: "Denmark", sortAs: "DK" },
        { zipCode: "2000", county: "Copenhagen", streets: ["Amagerbrogade", "Vesterbrogade", "Rådhuspladsen"], city: "Copenhagen", country: "Denmark", sortAs: "DK" }
    ],

    "Level 5": [
        { zipCode: "10100", county: "Vienna", streets: ["Stephansplatz", "Mariahilfer Strasse", "Gumpendorfer Strasse"], city: "Vienna", country: "Austria", sortAs: "EU" },
        { zipCode: "1000", county: "Brussels", streets: ["Grand Place", "Rue de la Loi", "Avenue Louise"], city: "Brussels", country: "Belgium", sortAs: "EU" },
        { zipCode: "15010", county: "Prague", streets: ["Old Town Square", "Wenceslas Square", "Charles Bridge"], city: "Prague", country: "Czech Republic", sortAs: "EU" },
        { zipCode: "20000", county: "Sofia", streets: ["Vitosha Boulevard", "St. Alexander Nevsky Cathedral", "Sofia Square"], city: "Sofia", country: "Bulgaria", sortAs: "EU" },
        { zipCode: "10100", county: "Budapest", streets: ["Andrássy Avenue", "Heroes' Square", "Váci Street"], city: "Budapest", country: "Hungary", sortAs: "EU" },
        { zipCode: "1100", county: "Amsterdam", streets: ["Dam Square", "Leidseplein", "Prinsengracht"], city: "Amsterdam", country: "Netherlands", sortAs: "EU" },
        { zipCode: "75001", county: "Paris", streets: ["Champs-Élysées", "Rue de Rivoli", "Montmartre"], city: "Paris", country: "France", sortAs: "EU" },
        { zipCode: "80100", county: "Rome", streets: ["Via del Corso", "Piazza Venezia", "Vatican City"], city: "Rome", country: "Italy", sortAs: "EU" },
        { zipCode: "28000", county: "Lisbon", streets: ["Avenida da Liberdade", "Praça do Comércio", "Baixa"], city: "Lisbon", country: "Portugal", sortAs: "EU" },
        { zipCode: "31000", county: "Madrid", streets: ["Gran Vía", "Puerta del Sol", "Plaza Mayor"], city: "Madrid", country: "Spain", sortAs: "EU" },
        { zipCode: "1000", county: "Zagreb", streets: ["Ilica", "Trg bana Jelačića", "Tkalčićeva"], city: "Zagreb", country: "Croatia", sortAs: "EU" },
        { zipCode: "11000", county: "Belgrade", streets: ["Knez Mihailova", "Terazije", "Skadarlija"], city: "Belgrade", country: "Serbia", sortAs: "EU" },
        { zipCode: "04000", county: "Berlin", streets: ["Unter den Linden", "Brandenburger Tor", "Alexanderplatz"], city: "Berlin", country: "Germany", sortAs: "EU" },
        { zipCode: "8001", county: "Zurich", streets: ["Bahnhofstrasse", "Lake Zurich", "Old Town"], city: "Zurich", country: "Switzerland", sortAs: "EU" },
        { zipCode: "60100", county: "Luxembourg City", streets: ["Grand Rue", "Place d'Armes", "Luxembourg Gardens"], city: "Luxembourg City", country: "Luxembourg", sortAs: "EU" },
        { zipCode: "69001", county: "Lyon", streets: ["Place Bellecour", "Vieux Lyon", "Parc de la Tête d'Or"], city: "Lyon", country: "France", sortAs: "EU" },
        { zipCode: "2000", county: "Stockholm", streets: ["Gamla Stan", "Drottninggatan", "Kungsträdgården"], city: "Stockholm", country: "Sweden", sortAs: "EU" },
        { zipCode: "10100", county: "Helsinki", streets: ["Senate Square", "Esplanade", "Uspenski Cathedral"], city: "Helsinki", country: "Finland", sortAs: "EU" },
        { zipCode: "7000", county: "Copenhagen", streets: ["Nyhavn", "Strøget", "Vesterbrogade"], city: "Copenhagen", country: "Denmark", sortAs: "EU" },
        { zipCode: "1000", county: "Oslo", streets: ["Karl Johans Gate", "Akershus Festning", "Stortinget"], city: "Oslo", country: "Norway", sortAs: "EU" },
        { zipCode: "3000", county: "Tallinn", streets: ["Tallinn Old Town", "Viru Street", "Toompea Castle"], city: "Tallinn", country: "Estonia", sortAs: "EU" },
        { zipCode: "4000", county: "Riga", streets: ["Freedom Monument", "Old Town", "Albert Street"], city: "Riga", country: "Latvia", sortAs: "EU" },
        { zipCode: "5000", county: "Vilnius", streets: ["Gedimino Avenue", "Vilnius Cathedral", "Pilis Street"], city: "Vilnius", country: "Lithuania", sortAs: "EU" },
        { zipCode: "7000", county: "Bucharest", streets: ["Piata Unirii", "Calea Victoriei", "Parliament Palace"], city: "Bucharest", country: "Romania", sortAs: "EU" }
    ],

    "Level 6": [
        { zipCode: "90210", county: "California", streets: ["Rodeo Drive", "Santa Monica Blvd", "Venice Beach"], city: "Beverly Hills", country: "USA", sortAs: "USA" },
        { zipCode: "10001", county: "New York", streets: ["5th Avenue", "Broadway", "Times Square"], city: "New York", country: "USA", sortAs: "USA" },
        { zipCode: "30301", county: "Georgia", streets: ["Peachtree Street", "Buckhead", "Midtown"], city: "Atlanta", country: "USA", sortAs: "USA" },
        { zipCode: "94110", county: "California", streets: ["Fisherman's Wharf", "Golden Gate Park", "Mission District"], city: "San Francisco", country: "USA", sortAs: "USA" },
        { zipCode: "02118", county: "Massachusetts", streets: ["Back Bay", "Beacon Hill", "Fenway Park"], city: "Boston", country: "USA", sortAs: "USA" },
        { zipCode: "60601", county: "Illinois", streets: ["Michigan Avenue", "Willis Tower", "Navy Pier"], city: "Chicago", country: "USA", sortAs: "USA" },
        { zipCode: "73301", county: "Texas", streets: ["Congress Avenue", "6th Street", "Texas State Capitol"], city: "Austin", country: "USA", sortAs: "USA" },
        { zipCode: "33101", county: "Florida", streets: ["Ocean Drive", "South Beach", "Little Havana"], city: "Miami", country: "USA", sortAs: "USA" },
        { zipCode: "90001", county: "California", streets: ["Sunset Boulevard", "Hollywood Boulevard", "Venice Beach"], city: "Los Angeles", country: "USA", sortAs: "USA" },
        { zipCode: "75201", county: "Texas", streets: ["Main Street", "Klyde Warren Park", "Deep Ellum"], city: "Dallas", country: "USA", sortAs: "USA" },
        { zipCode: "94103", county: "California", streets: ["Castro District", "Golden Gate Bridge", "Twin Peaks"], city: "San Francisco", country: "USA", sortAs: "USA" },
        { zipCode: "80202", county: "Colorado", streets: ["LoDo District", "16th Street Mall", "Union Station"], city: "Denver", country: "USA", sortAs: "USA" },
        { zipCode: "63101", county: "Missouri", streets: ["Gateway Arch", "Forest Park", "Washington Avenue"], city: "St. Louis", country: "USA", sortAs: "USA" },
        { zipCode: "94102", county: "California", streets: ["Hayes Valley", "Civic Center", "Opera House"], city: "San Francisco", country: "USA", sortAs: "USA" },
        { zipCode: "98101", county: "Washington", streets: ["Pike Place Market", "Space Needle", "Chinatown"], city: "Seattle", country: "USA", sortAs: "USA" },
        { zipCode: "43201", county: "Ohio", streets: ["Short North", "High Street", "Arena District"], city: "Columbus", country: "USA", sortAs: "USA" },
        { zipCode: "30303", county: "Georgia", streets: ["Centennial Olympic Park", "Georgia State University", "Underground Atlanta"], city: "Atlanta", country: "USA", sortAs: "USA" },
        { zipCode: "89109", county: "Nevada", streets: ["Las Vegas Boulevard", "The Strip", "Fremont Street"], city: "Las Vegas", country: "USA", sortAs: "USA" },
        { zipCode: "45202", county: "Ohio", streets: ["Fountain Square", "Over-the-Rhine", "Great American Tower"], city: "Cincinnati", country: "USA", sortAs: "USA" },
        { zipCode: "55101", county: "Minnesota", streets: ["Rice Park", "Como Park", "Mississippi River"], city: "St. Paul", country: "USA", sortAs: "USA" },
        { zipCode: "94109", county: "California", streets: ["Nob Hill", "Chinatown", "North Beach"], city: "San Francisco", country: "USA", sortAs: "USA" },
        { zipCode: "20001", county: "District of Columbia", streets: ["Dupont Circle", "The White House", "National Mall"], city: "Washington D.C.", country: "USA", sortAs: "USA" },
        { zipCode: "85001", county: "Arizona", streets: ["Camelback Mountain", "Desert Botanical Garden", "Downtown Phoenix"], city: "Phoenix", country: "USA", sortAs: "USA" },
        { zipCode: "38103", county: "Tennessee", streets: ["Beale Street", "Sun Studio", "Graceland"], city: "Memphis", country: "USA", sortAs: "USA" },
        { zipCode: "53202", county: "Wisconsin", streets: ["Lakefront", "Brady Street", "Third Ward"], city: "Milwaukee", country: "USA", sortAs: "USA" },
        { zipCode: "44101", county: "Ohio", streets: ["Cleveland Browns Stadium", "Rock and Roll Hall of Fame", "West Side Market"], city: "Cleveland", country: "USA", sortAs: "USA" },
        { zipCode: "27511", county: "North Carolina", streets: ["Downtown Cary", "SAS Campus", "Jordan Lake"], city: "Cary", country: "USA", sortAs: "USA" }
    ],
    "Level 7": [
        { zipCode: "10101", county: "Algiers", streets: ["Boulevard Amirouche", "Rue Didouche Mourad", "Place Maurice Audin"], city: "Algiers", country: "Algeria", sortAs: "AFRICA" },
        { zipCode: "2000", county: "Angola", streets: ["Rua da Paz", "Avenida 4 de Fevereiro", "Praça da Independência"], city: "Luanda", country: "Angola", sortAs: "AFRICA" },
        { zipCode: "3000", county: "Benin", streets: ["Avenue Jean-Paul II", "Avenue de l'Indépendance", "Place des Martyrs"], city: "Cotonou", country: "Benin", sortAs: "AFRICA" },
        { zipCode: "4000", county: "Botswana", streets: ["Mophane Road", "Lobatse Road", "Khwai Road"], city: "Gaborone", country: "Botswana", sortAs: "AFRICA" },
        { zipCode: "5000", county: "Burkina Faso", streets: ["Avenue Kadiogo", "Rue de la Revolution", "Place des Nations"], city: "Ouagadougou", country: "Burkina Faso", sortAs: "AFRICA" },
        { zipCode: "6000", county: "Burundi", streets: ["Avenue de l'Indépendance", "Bujumbura Road", "Place de la Paix"], city: "Gitega", country: "Burundi", sortAs: "AFRICA" },
        { zipCode: "7000", county: "Cabo Verde", streets: ["Rua de Lisboa", "Avenida Amílcar Cabral", "Praça de Dona Maria"], city: "Praia", country: "Cabo Verde", sortAs: "AFRICA" },
        { zipCode: "8000", county: "Cameroon", streets: ["Avenue Charles Atangana", "Avenue de l'Indépendance", "Place de la République"], city: "Yaoundé", country: "Cameroon", sortAs: "AFRICA" },
        { zipCode: "9000", county: "Central African Republic", streets: ["Avenue Barthélemy Boganda", "Boulevard de l'Indépendance", "Place de la Réconciliation"], city: "Bangui", country: "Central African Republic", sortAs: "AFRICA" },
        { zipCode: "10000", county: "Chad", streets: ["Avenue Charles de Gaulle", "Place de la Nation", "Rue des Martyrs"], city: "N'Djamena", country: "Chad", sortAs: "AFRICA" },
        { zipCode: "11000", county: "Comoros", streets: ["Avenue de l'Union", "Rue de la Paix", "Place de la République"], city: "Moroni", country: "Comoros", sortAs: "AFRICA" },
        { zipCode: "12000", county: "Congo (Republic of the)", streets: ["Avenue de l'OUA", "Boulevard de la République", "Place de la Victoire"], city: "Brazzaville", country: "Congo (Republic of the)", sortAs: "AFRICA" },
        { zipCode: "13000", county: "Congo (Democratic Republic of the)", streets: ["Avenue Kabila", "Boulevard du 30 Juin", "Place Victoire"], city: "Kinshasa", country: "Congo (Democratic Republic of the)", sortAs: "AFRICA" },
        { zipCode: "14000", county: "Djibouti", streets: ["Avenue Mohamed Dileita", "Rue Ali Sudi", "Place de la République"], city: "Djibouti", country: "Djibouti", sortAs: "AFRICA" },
        { zipCode: "15000", county: "Egypt", streets: ["Tahrir Square", "Cairo Opera House", "Avenue Ramses"], city: "Cairo", country: "Egypt", sortAs: "AFRICA" },
        { zipCode: "16000", county: "Equatorial Guinea", streets: ["Avenue de la République", "Boulevard de la Liberté", "Place de la Paix"], city: "Malabo", country: "Equatorial Guinea", sortAs: "AFRICA" },
        { zipCode: "17000", county: "Eritrea", streets: ["Avenue Harnet", "Asmara Road", "Place de la Révolution"], city: "Asmara", country: "Eritrea", sortAs: "AFRICA" },
        { zipCode: "18000", county: "Eswatini", streets: ["Avenue Mbandzeni", "Luhleko Road", "Place Nhlangano"], city: "Mbabane", country: "Eswatini", sortAs: "AFRICA" },
        { zipCode: "19000", county: "Ethiopia", streets: ["Addis Ababa Avenue", "Bole Road", "Meskel Square"], city: "Addis Ababa", country: "Ethiopia", sortAs: "AFRICA" },
        { zipCode: "20000", county: "Gabon", streets: ["Avenue de l'Indépendance", "Boulevard Triomphal", "Place de l'Unité"], city: "Libreville", country: "Gabon", sortAs: "AFRICA" },
        { zipCode: "21000", county: "Gambia", streets: ["Westfield Street", "Kairaba Avenue", "Albert Market"], city: "Banjul", country: "Gambia", sortAs: "AFRICA" },
        { zipCode: "22000", county: "Ghana", streets: ["Kwame Nkrumah Circle", "Oxford Street", "Independence Square"], city: "Accra", country: "Ghana", sortAs: "AFRICA" },
        { zipCode: "23000", county: "Guinea", streets: ["Avenue de la République", "Conakry Road", "Place du 2 Octobre"], city: "Conakry", country: "Guinea", sortAs: "AFRICA" },
        { zipCode: "24000", county: "Guinea-Bissau", streets: ["Avenida 24 de Setembro", "Place de l'Indépendance", "Rua da Liberdade"], city: "Bissau", country: "Guinea-Bissau", sortAs: "AFRICA" },
        { zipCode: "25000", county: "Ivory Coast", streets: ["Boulevard des Martyrs", "Rue de la Paix", "Place de la République"], city: "Abidjan", country: "Ivory Coast", sortAs: "AFRICA" },
        { zipCode: "26000", county: "Kenya", streets: ["Moi Avenue", "Kenya National Theatre", "Uhuru Park"], city: "Nairobi", country: "Kenya", sortAs: "AFRICA" },
        { zipCode: "27000", county: "Lesotho", streets: ["Kingsway", "Avenue de l'Indépendance", "Place Mahlohonolo"], city: "Maseru", country: "Lesotho", sortAs: "AFRICA" },
        { zipCode: "28000", county: "Liberia", streets: ["Broad Street", "Tubman Boulevard", "Roberts International Airport Road"], city: "Monrovia", country: "Liberia", sortAs: "AFRICA" },
        { zipCode: "29000", county: "Libya", streets: ["Al Fatah Street", "Al-Manara Square", "Shari'a Al-Huda"], city: "Tripoli", country: "Libya", sortAs: "AFRICA" },
        { zipCode: "30000", county: "Madagascar", streets: ["Avenue de l'Indépendance", "Avenue de la République", "Place de l'Indépendance"], city: "Antananarivo", country: "Madagascar", sortAs: "AFRICA" },
        { zipCode: "31000", county: "Malawi", streets: ["Kachere Avenue", "Chikondi Drive", "Mzuzu Road"], city: "Lilongwe", country: "Malawi", sortAs: "AFRICA" },
        { zipCode: "32000", county: "Mali", streets: ["Avenue Moussa Tavele", "Boulevard de l'Indépendance", "Place de l'Emploi"], city: "Bamako", country: "Mali", sortAs: "AFRICA" },
        { zipCode: "33000", county: "Mauritania", streets: ["Avenue Moktar Ould Daddah", "Place du Nouakchott", "Rue de l'Indépendance"], city: "Nouakchott", country: "Mauritania", sortAs: "AFRICA" },
        { zipCode: "34000", county: "Mauritius", streets: ["Avenue Sir Seewoosagur Ramgoolam", "Place d'Armes", "Bain Boeuf Road"], city: "Port Louis", country: "Mauritius", sortAs: "AFRICA" },
        { zipCode: "35000", county: "Morocco", streets: ["Avenue Mohammed V", "Place Mohammed Ben Abdallah", "Rue de la Liberté"], city: "Rabat", country: "Morocco", sortAs: "AFRICA" },
        { zipCode: "36000", county: "Mozambique", streets: ["Avenida 24 de Julho", "Avenida Samora Machel", "Praça de Independência"], city: "Maputo", country: "Mozambique", sortAs: "AFRICA" },
        { zipCode: "37000", county: "Namibia", streets: ["Post Street Mall", "Independence Avenue", "Windhoek Central Square"], city: "Windhoek", country: "Namibia", sortAs: "AFRICA" },
        { zipCode: "38000", county: "Niger", streets: ["Avenue de la République", "Place de la Concorde", "Boulevard Mariama"], city: "Niamey", country: "Niger", sortAs: "AFRICA" },
        { zipCode: "39000", county: "Nigeria", streets: ["Avenue Ahmadu Bello", "Lekki Road", "National Stadium Road"], city: "Abuja", country: "Nigeria", sortAs: "AFRICA" },
        { zipCode: "40000", county: "Rwanda", streets: ["Kigali Heights", "Avenue de la Paix", "Kimisagara Road"], city: "Kigali", country: "Rwanda", sortAs: "AFRICA" },
        { zipCode: "41000", county: "São Tomé and Príncipe", streets: ["Avenida 12 de Julho", "Rua de São João", "Praça da Independência"], city: "São Tomé", country: "São Tomé and Príncipe", sortAs: "AFRICA" },
        { zipCode: "42000", county: "Senegal", streets: ["Avenue Lamine Gueye", "Place de la Nation", "Avenue Faidherbe"], city: "Dakar", country: "Senegal", sortAs: "AFRICA" },
        { zipCode: "43000", county: "Seychelles", streets: ["Victoria Avenue", "Anse Royale", "Independence Avenue"], city: "Victoria", country: "Seychelles", sortAs: "AFRICA" },
        { zipCode: "44000", county: "Sierra Leone", streets: ["Tudor Road", "Main Motor Road", "Fourah Bay Road"], city: "Freetown", country: "Sierra Leone", sortAs: "AFRICA" },
        { zipCode: "45000", county: "Somalia", streets: ["Mogadishu Road", "Avenue de la République", "Place de l'Indépendance"], city: "Mogadishu", country: "Somalia", sortAs: "AFRICA" },
        { zipCode: "46000", county: "South Africa", streets: ["Adderley Street", "Long Street", "Nelson Mandela Boulevard"], city: "Cape Town", country: "South Africa", sortAs: "AFRICA" },
        { zipCode: "47000", county: "South Sudan", streets: ["Juba Road", "Nile Avenue", "Independence Square"], city: "Juba", country: "South Sudan", sortAs: "AFRICA" },
        { zipCode: "48000", county: "Sudan", streets: ["Avenue Abdel Nasser", "Al-Muqrin Street", "Khartoum Road"], city: "Khartoum", country: "Sudan", sortAs: "AFRICA" },
        { zipCode: "49000", county: "Togo", streets: ["Avenue de l'Indépendance", "Boulevard du 13 Janvier", "Place de la Paix"], city: "Lomé", country: "Togo", sortAs: "AFRICA" },
        { zipCode: "50000", county: "Tunisia", streets: ["Avenue Habib Bourguiba", "Rue de l'Indépendance", "Place de la République"], city: "Tunis", country: "Tunisia", sortAs: "AFRICA" },
        { zipCode: "51000", county: "Uganda", streets: ["Kampala Road", "Jinja Road", "Entebbe Road"], city: "Kampala", country: "Uganda", sortAs: "AFRICA" },
        { zipCode: "52000", county: "Zambia", streets: ["Independence Avenue", "Cairo Road", "Manda Hill"], city: "Lusaka", country: "Zambia", sortAs: "AFRICA" },
        { zipCode: "53000", county: "Zimbabwe", streets: ["Nelson Mandela Avenue", "Samora Machel Avenue", "Robert Mugabe Road"], city: "Harare", country: "Zimbabwe", sortAs: "AFRICA" }
    ],
    "Level 8": [
        { zipCode: "1000", county: "Afghanistan", streets: ["Kabul Street", "Shahr-e-Naw", "Karte Parwan"], city: "Kabul", country: "Afghanistan", sortAs: "ASIA" },
        { zipCode: "2000", county: "Armenia", streets: ["Northern Avenue", "Republic Square", "Mashtots Avenue"], city: "Yerevan", country: "Armenia", sortAs: "ASIA" },
        { zipCode: "3000", county: "Azerbaijan", streets: ["Fountain Square", "Baku Boulevard", "Nizami Street"], city: "Baku", country: "Azerbaijan", sortAs: "ASIA" },
        { zipCode: "4000", county: "Bahrain", streets: ["King Faisal Highway", "Corniche Road", "Al Khalifa Avenue"], city: "Manama", country: "Bahrain", sortAs: "ASIA" },
        { zipCode: "5000", county: "Bangladesh", streets: ["Dhanmondi", "Shahbagh", "Gulshan Avenue"], city: "Dhaka", country: "Bangladesh", sortAs: "ASIA" },
        { zipCode: "6000", county: "Bhutan", streets: ["Norzin Lam", "Changangkha Lhakhang", "Thimphu Valley Road"], city: "Thimphu", country: "Bhutan", sortAs: "ASIA" },
        { zipCode: "7000", county: "Brunei", streets: ["Jalan Sultan", "Jalan Tutong", "Jalan Kianggeh"], city: "Bandar Seri Begawan", country: "Brunei", sortAs: "ASIA" },
        { zipCode: "8000", county: "Cambodia", streets: ["Sisowath Quay", "Monivong Boulevard", "Russian Boulevard"], city: "Phnom Penh", country: "Cambodia", sortAs: "ASIA" },
        { zipCode: "9000", county: "China", streets: ["Wangfujing Street", "Nanjing Road", "Xidan Street"], city: "Beijing", country: "China", sortAs: "ASIA" },
        { zipCode: "10000", county: "Cyprus", streets: ["Makarios Avenue", "Archbishop Street", "Ledra Street"], city: "Nicosia", country: "Cyprus", sortAs: "ASIA" },
        { zipCode: "11000", county: "Georgia", streets: ["Rustaveli Avenue", "Freedom Square", "Tbilisi Avenue"], city: "Tbilisi", country: "Georgia", sortAs: "ASIA" },
        { zipCode: "12000", county: "India", streets: ["Connaught Place", "Marine Drive", "Park Street"], city: "New Delhi", country: "India", sortAs: "ASIA" },
        { zipCode: "13000", county: "Indonesia", streets: ["Jalan Thamrin", "Jalan Sudirman", "Kota Tua"], city: "Jakarta", country: "Indonesia", sortAs: "ASIA" },
        { zipCode: "14000", county: "Iran", streets: ["Vali Asr Street", "Enghelab Street", "Azadi Square"], city: "Tehran", country: "Iran", sortAs: "ASIA" },
        { zipCode: "15000", county: "Iraq", streets: ["Sadoun Street", "Al-Rashid Street", "Al-Kadhimiya"], city: "Baghdad", country: "Iraq", sortAs: "ASIA" },
        { zipCode: "16000", county: "Israel", streets: ["King George Street", "Rothschild Boulevard", "Dizengoff Street"], city: "Tel Aviv", country: "Israel", sortAs: "ASIA" },
        { zipCode: "17000", county: "Japan", streets: ["Shibuya Crossing", "Ginza Street", "Takeshita Street"], city: "Tokyo", country: "Japan", sortAs: "ASIA" },
        { zipCode: "18000", county: "Jordan", streets: ["Rainbow Street", "Shmeisani", "Jabal Amman"], city: "Amman", country: "Jordan", sortAs: "ASIA" },
        { zipCode: "19000", county: "Kazakhstan", streets: ["Republic Avenue", "Zhibek Zholy", "Abai Avenue"], city: "Almaty", country: "Kazakhstan", sortAs: "ASIA" },
        { zipCode: "20000", county: "Kuwait", streets: ["Salmiya", "Fahaheel", "Mubarak Al Kabeer Street"], city: "Kuwait City", country: "Kuwait", sortAs: "ASIA" },
        { zipCode: "21000", county: "Kyrgyzstan", streets: ["Ala-Too Square", "Chui Avenue", "Lenin Street"], city: "Bishkek", country: "Kyrgyzstan", sortAs: "ASIA" },
        { zipCode: "22000", county: "Laos", streets: ["Lane Xang Avenue", "Rue Setthathirath", "Chao Anouvong Park"], city: "Vientiane", country: "Laos", sortAs: "ASIA" },
        { zipCode: "23000", county: "Lebanon", streets: ["Hamra Street", "Rue Verdun", "Ain el-Mreisseh"], city: "Beirut", country: "Lebanon", sortAs: "ASIA" },
        { zipCode: "24000", county: "Malaysia", streets: ["Bukit Bintang", "Jalan Raja Laut", "Petaling Street"], city: "Kuala Lumpur", country: "Malaysia", sortAs: "ASIA" },
        { zipCode: "25000", county: "Maldives", streets: ["Male City", "Ameenee Magu", "Dhiggaru Magu"], city: "Malé", country: "Maldives", sortAs: "ASIA" },
        { zipCode: "26000", county: "Mongolia", streets: ["Chinggis Avenue", "Peace Avenue", "Sukhbaatar Square"], city: "Ulaanbaatar", country: "Mongolia", sortAs: "ASIA" },
        { zipCode: "27000", county: "Myanmar", streets: ["Bogyoke Aung San Road", "Inya Road", "Sule Pagoda Road"], city: "Yangon", country: "Myanmar", sortAs: "ASIA" },
        { zipCode: "28000", county: "Nepal", streets: ["Thamel", "Durbar Square", "Ason Market"], city: "Kathmandu", country: "Nepal", sortAs: "ASIA" },
        { zipCode: "29000", county: "North Korea", streets: ["Kim Il-sung Square", "Ryomyong Street", "Koryo Hotel"], city: "Pyongyang", country: "North Korea", sortAs: "ASIA" },
        { zipCode: "30000", county: "Oman", streets: ["Al Qurm Street", "Mutrah Corniche", "Sultan Qaboos Street"], city: "Muscat", country: "Oman", sortAs: "ASIA" },
        { zipCode: "31000", county: "Pakistan", streets: ["Mall Road", "Jinnah Avenue", "Shahrah-e-Faisal"], city: "Islamabad", country: "Pakistan", sortAs: "ASIA" },
        { zipCode: "32000", county: "Palestine", streets: ["Al-Quds Street", "Al-Manara Square", "Khalil Ibrahim Street"], city: "Ramallah", country: "Palestine", sortAs: "ASIA" },
        { zipCode: "33000", county: "Philippines", streets: ["Roxas Boulevard", "Ayala Avenue", "Quiapo Church"], city: "Manila", country: "Philippines", sortAs: "ASIA" },
        { zipCode: "34000", county: "Qatar", streets: ["Al Corniche", "Doha Souq", "West Bay"], city: "Doha", country: "Qatar", sortAs: "ASIA" },
        { zipCode: "35000", county: "Russia", streets: ["Tverskaya Street", "Red Square", "Nevsky Prospect"], city: "Moscow", country: "Russia", sortAs: "ASIA" },
        { zipCode: "36000", county: "Saudi Arabia", streets: ["King Abdulaziz Road", "Al-Tahlia Street", "Mekkah Road"], city: "Riyadh", country: "Saudi Arabia", sortAs: "ASIA" },
        { zipCode: "37000", county: "Singapore", streets: ["Orchard Road", "Marina Bay", "Clarke Quay"], city: "Singapore", country: "Singapore", sortAs: "ASIA" },
        { zipCode: "38000", county: "South Korea", streets: ["Gangnam", "Insadong", "Myeongdong"], city: "Seoul", country: "South Korea", sortAs: "ASIA" },
        { zipCode: "39000", county: "Sri Lanka", streets: ["Galle Road", "Colombo Fort", "Borella"], city: "Colombo", country: "Sri Lanka", sortAs: "ASIA" },
        { zipCode: "40000", county: "Syria", streets: ["Damascus Road", "Al-Mazzeh", "Malki"], city: "Damascus", country: "Syria", sortAs: "ASIA" },
        { zipCode: "41000", county: "Tajikistan", streets: ["Rudaki Avenue", "Shahidon Street", "Panjshanbe Market"], city: "Dushanbe", country: "Tajikistan", sortAs: "ASIA" },
        { zipCode: "42000", county: "Thailand", streets: ["Sukhumvit Road", "Khao San Road", "Rattanakosin"], city: "Bangkok", country: "Thailand", sortAs: "ASIA" },
        { zipCode: "43000", county: "Timor-Leste", streets: ["Av. Presidente Nicolau Lobato", "Bairo Pite", "Comoro"], city: "Dili", country: "Timor-Leste", sortAs: "ASIA" },
        { zipCode: "44000", county: "Turkey", streets: ["Istiklal Avenue", "Taksim Square", "Beyoğlu"], city: "Istanbul", country: "Turkey", sortAs: "ASIA" },
        { zipCode: "45000", county: "Turkmenistan", streets: ["Ashgabat Avenue", "Bitarap Street", "Halk Hakydasy"], city: "Ashgabat", country: "Turkmenistan", sortAs: "ASIA" },
        { zipCode: "46000", county: "United Arab Emirates", streets: ["Sheikh Zayed Road", "Dubai Marina", "Al Fahidi Street"], city: "Dubai", country: "United Arab Emirates", sortAs: "ASIA" },
        { zipCode: "47000", county: "Uzbekistan", streets: ["Amir Timur Square", "Pushkin Street", "Bukhara Street"], city: "Tashkent", country: "Uzbekistan", sortAs: "ASIA" },
        { zipCode: "48000", county: "Vietnam", streets: ["Hoan Kiem Lake", "Phan Dinh Phung", "Nguyen Hue"], city: "Hanoi", country: "Vietnam", sortAs: "ASIA" },
        { zipCode: "49000", county: "Yemen", streets: ["Sana'a Road", "Al-Tahrir Square", "Zubairi Street"], city: "Sana'a", country: "Yemen", sortAs: "ASIA" }
    ],

    "Level 9": [
        { sortAs: "BIN" }
    ]
};



export const firstNames = [
    "Adam", "Albin", "Alfred", "Alma", "Alvar", "Alve", "Amir", "Anna", "Anton", "Aron", "Astrid",
    "August", "Axel", "Benjamin", "Bill", "Björn", "Charlie", "Christina", "Casper", "Dante", "Ebba",
    "Ebbi", "Eduard", "Elias", "Elina", "Ellie", "Emma", "Emil", "Erik", "Eva", "Filip", "Folke", "Frans",
    "Gabriel", "Gustav", "Hanna", "Harry", "Henry", "Hjalmar", "Hugo", "Ivar", "Jack", "Jan", "Johan", "Joel",
    "Julian", "Karin", "Karl", "Kerstin", "Kian", "Knut", "Lars", "Levi", "Liam", "Lena", "Leo", "Leon", "Lili",
    "Lina", "Linnéa", "Lisa", "Liva", "Loke", "Love", "Lucas", "Ludvig", "Lukas", "Luna", "Madeleine", "Malte",
    "Maria", "Marie", "Matheo", "Max", "Melker", "Melvin", "Mikael", "Milan", "Milo", "Milton", "Nils", "Noel",
    "Omar", "Oliver", "Olle", "Otis", "Otto", "Oskar", "Per", "Peter", "Philip", "Sam", "Sara", "Sigge", "Sixten",
    "Sophia", "Theo", "Thomas", "Valter", "Vera", "Viggo", "Vincent", "William", "Wilhelm", "Walter", "Xavier",
    "Ylva", "Åke", "Ava", "Liam", "Zara", "Ibrahim", "Hiroshi", "Fatima", "Carlos", "Mohammed", "Priya", "Luca",
    "Elena", "Maya", "Amira", "Sebastian", "Lucas", "Leo", "Kai", "Ximena", "Youssef", "Ayaan", "Kofi", "Jade",
    "Xander", "Nia", "Thalia", "Noah", "Keisha", "Santiago", "Leila", "Evelyn", "Tariq", "Sanaa", "Soraya",
    "Matteo", "Jin", "Tenzin", "Jun", "Ravi", "Gita", "Chinonso", "Oluwaseun", "Dinesh", "Rhea", "Javier",
    "Zane", "Tariq", "Hassan", "Arvind", "Ramon", "Tomas", "Lina", "Juan", "Alicia", "Carmen", "Lucia", "Zara",
    "Mariam", "Khalid", "Asma", "Sami", "Hassan", "Yara", "Chloe", "Noelle", "Anjali", "Indira", "Ayesha", "Anwar",
    "Rashid", "Zubair", "Matilda", "Sven", "Isha", "Benedicta", "Chetan", "Kwame", "Musa", "Kwabena", "Felix",
    "Zahra", "Isabella", "Nadia", "Eloise", "Oscar", "Eva", "Jasmin", "Diana", "Karim", "Zoya", "Nina", "Hadiya",
    "Lorenzo", "Esme", "Leandro", "Aurelia", "Boris", "Omar", "Mira", "Raj", "Yasmin", "Diana", "Gustavo", "Tunde",
    "Lola", "Dimitri", "Ksenia", "Sasha", "Nikolai", "Svetlana", "Darya", "Rostislav", "Karolina", "Zbigniew",
    "Andrei", "Elena", "Milena", "Zofia", "Lucian", "Bogdan", "Aditya", "Disha", "Pooja", "Lalita", "Swati", "Manoj",
    "Alejandro", "Leonardo", "Marcelo", "Francisco", "Andres", "Violet", "Fernanda", "Luz", "Joaquin", "Victoria",
    "Marta", "Carla", "Lucas", "Giulia", "Matilde", "Luisa", "Mia", "Sofia", "Gabriela", "Camila", "Isadora", "Anya",
    "Sofia", "Giovanni", "Zoe", "Camila", "Anastasia", "Rania", "Katerina", "Elif", "Leyla", "Mira", "Nina"
];

export const lastNames = [
    "Abrahamsson", "Ahmed", "Ali", "Andreasson", "Arvidsson", "Axelsson", "Bengtsson", "Berger", "Berggren",
    "Bergkvist", "Bergman", "Bergström", "Blom", "Blomberg", "Blomkvist", "Blomquist", "Blomqvist", "Björk",
    "Björklund", "Björnsson", "Claesson", "Danielsson", "Dahlberg", "Ek", "Ekberg", "Ekblad", "Ekholm", "Ekström",
    "Eliasson", "Engström", "Eriksson", "Eklund", "Fallberg", "Fredriksson", "Fransson", "Frantzén", "Frisk",
    "Gunnarsson", "Gustafsson", "Gyllenhaal", "Hallberg", "Hansson", "Hedberg", "Hellström", "Henriksson",
    "Hermansson", "Holberg", "Holmgren", "Holmqvist", "Hultén", "Hägg", "Hällström", "Jakobsson", "Jansson",
    "Johansson", "Jonsson", "Jönsson", "Karlsson", "Klintberg", "Klingberg", "Klintström", "Knutsson", "Krüger",
    "Kullberg", "Kullén", "Kurck", "Larsson", "Lindberg", "Lindblad", "Lindell", "Lindgren", "Lindholm", "Lindkvist",
    "Lindner", "Lindroos", "Lindström", "Lindqvist", "Lindsten", "Lindwall", "Ljungberg", "Ljunggren", "Löfgren",
    "Lundberg", "Lundgren", "Lundkvist", "Lundmark", "Lundström", "Magnusson", "Mattsson", "Malmberg", "Malmgren",
    "Malmqvist", "Malmström", "Månsson", "Martinsson", "Melin", "Mellberg", "Mellgren", "Mellqvist", "Mellström",
    "Mohamed", "Molin", "Moller", "Mörner", "Mörtberg", "Mörtén", "Mörtstedt", "Norberg", "Nordin", "Nyberg",
    "Nyström", "Olsson", "Olofsson", "Persson", "Pettersson", "Pålsson", "Sandberg", "Sandström", "Sjögren",
    "Sjöberg", "Ström", "Strömberg", "Sundberg", "Sundström", "Söderberg", "Tage", "Viklund", "Wallin", "Åberg",
    "Åkesson", "Åström", "Nguyen", "Tanaka", "Li", "Wang", "Chavez", "Ramirez", "Gomez", "Hernandez", "Lopez",
    "Martinez", "Perez", "Garcia", "Rodriguez", "Kim", "Park", "Choi", "Lee", "Jang", "Song", "Kang", "Yang",
    "Kumar", "Patel", "Sharma", "Singh", "Mehta", "Gupta", "Reddy", "Naidu", "Ibrahim", "Abdullah", "Aliyu",
    "Mohammed", "Bello", "Aminu", "Zhang", "Xu", "Chen", "Liu", "Mao", "Zhao", "Wang", "Tan", "Ng", "Tan", "Khoo",
    "Fong", "Jansen", "De Vries", "Van den Berg", "De Jong", "Smit", "Bakker", "Hofman", "Visser", "Van Dijk",
    "Schmidt", "Müller", "Schneider", "Weber", "Fischer", "Becker", "Wagner", "Hoffmann", "Klein", "Zimmermann",
    "Schulz", "Bauer", "Weiss", "Meier", "Böhm", "Krause", "Steiner", "Schwarz", "Hartmann", "Bauer", "Hansen",
    "Johansen", "Olsen", "Eriksen", "Nilsen", "Andersen", "Larsen", "Jensen", "Pedersen", "Kristensen", "Wang",
    "Tso", "Lau", "Wu", "Yip", "Cheng", "Shen", "Tanaka", "Abe", "Takeda", "Nakamura", "Yamamoto", "Matsumoto",
    "Inoue", "Fujimoto", "Kobayashi", "Yoshida", "Chung", "Yip", "Hong", "Huang", "Nguyen", "Tran", "Pham", "Luu",
    "Fong", "Yeo", "Liu", "Lin", "Sullivan", "Kelly", "O'Connor", "Murphy", "Smith", "Davis", "Miller", "Wilson",
    "Taylor", "Moore", "Clark", "Johnson", "Lewis", "Scott", "Roberts", "Walker", "Young", "Allen", "Harris",
    "Baker", "Gonzalez", "Ramirez", "Adams", "Nelson", "Hill", "Carter", "Mitchell", "Perez", "Green", "Phillips",
    "King", "Campbell", "Davis", "Evans", "Turner", "Thomas", "Bashir", "Aliyev", "Khan", "Khoury", "Sanchez"
];

