export const messages = {

    labels: {
        name: "Name",
        street: "Street",
        zipCode: "Zip Code",
        county: "County",
        location: "Location"
    },
    headerTitle: "PIGEONHOLED",
    instructions: "",
    startGame: "Level 1",
    level1Dialog: "All Stockholm letters should be sorted by the last two digits in the zip code!",
    level2Dialog: "Other Swedish cities go in the SE box.",
    level3Dialog: "Norwegian cities go in the NO box.",
    level4Dialog: "Danish cities go in the DK box.",
    level5Dialog: "Baltic cities (Latvia, Estonia, Lithuania) go in the BLTC box.",
    level6Dialog: "Other European countries go in the EUR box.",
    level7Dialog: "Put NorthAmerican letters in the NAM box (USA, Canada, Mexico).",
    level8Dialog: "South American cities go in the SAM box.",
    level9Dialog: "Asian cities go in the ASIA box.",
    level10Dialog: "African cities go in the AFRICA box.",
    level11Dialog: "Caribbean cities go in the CRBN box.",
    level12Dialog: "Central American cities go in the CAM box.",
    level13Dialog: "Oceania cities go in the OCN box.",
    level14Dialog: "If a letter is missing any details, put it in the BIN box.",
    correctMessage: "Correct!",
    incorrectMessage: "Incorrect.",
    firedOutOfTimeMessage: "YOU'RE FIRED! Too slow!",
    firedMistakesMessage: "YOU'RE FIRED! You made too many mistakes!",

    livesMessage: "Lives: {lives}",
    cashMessage: "Cash: ${cash}",
    timerMessage: "Time remaining: {time} seconds",
};

export const addresses = {
    "Level 1": [
        { zipCode: "126 20", county: "Hägersten", streets: ["Fleminggatan", "Hägersjövägen", "Hägersten Torg"], city: "Stockholm", country: "Sweden", sortAs: "20" },
        { zipCode: "145 23", county: "Vårby", streets: ["Vårby Gårdsvägen", "Vårby Allé", "Bäckvägen"], city: "Stockholm", country: "Sweden", sortAs: "23" },
        { zipCode: "147 24", county: "Rönninge", streets: ["Rönninge Allé", "Bergsvägen", "Solrosvägen"], city: "Stockholm", country: "Sweden", sortAs: "24" },
        { zipCode: "143 31", county: "Vårby", streets: ["Vårby Allé", "Vårbergsplan", "Vårby Gårdsväg"], city: "Stockholm", country: "Sweden", sortAs: "31" },
        { zipCode: "126 34", county: "Hägersten", streets: ["Fleminggatan", "Västertorp", "Hägersköpingsvägen"], city: "Stockholm", country: "Sweden", sortAs: "34" },
        { zipCode: "145 40", county: "Rönninge", streets: ["Solviksvägen", "Björkvägen", "Rönningebadet"], city: "Stockholm", country: "Sweden", sortAs: "40" },
        { zipCode: "117 44", county: "Liljeholmen", streets: ["Liljeholmsvägen", "Västerbroplan", "Hälsingegatan"], city: "Stockholm", country: "Sweden", sortAs: "44" },
        { zipCode: "128 51", county: "Högdalen", streets: ["Högdalsvägen", "Högdalstorget", "Högdalsparken"], city: "Stockholm", country: "Sweden", sortAs: "51" },
        { zipCode: "145 52", county: "Grödinge", streets: ["Gröndalsvägen", "Gröndalstorget", "Sundsvägen"], city: "Stockholm", country: "Sweden", sortAs: "52" },
        { zipCode: "143 53", county: "Vårby", streets: ["Vårby Allé", "Vårby Gårdsvägen", "Vårbyplan"], city: "Stockholm", country: "Sweden", sortAs: "53" },
        { zipCode: "137 54", county: "Västerhaninge", streets: ["Skogsbo Allé", "Västerhaningevägen", "Fältvägen"], city: "Stockholm", country: "Sweden", sortAs: "54" },
        { zipCode: "126 58", county: "Västertorp", streets: ["Västertorpsvägen", "Borgarskolan", "Västertorpstorg"], city: "Stockholm", country: "Sweden", sortAs: "58" },
        { zipCode: "126 60", county: "Hägersten", streets: ["Hägersjövägen", "Hägersjöplan", "Lillholmstorget"], city: "Stockholm", country: "Sweden", sortAs: "60" },
        { zipCode: "145 68", county: "Norsborg", streets: ["Bredängsvägen", "Norsborgsvägen", "Albyvägen"], city: "Stockholm", country: "Sweden", sortAs: "68" },
        { zipCode: "145 83", county: "Tumba", streets: ["Tumbavägen", "Gröndalsvägen", "Lilla Tumba"], city: "Stockholm", country: "Sweden", sortAs: "83" },
        { zipCode: "137 91", county: "Västerhaninge", streets: ["Västerbyvägen", "Lilla Skogsvägen", "Kungshällagatan"], city: "Stockholm", country: "Sweden", sortAs: "91" },
    ],

    "Level 2": [
        { zipCode: "753 10", county: "Uppsala", streets: ["Stora Torget", "Dragarbrunnsgatan", "Sankt Olofsgatan"], city: "Uppsala", country: "Sweden", sortAs: "SE" },
        { zipCode: "411 04", county: "Göteborg", streets: ["Avenyn", "Lilla Torget", "Magasinsgatan"], city: "Gothenburg", country: "Sweden", sortAs: "SE" },
        { zipCode: "211 45", county: "Malmö", streets: ["Södra Förstadsgatan", "Pildammsparken", "Linnégatan"], city: "Malmö", country: "Sweden", sortAs: "SE" },
        { zipCode: "222 21", county: "Lund", streets: ["Stora Torget", "Mårtenstorget", "Kyrkogatan"], city: "Lund", country: "Sweden", sortAs: "SE" },
        { zipCode: "722 13", county: "Västerås", streets: ["Stora Gatan", "Sundbyvägen", "Fristadstorget"], city: "Västerås", country: "Sweden", sortAs: "SE" },
        { zipCode: "902 40", county: "Umeå", streets: ["Rådhusesplanaden", "Västerbottensvägen", "Storgatan"], city: "Umeå", country: "Sweden", sortAs: "SE" },
        { zipCode: "371 33", county: "Karlskrona", streets: ["Fiskaregatan", "Trossö", "Ronnebygatan"], city: "Karlskrona", country: "Sweden", sortAs: "SE" },
        { zipCode: "903 27", county: "Umeå", streets: ["Västra Esplanaden", "Björngårdsgatan", "Skolgatan"], city: "Umeå", country: "Sweden", sortAs: "SE" },
        { zipCode: "421 32", county: "Kungsbacka", streets: ["Storgatan", "Brogatan", "Södra vägen"], city: "Kungsbacka", country: "Sweden", sortAs: "SE" },
        { zipCode: "831 33", county: "Östersund", streets: ["Storgatan", "Prästgatan", "Kyrkgatan"], city: "Östersund", country: "Sweden", sortAs: "SE" },
        { zipCode: "611 31", county: "Nyköping", streets: ["Stora Torget", "Västra Storgatan", "Nyköpingsvägen"], city: "Nyköping", country: "Sweden", sortAs: "SE" },
        { zipCode: "444 31", county: "Alingsås", streets: ["Södra Ringgatan", "Västra Gatan", "Storgatan"], city: "Alingsås", country: "Sweden", sortAs: "SE" },
        { zipCode: "581 83", county: "Linköping", streets: ["Tullgårdsgatan", "Västra Storgatan", "Sankt Larsgatan"], city: "Linköping", country: "Sweden", sortAs: "SE" },
        { zipCode: "656 37", county: "Karlstad", streets: ["Västerlånggatan", "Stora Torget", "Torggatan"], city: "Karlstad", country: "Sweden", sortAs: "SE" },
        { zipCode: "753 35", county: "Uppsala", streets: ["Hälsingegatan", "Vaksalagatan", "Kungsgatan"], city: "Uppsala", country: "Sweden", sortAs: "SE" },
        { zipCode: "265 34", county: "Helsingborg", streets: ["Stortorget", "Kullagatan", "Norra Hamngatan"], city: "Helsingborg", country: "Sweden", sortAs: "SE" },
        { zipCode: "231 22", county: "Landskrona", streets: ["Södra Strandgatan", "Färjeleden", "Lilla Strandgatan"], city: "Landskrona", country: "Sweden", sortAs: "SE" },
        { zipCode: "801 05", county: "Gävle", streets: ["Södra Kungsgatan", "Stortorget", "Nygatan"], city: "Gävle", country: "Sweden", sortAs: "SE" },
        { zipCode: "263 39", county: "Ängelholm", streets: ["Storgatan", "Tågaborg", "Sundsgatan"], city: "Ängelholm", country: "Sweden", sortAs: "SE" },
        { zipCode: "781 30", county: "Borlänge", streets: ["Smedjegatan", "Stora Torget", "Vasagatan"], city: "Borlänge", country: "Sweden", sortAs: "SE" },
    ],

    "Level 3": [
        { zipCode: "4000", county: "Oslo", streets: ["Karl Johans Gate", "Akershus Festning", "Stortinget"], city: "Oslo", country: "Norway", sortAs: "NO" },
        { zipCode: "5000", county: "Bergen", streets: ["Bryggen", "Fløibanen", "Torgallmenningen"], city: "Bergen", country: "Norway", sortAs: "NO" },
        { zipCode: "6000", county: "Stavanger", streets: ["Vikingveien", "Sandnesgaten", "Torpveien"], city: "Stavanger", country: "Norway", sortAs: "NO" },
        { zipCode: "7000", county: "Trondheim", streets: ["Bakklandet", "St. Olavs Gate", "Torget"], city: "Trondheim", country: "Norway", sortAs: "NO" },
        { zipCode: "8000", county: "Tromsø", streets: ["Storgata", "Hurtigrutekaia", "Sjøgata"], city: "Tromsø", country: "Norway", sortAs: "NO" },
        { zipCode: "9000", county: "Bodø", streets: ["Storgata", "Rønvikveien", "Nyholmen"], city: "Bodø", country: "Norway", sortAs: "NO" },
        { zipCode: "3000", county: "Drammen", streets: ["Bragernes Torg", "Storgata", "Strømsø"], city: "Drammen", country: "Norway", sortAs: "NO" },
        { zipCode: "2000", county: "Lillestrøm", streets: ["Storgata", "Akershusveien", "Gågata"], city: "Lillestrøm", country: "Norway", sortAs: "NO" },
        { zipCode: "1500", county: "Sarpsborg", streets: ["Kirkegata", "Vesterøyveien", "Hafslundveien"], city: "Sarpsborg", country: "Norway", sortAs: "NO" },
        { zipCode: "1600", county: "Fredrikstad", streets: ["Brogata", "Storgata", "Folkets Hus"], city: "Fredrikstad", country: "Norway", sortAs: "NO" },
        { zipCode: "5001", county: "Haugesund", streets: ["Kirkegata", "Vågen", "Torggata"], city: "Haugesund", country: "Norway", sortAs: "NO" }
    ],

    "Level 4": [
        { zipCode: "1001", county: "Copenhagen", streets: ["Nyhavn", "Strøget", "Vesterbrogade"], city: "Copenhagen", country: "Denmark", sortAs: "DK" },
        { zipCode: "2001", county: "Aarhus", streets: ["Aarhus Ø", "Strandvejen", "Søndergade"], city: "Aarhus", country: "Denmark", sortAs: "DK" },
        { zipCode: "3001", county: "Odense", streets: ["Kongensgade", "Havnegade", "Vesterbro"], city: "Odense", country: "Denmark", sortAs: "DK" },
        { zipCode: "4001", county: "Aalborg", streets: ["Sankt Marie Gade", "Bollerslev", "Jens Bangs Stenhus"], city: "Aalborg", country: "Denmark", sortAs: "DK" },
        { zipCode: "5001", county: "Esbjerg", streets: ["Kongensgade", "Skolegade", "Grønningen"], city: "Esbjerg", country: "Denmark", sortAs: "DK" },
        { zipCode: "6000", county: "Kolding", streets: ["Helligkorsgade", "Vesterbrogade", "Slotssøvejen"], city: "Kolding", country: "Denmark", sortAs: "DK" },
        { zipCode: "7000", county: "Fredericia", streets: ["Vestre Ringvej", "Søndergade", "Jernbanegade"], city: "Fredericia", country: "Denmark", sortAs: "DK" },
        { zipCode: "8000", county: "Randers", streets: ["Niels Ebbesens Gade", "Vestergrav", "Glamsbjergvej"], city: "Randers", country: "Denmark", sortAs: "DK" },
        { zipCode: "9000", county: "Aarhus", streets: ["Langelandsgade", "Skovbakken", "Silkeborgvej"], city: "Aarhus", country: "Denmark", sortAs: "DK" },
        { zipCode: "1500", county: "Odense", streets: ["Jernbanegade", "Tårnvej", "Møllebakken"], city: "Odense", country: "Denmark", sortAs: "DK" },
        { zipCode: "2000", county: "Copenhagen", streets: ["Amagerbrogade", "Vesterbrogade", "Rådhuspladsen"], city: "Copenhagen", country: "Denmark", sortAs: "DK" }
    ],

    "Level 5": [
        { zipCode: "3000", county: "Tallinn", streets: ["Tallinn Old Town", "Viru Street", "Toompea Castle"], city: "Tallinn", country: "Estonia", sortAs: "BLTC" },
        { zipCode: "4000", county: "Riga", streets: ["Freedom Monument", "Old Town", "Albert Street"], city: "Riga", country: "Latvia", sortAs: "BLTC" },
        { zipCode: "5000", county: "Vilnius", streets: ["Gedimino Avenue", "Vilnius Cathedral", "Pilis Street"], city: "Vilnius", country: "Lithuania", sortAs: "BLTC" },
    ],

    "Level 6": [
        { zipCode: "1001", county: "Albania", streets: ["Rruga e Durrësit", "Rruga Myslym Shyri", "Bulevardi Zogu I"], city: "Tirana", country: "Albania", sortAs: "EUR" },
        { zipCode: "AD500", county: "Andorra", streets: ["Avinguda Meritxell", "Carrer de la Unió", "Carrer Prat de la Creu"], city: "Andorra la Vella", country: "Andorra", sortAs: "EUR" },
        { zipCode: "0010", county: "Armenia", streets: ["Mashtots Avenue", "Tigran Mets Avenue", "Northern Avenue"], city: "Yerevan", country: "Armenia", sortAs: "EUR" },
        { zipCode: "1010", county: "Austria", streets: ["Graben", "Mariahilfer Straße", "Ringstraße"], city: "Vienna", country: "Austria", sortAs: "EUR" },
        { zipCode: "AZ1001", county: "Azerbaijan", streets: ["Nizami Street", "Heydar Aliyev Avenue", "Fuzuli Square"], city: "Baku", country: "Azerbaijan", sortAs: "EUR" },
        { zipCode: "220030", county: "Belarus", streets: ["Independence Avenue", "Zybitskaya Street", "Pobeditelei Avenue"], city: "Minsk", country: "Belarus", sortAs: "EUR" },
        { zipCode: "1000", county: "Belgium", streets: ["Rue Neuve", "Avenue Louise", "Rue des Bouchers"], city: "Brussels", country: "Belgium", sortAs: "EUR" },
        { zipCode: "71000", county: "Bosnia and Herzegovina", streets: ["Ferhadija Street", "Titova Street", "Maršala Tita"], city: "Sarajevo", country: "Bosnia and Herzegovina", sortAs: "EUR" },
        { zipCode: "1000", county: "Bulgaria", streets: ["Vitosha Boulevard", "Dondukov Boulevard", "Tsarigradsko Shose"], city: "Sofia", country: "Bulgaria", sortAs: "EUR" },
        { zipCode: "10000", county: "Croatia", streets: ["Ilica Street", "Radiceva Street", "Tkalciceva Street"], city: "Zagreb", country: "Croatia", sortAs: "EUR" },
        { zipCode: "1097", county: "European Cyprus", streets: ["Makarios Avenue", "Ledra Street", "Archbishop Kyprianou Street"], city: "Nicosia", country: "Cyprus", sortAs: "EUR" },
        { zipCode: "11000", county: "Czech Republic", streets: ["Wenceslas Square", "Parizska Street", "Karlova Street"], city: "Prague", country: "Czech Republic", sortAs: "EUR" },
        { zipCode: "00100", county: "Finland", streets: ["Esplanadi", "Aleksanterinkatu", "Mannerheimintie"], city: "Helsinki", country: "Finland", sortAs: "EUR" },
        { zipCode: "75001", county: "France", streets: ["Champs-Élysées", "Rue de Rivoli", "Boulevard Haussmann"], city: "Paris", country: "France", sortAs: "EUR" },
        { zipCode: "0101", county: "European Georgia", streets: ["Rustaveli Avenue", "Chavchavadze Avenue", "Agmashenebeli Avenue"], city: "Tbilisi", country: "Georgia", sortAs: "EUR" },
        { zipCode: "10115", county: "Germany", streets: ["Unter den Linden", "Kurfürstendamm", "Friedrichstraße"], city: "Berlin", country: "Germany", sortAs: "EUR" },
        { zipCode: "10552", county: "Greece", streets: ["Ermou Street", "Panepistimiou Street", "Adrianou Street"], city: "Athens", country: "Greece", sortAs: "EUR" },
        { zipCode: "1051", county: "Hungary", streets: ["Andrássy Avenue", "Váci Street", "Rákóczi Road"], city: "Budapest", country: "Hungary", sortAs: "EUR" },
        { zipCode: "101", county: "Iceland", streets: ["Laugavegur", "Bankastræti", "Austurstræti"], city: "Reykjavík", country: "Iceland", sortAs: "EUR" },
        { zipCode: "D01", county: "Ireland", streets: ["Grafton Street", "O'Connell Street", "Henry Street"], city: "Dublin", country: "Ireland", sortAs: "EUR" },
        { zipCode: "00184", county: "Italy", streets: ["Via del Corso", "Via Veneto", "Via Condotti"], city: "Rome", country: "Italy", sortAs: "EUR" },
        { zipCode: "9490", county: "Liechtenstein", streets: ["Städtle", "Fürst-Franz-Josef-Strasse", "Herrengasse"], city: "Vaduz", country: "Liechtenstein", sortAs: "EUR" },
        { zipCode: "L-1510", county: "Luxembourg", streets: ["Avenue de la Liberté", "Rue des Bains", "Grand-Rue"], city: "Luxembourg", country: "Luxembourg", sortAs: "EUR" },
        { zipCode: "VLT 1110", county: "Malta", streets: ["Republic Street", "Merchant Street", "St. Paul’s Street"], city: "Valletta", country: "Malta", sortAs: "EUR" },
        { zipCode: "2001", county: "Moldova", streets: ["Stefan cel Mare Boulevard", "Puskin Street", "Negruzzi Boulevard"], city: "Chisinau", country: "Moldova", sortAs: "EUR" },
        { zipCode: "98000", county: "Monaco", streets: ["Avenue Princesse Grace", "Rue Grimaldi", "Boulevard des Moulins"], city: "Monaco", country: "Monaco", sortAs: "EUR" },
        { zipCode: "81000", county: "Montenegro", streets: ["Njegoševa Street", "Hercegovačka Street", "Slobode Boulevard"], city: "Podgorica", country: "Montenegro", sortAs: "EUR" },
        { zipCode: "1011", county: "Netherlands", streets: ["Damrak", "Kalverstraat", "Leidsestraat"], city: "Amsterdam", country: "Netherlands", sortAs: "EUR" },
        { zipCode: "1000", county: "North Macedonia", streets: ["Macedonia Street", "Ilindenska Boulevard", "Dimitrie Chupovski"], city: "Skopje", country: "North Macedonia", sortAs: "EUR" },
        { zipCode: "00-001", county: "Poland", streets: ["Nowy Świat", "Krakowskie Przedmieście", "Marszałkowska"], city: "Warsaw", country: "Poland", sortAs: "EUR" },
        { zipCode: "1100-000", county: "Portugal", streets: ["Rua Augusta", "Avenida da Liberdade", "Rua do Carmo"], city: "Lisbon", country: "Portugal", sortAs: "EUR" },
        { zipCode: "010001", county: "Romania", streets: ["Calea Victoriei", "Bulevardul Magheru", "Bulevardul Unirii"], city: "Bucharest", country: "Romania", sortAs: "EUR" },
        { zipCode: "123000", county: "Russia", streets: ["Arbat Street", "Tverskaya Street", "Kuznetsky Most"], city: "Moscow", country: "Russia", sortAs: "EUR" },
        { zipCode: "47890", county: "San Marino", streets: ["Via Eugippo", "Contrada Omerelli", "Piazzale della Libertà"], city: "San Marino", country: "San Marino", sortAs: "EUR" },
        { zipCode: "11000", county: "Serbia", streets: ["Knez Mihailova Street", "Skadarlija", "Bulevar Kralja Aleksandra"], city: "Belgrade", country: "Serbia", sortAs: "EUR" },
        { zipCode: "811 01", county: "Slovakia", streets: ["Hviezdoslavovo námestie", "Štefánikova Street", "Obchodná Street"], city: "Bratislava", country: "Slovakia", sortAs: "EUR" },
        { zipCode: "1000", county: "Slovenia", streets: ["Čop Street", "Miklošičeva Street", "Prešernova Street"], city: "Ljubljana", country: "Slovenia", sortAs: "EUR" },
        { zipCode: "28001", county: "Spain", streets: ["Gran Via", "Calle de Alcalá", "Paseo de la Castellana"], city: "Madrid", country: "Spain", sortAs: "EUR" },
        { zipCode: "8001", county: "Switzerland", streets: ["Bahnhofstrasse", "Limmatquai", "Niederdorfstrasse"], city: "Zurich", country: "Switzerland", sortAs: "EUR" },
        { zipCode: "34100", county: "European Turkey", streets: ["Istiklal Avenue", "Bagdat Avenue", "Ataturk Boulevard"], city: "Istanbul", country: "Europe", sortAs: "EUR" },
        { zipCode: "01001", county: "Ukraine", streets: ["Khreshchatyk Street", "Andriivskyi Uzviz", "Bessarabska Square"], city: "Kyiv", country: "Ukraine", sortAs: "EUR" },
        { zipCode: "SW1A 1AA", county: "United Kingdom", streets: ["Oxford Street", "Regent Street", "Piccadilly Circus"], city: "London", country: "United Kingdom", sortAs: "EUR" },
        { zipCode: "00120", county: "Vatican City", streets: ["St. Peter's Square", "Via della Conciliazione", "Borgo Pio"], city: "Vatican City", country: "Vatican City", sortAs: "EUR" }
    ],

    "Level 7": [
        { zipCode: "10001", county: "New York", streets: ["5th Avenue", "Broadway", "Times Square"], city: "New York", country: "USA", sortAs: "N-AM" },
        { zipCode: "30301", county: "Georgia", streets: ["Peachtree Street", "Buckhead", "Midtown"], city: "Atlanta", country: "USA", sortAs: "N-AM" },
        { zipCode: "94110", county: "California", streets: ["Fisherman's Wharf", "Golden Gate Park", "Mission District"], city: "San Francisco", country: "USA", sortAs: "N-AM" },
        { zipCode: "02118", county: "Massachusetts", streets: ["Back Bay", "Beacon Hill", "Fenway Park"], city: "Boston", country: "USA", sortAs: "N-AM" },
        { zipCode: "60601", county: "Illinois", streets: ["Michigan Avenue", "Willis Tower", "Navy Pier"], city: "Chicago", country: "USA", sortAs: "N-AM" },
        { zipCode: "73301", county: "Texas", streets: ["Congress Avenue", "6th Street", "Texas State Capitol"], city: "Austin", country: "USA", sortAs: "N-AM" },
        { zipCode: "33101", county: "Florida", streets: ["Ocean Drive", "South Beach", "Little Havana"], city: "Miami", country: "USA", sortAs: "N-AM" },
        { zipCode: "90001", county: "California", streets: ["Sunset Boulevard", "Hollywood Boulevard", "Venice Beach"], city: "Los Angeles", country: "USA", sortAs: "N-AM" },
        { zipCode: "75201", county: "Texas", streets: ["Main Street", "Klyde Warren Park", "Deep Ellum"], city: "Dallas", country: "USA", sortAs: "N-AM" },
        { zipCode: "94103", county: "California", streets: ["Castro District", "Golden Gate Bridge", "Twin Peaks"], city: "San Francisco", country: "USA", sortAs: "N-AM" },
        { zipCode: "80202", county: "Colorado", streets: ["LoDo District", "16th Street Mall", "Union Station"], city: "Denver", country: "USA", sortAs: "N-AM" },
        { zipCode: "63101", county: "Missouri", streets: ["Gateway Arch", "Forest Park", "Washington Avenue"], city: "St. Louis", country: "USA", sortAs: "N-AM" },
        { zipCode: "94102", county: "California", streets: ["Hayes Valley", "Civic Center", "Opera House"], city: "San Francisco", country: "USA", sortAs: "N-AM" },
        { zipCode: "98101", county: "Washington", streets: ["Pike Place Market", "Space Needle", "Chinatown"], city: "Seattle", country: "USA", sortAs: "N-AM" },
        { zipCode: "43201", county: "Ohio", streets: ["Short North", "High Street", "Arena District"], city: "Columbus", country: "USA", sortAs: "N-AM" },
        { zipCode: "30303", county: "Georgia", streets: ["Centennial Olympic Park", "Georgia State University", "Underground Atlanta"], city: "Atlanta", country: "USA", sortAs: "N-AM" },
        { zipCode: "89109", county: "Nevada", streets: ["Las Vegas Boulevard", "The Strip", "Fremont Street"], city: "Las Vegas", country: "USA", sortAs: "N-AM" },
        { zipCode: "94109", county: "California", streets: ["Nob Hill", "Chinatown", "North Beach"], city: "San Francisco", country: "USA", sortAs: "N-AM" },
        { zipCode: "20001", county: "District of Columbia", streets: ["Dupont Circle", "The White House", "National Mall"], city: "Washington D.C.", country: "USA", sortAs: "N-AM" },
        { zipCode: "85001", county: "Arizona", streets: ["Camelback Mountain", "Desert Botanical Garden", "Downtown Phoenix"], city: "Phoenix", country: "USA", sortAs: "N-AM" },
        { zipCode: "38103", county: "Tennessee", streets: ["Beale Street", "Sun Studio", "Graceland"], city: "Memphis", country: "USA", sortAs: "N-AM" },
        { zipCode: "53202", county: "Wisconsin", streets: ["Lakefront", "Brady Street", "Third Ward"], city: "Milwaukee", country: "USA", sortAs: "N-AM" },
        { zipCode: "44101", county: "Ohio", streets: ["Cleveland Browns Stadium", "Rock and Roll Hall of Fame", "West Side Market"], city: "Cleveland", country: "USA", sortAs: "N-AM" },

        { zipCode: "2000", county: "Ontario", streets: ["Queen Street", "King Street", "University Avenue"], city: "Toronto", country: "Canada", sortAs: "N-AM" },
        { zipCode: "H3A 1B7", county: "Quebec", streets: ["Rue Sainte-Catherine", "Avenue des Pins", "Montreal Street"], city: "Montreal", country: "Canada", sortAs: "N-AM" },
        { zipCode: "75001", county: "Mexico City", streets: ["Avenida Reforma", "Calle 5 de Febrero", "Avenida Insurgentes"], city: "Mexico City", country: "Mexico", sortAs: "N-AM" },
        { zipCode: "64000", county: "Nuevo León", streets: ["Avenida Juárez", "Calle Madero", "Calle Padre Mier"], city: "Monterrey", country: "Mexico", sortAs: "N-AM" },
        { zipCode: "98000", county: "Baja California", streets: ["Boulevard Costero", "Calle Primera", "Avenida Revolución"], city: "Tijuana", country: "Mexico", sortAs: "N-AM" },

        { zipCode: "V6B 1A1", county: "British Columbia", streets: ["Granville Street", "Robson Street", "Stanley Park"], city: "Vancouver", country: "Canada", sortAs: "N-AM" },
        { zipCode: "K1A 0B1", county: "Ontario", streets: ["Wellington Street", "Rideau Street", "Parliament Hill"], city: "Ottawa", country: "Canada", sortAs: "N-AM" },
        { zipCode: "T2P 3T1", county: "Alberta", streets: ["Stephen Avenue", "6th Avenue SW", "Prince Island Park"], city: "Calgary", country: "Canada", sortAs: "N-AM" },
        { zipCode: "M5A 1A1", county: "Ontario", streets: ["Front Street", "St. Lawrence Market", "Toronto Islands"], city: "Toronto", country: "Canada", sortAs: "N-AM" },
        { zipCode: "R3C 1S1", county: "Manitoba", streets: ["Portage Avenue", "Assiniboine Park", "The Forks"], city: "Winnipeg", country: "Canada", sortAs: "N-AM" },

        { zipCode: "99501", county: "Alaska", streets: ["Downtown Anchorage", "4th Avenue", "Kincaid Park"], city: "Anchorage", country: "USA", sortAs: "N-AM" },
        { zipCode: "99701", county: "Alaska", streets: ["College Road", "Northrim Bank", "Chena River"], city: "Fairbanks", country: "USA", sortAs: "N-AM" },
        { zipCode: "99723", county: "Alaska", streets: ["Main Street", "Fort Greely", "Sullivan Road"], city: "Delta Junction", country: "USA", sortAs: "N-AM" },
        { zipCode: "99801", county: "Alaska", streets: ["Douglas Island", "Downtown Juneau", "Gold Creek"], city: "Juneau", country: "USA", sortAs: "N-AM" },
        { zipCode: "99775", county: "Alaska", streets: ["Kuskokwim River", "Bethel", "Ekwok"], city: "Bethel", country: "USA", sortAs: "N-AM" }
    ],


    "Level 8": [
        { zipCode: "10000", county: "Argentina", streets: ["Avenida 9 de Julio", "Avenida Corrientes", "Calle Florida"], city: "Buenos Aires", country: "Argentina", sortAs: "S-AM" },
        { zipCode: "11000", county: "Bolivia", streets: ["El Prado", "Calle Jaén", "Avenida Arce"], city: "La Paz", country: "Bolivia", sortAs: "S-AM" },
        { zipCode: "12000", county: "Brazil", streets: ["Avenida Paulista", "Copacabana Beach", "Ipanema Beach"], city: "Brasília", country: "Brazil", sortAs: "S-AM" },
        { zipCode: "13000", county: "Chile", streets: ["Avenida Apoquindo", "Barrio Bellavista", "Paseo Ahumada"], city: "Santiago", country: "Chile", sortAs: "S-AM" },
        { zipCode: "14000", county: "Colombia", streets: ["Carrera Séptima", "Calle 26", "Zona Rosa"], city: "Bogotá", country: "Colombia", sortAs: "S-AM" },
        { zipCode: "15000", county: "Ecuador", streets: ["Avenida de los Shyris", "Calle García Moreno", "Calle Benalcázar"], city: "Quito", country: "Ecuador", sortAs: "S-AM" },
        { zipCode: "16000", county: "Guyana", streets: ["Main Street", "Camp Street", "Brickdam"], city: "Georgetown", country: "Guyana", sortAs: "S-AM" },
        { zipCode: "17000", county: "Paraguay", streets: ["Avenida Mariscal López", "Calle Palma", "Avenida Eusebio Ayala"], city: "Asunción", country: "Paraguay", sortAs: "S-AM" },
        { zipCode: "18000", county: "Peru", streets: ["Jirón de la Unión", "Avenida Arequipa", "Malecón de Miraflores"], city: "Lima", country: "Peru", sortAs: "S-AM" },
        { zipCode: "19000", county: "Suriname", streets: ["Domineestraat", "Heerenstraat", "Kwattaweg"], city: "Paramaribo", country: "Suriname", sortAs: "S-AM" },
        { zipCode: "20000", county: "Uruguay", streets: ["Avenida 18 de Julio", "Rambla de Montevideo", "Peatonal Sarandí"], city: "Montevideo", country: "Uruguay", sortAs: "S-AM" },
        { zipCode: "21000", county: "Venezuela", streets: ["Avenida Bolívar", "Avenida Urdaneta", "Paseo Los Próceres"], city: "Caracas", country: "Venezuela", sortAs: "S-AM" }
    ],

    "Level 9": [
        { zipCode: "1001", county: "Afghanistan", streets: ["Kabul Road", "Shah-e-Do Shamshira Street", "Jade Maiwand"], city: "Kabul", country: "Afghanistan", sortAs: "ASIA" },
        { zipCode: "0002", county: "Armenia", streets: ["Mashtots Avenue", "Tigran Mets Avenue", "Northern Avenue"], city: "Yerevan", country: "Armenia", sortAs: "ASIA" },
        { zipCode: "AZ1000", county: "Azerbaijan", streets: ["Nizami Street", "Heydar Aliyev Avenue", "Azadliq Square"], city: "Baku", country: "Azerbaijan", sortAs: "ASIA" },
        { zipCode: "PO Box 1234", county: "Bahrain", streets: ["Manama Avenue", "Shaikh Khalifa Road", "Budaiya Highway"], city: "Manama", country: "Bahrain", sortAs: "ASIA" },
        { zipCode: "1207", county: "Bangladesh", streets: ["Dhanmondi 27", "Gulshan Avenue", "Motijheel"], city: "Dhaka", country: "Bangladesh", sortAs: "ASIA" },
        { zipCode: "11001", county: "Bhutan", streets: ["Norzin Lam", "Chorten Lam", "Chang Lam"], city: "Thimphu", country: "Bhutan", sortAs: "ASIA" },
        { zipCode: "BB3713", county: "Brunei", streets: ["Jalan Sultan", "Jalan Residency", "Jalan Tutong"], city: "Bandar Seri Begawan", country: "Brunei", sortAs: "ASIA" },
        { zipCode: "12000", county: "Cambodia", streets: ["Norodom Boulevard", "Preah Sisowath Quay", "Monivong Boulevard"], city: "Phnom Penh", country: "Cambodia", sortAs: "ASIA" },
        { zipCode: "100000", county: "China", streets: ["Wangfujing Street", "Nanjing Road", "Chang'an Avenue"], city: "Beijing", country: "China", sortAs: "ASIA" },
        { zipCode: "1097", county: "Asian Cyprus", streets: ["Makarios Avenue", "Ledra Street", "Stasikratous Street"], city: "Nicosia", country: "Cyprus", sortAs: "ASIA" },
        { zipCode: "0101", county: "Asian Georgia", streets: ["Rustaveli Avenue", "Marjanishvili Street", "Chavchavadze Avenue"], city: "Tbilisi", country: "Georgia", sortAs: "ASIA" },
        { zipCode: "110001", county: "India", streets: ["Connaught Place", "Janpath", "MG Road"], city: "New Delhi", country: "India", sortAs: "ASIA" },
        { zipCode: "10110", county: "Indonesia", streets: ["Jalan Sudirman", "Jalan Thamrin", "Jalan Medan Merdeka"], city: "Jakarta", country: "Indonesia", sortAs: "ASIA" },
        { zipCode: "11365", county: "Iran", streets: ["Valiasr Street", "Enghelab Street", "Shariati Street"], city: "Tehran", country: "Iran", sortAs: "ASIA" },
        { zipCode: "10011", county: "Iraq", streets: ["Al-Rasheed Street", "Sadoun Street", "Haifa Street"], city: "Baghdad", country: "Iraq", sortAs: "ASIA" },
        { zipCode: "91950", county: "Israel", streets: ["Ben Yehuda Street", "Jaffa Road", "Herzl Boulevard"], city: "Jerusalem", country: "Israel", sortAs: "ASIA" },
        { zipCode: "100-0001", county: "Japan", streets: ["Ginza Street", "Shibuya Crossing", "Omotesando Avenue"], city: "Tokyo", country: "Japan", sortAs: "ASIA" },
        { zipCode: "11118", county: "Jordan", streets: ["Rainbow Street", "Abdullah Ghosheh Street", "Zahran Street"], city: "Amman", country: "Jordan", sortAs: "ASIA" },
        { zipCode: "050000", county: "Kazakhstan", streets: ["Abay Avenue", "Al-Farabi Avenue", "Dostyk Street"], city: "Almaty", country: "Kazakhstan", sortAs: "ASIA" },
        { zipCode: "13000", county: "Kuwait", streets: ["Gulf Road", "Al-Shuhada Street", "Soor Street"], city: "Kuwait City", country: "Kuwait", sortAs: "ASIA" },
        { zipCode: "720001", county: "Kyrgyzstan", streets: ["Chuy Avenue", "Manas Avenue", "Molodaya Gvardiya Boulevard"], city: "Bishkek", country: "Kyrgyzstan", sortAs: "ASIA" },
        { zipCode: "01000", county: "Laos", streets: ["Lane Xang Avenue", "Setthathirath Road", "Samsenthai Road"], city: "Vientiane", country: "Laos", sortAs: "ASIA" },
        { zipCode: "1107", county: "Lebanon", streets: ["Hamra Street", "Beirut Souks", "Mar Mikhael Street"], city: "Beirut", country: "Lebanon", sortAs: "ASIA" },
        { zipCode: "50088", county: "Malaysia", streets: ["Bukit Bintang", "Jalan Raja Laut", "Petaling Street"], city: "Kuala Lumpur", country: "Malaysia", sortAs: "ASIA" },
        { zipCode: "20002", county: "Maldives", streets: ["Fareedhee Magu", "Orchid Magu", "Majeedhee Magu"], city: "Malé", country: "Maldives", sortAs: "ASIA" },
        { zipCode: "976001", county: "Mongolia", streets: ["Peace Avenue", "Sukhbaatar Square", "Chinggis Avenue"], city: "Ulaanbaatar", country: "Mongolia", sortAs: "ASIA" },
        { zipCode: "11201", county: "Myanmar", streets: ["Shwe Bontha Street", "Anawrahta Road", "Kandawgyi Road"], city: "Yangon", country: "Myanmar", sortAs: "ASIA" },
        { zipCode: "44600", county: "Nepal", streets: ["Durbar Marg", "New Road", "Thamel"], city: "Kathmandu", country: "Nepal", sortAs: "ASIA" },
        { zipCode: "999700", county: "North Korea", streets: ["Kim Il-sung Square", "Ryomyong Street", "Tongil Street"], city: "Pyongyang", country: "North Korea", sortAs: "ASIA" },
        { zipCode: "113", county: "Oman", streets: ["Sultan Qaboos Street", "Ruwi Street", "Al Khuwair Street"], city: "Muscat", country: "Oman", sortAs: "ASIA" },
        { zipCode: "54000", county: "Pakistan", streets: ["Mall Road", "MM Alam Road", "Gulberg Main"], city: "Lahore", country: "Pakistan", sortAs: "ASIA" },
        { zipCode: "1001", county: "Philippines", streets: ["Roxas Boulevard", "Ayala Avenue", "Katipunan Avenue"], city: "Manila", country: "Philippines", sortAs: "ASIA" },
        { zipCode: "12345", county: "Qatar", streets: ["Corniche Street", "Salwa Road", "Al Waab Street"], city: "Doha", country: "Qatar", sortAs: "ASIA" },
        { zipCode: "101000", county: "Russia", streets: ["Arbat Street", "Tverskaya Street", "Nevsky Prospect"], city: "Moscow", country: "Russia", sortAs: "ASIA" },
        { zipCode: "11564", county: "Saudi Arabia", streets: ["King Fahd Road", "Tahlia Street", "Olaya Street"], city: "Riyadh", country: "Saudi Arabia", sortAs: "ASIA" },
        { zipCode: "639798", county: "Singapore", streets: ["Orchard Road", "Clarke Quay", "Marina Bay"], city: "Singapore", country: "Singapore", sortAs: "ASIA" },
        { zipCode: "04524", county: "South Korea", streets: ["Gangnam Boulevard", "Insadong Street", "Myeongdong"], city: "Seoul", country: "South Korea", sortAs: "ASIA" },
        { zipCode: "00200", county: "Sri Lanka", streets: ["Galle Road", "Bauddhaloka Mawatha", "Marine Drive"], city: "Colombo", country: "Sri Lanka", sortAs: "ASIA" },
        { zipCode: "8001", county: "Syria", streets: ["Abu Roumaneh", "Hamra Street", "Al Thawra Street"], city: "Damascus", country: "Syria", sortAs: "ASIA" },
        { zipCode: "734000", county: "Tajikistan", streets: ["Somoni Avenue", "Rudaki Avenue", "Hovaron Street"], city: "Dushanbe", country: "Tajikistan", sortAs: "ASIA" },
        { zipCode: "10110", county: "Thailand", streets: ["Sukhumvit Road", "Khao San Road", "Silom Road"], city: "Bangkok", country: "Thailand", sortAs: "ASIA" },
        { zipCode: "670-1", county: "Timor-Leste", streets: ["Rua de Direito", "Avenida Nicolau Lobato", "Rua Dom Boa Ventura"], city: "Dili", country: "Timor-Leste", sortAs: "ASIA" },
        { zipCode: "34000", county: "Asian Turkey", streets: ["Istiklal Avenue", "Bagdat Avenue", "Ataturk Boulevard"], city: "Istanbul", country: "Turkey", sortAs: "ASIA" },
        { zipCode: "744000", county: "Turkmenistan", streets: ["Galkynysh Avenue", "Archabil Avenue", "Magtymguly Avenue"], city: "Ashgabat", country: "Turkmenistan", sortAs: "ASIA" },
        { zipCode: "00001", county: "United Arab Emirates", streets: ["Sheikh Zayed Road", "Jumeirah Beach Road", "Al Khail Road"], city: "Dubai", country: "United Arab Emirates", sortAs: "ASIA" },
        { zipCode: "100100", county: "Uzbekistan", streets: ["Amir Timur Street", "Sharaf Rashidov Street", "Independence Square"], city: "Tashkent", country: "Uzbekistan", sortAs: "ASIA" },
        { zipCode: "700000", county: "Vietnam", streets: ["Nguyen Hue Street", "Pham Ngu Lao Street", "Le Duan Boulevard"], city: "Ho Chi Minh City", country: "Vietnam", sortAs: "ASIA" },
        { zipCode: "8911", county: "Yemen", streets: ["Al Zubayri Street", "Hadda Street", "Al Sabeen Street"], city: "Sanaa", country: "Yemen", sortAs: "ASIA" }
    ],

    "Level 10": [
        { zipCode: "16000", county: "Algeria", streets: ["Rue Didouche Mourad", "Boulevard Mohammed V", "Place des Martyrs"], city: "Algiers", country: "Algeria", sortAs: "AFRICA" },
        { zipCode: "2000", county: "Angola", streets: ["Rua Hoji Ya Henda", "Avenida Deolinda Rodrigues", "Rua Rainha Ginga"], city: "Luanda", country: "Angola", sortAs: "AFRICA" },
        { zipCode: "01BP123", county: "Benin", streets: ["Rue des Martyrs", "Avenue Steinmetz", "Boulevard de la Marina"], city: "Cotonou", country: "Benin", sortAs: "AFRICA" },
        { zipCode: "0000", county: "Botswana", streets: ["Nelson Mandela Drive", "Khama Crescent", "Independence Avenue"], city: "Gaborone", country: "Botswana", sortAs: "AFRICA" },
        { zipCode: "01BP456", county: "Burkina Faso", streets: ["Avenue Kwamé Nkrumah", "Rue de la Grande Mosquée", "Rue de l'Université"], city: "Ouagadougou", country: "Burkina Faso", sortAs: "AFRICA" },
        { zipCode: "BJM120", county: "Burundi", streets: ["Avenue de la Révolution", "Boulevard Patrice Lumumba", "Rue de l'Indépendance"], city: "Bujumbura", country: "Burundi", sortAs: "AFRICA" },
        { zipCode: "237001", county: "Cameroon", streets: ["Boulevard de l'Avenue Kennedy", "Rue Joseph Essono", "Avenue des Banques"], city: "Yaoundé", country: "Cameroon", sortAs: "AFRICA" },
        { zipCode: "7600", county: "Cape Verde", streets: ["Rua 5 de Julho", "Avenida Amílcar Cabral", "Rua Pedonal"], city: "Praia", country: "Cape Verde", sortAs: "AFRICA" },
        { zipCode: "236", county: "Central African Republic", streets: ["Avenue de l'Indépendance", "Boulevard des Martyrs", "Rue de l'Évêché"], city: "Bangui", country: "Central African Republic", sortAs: "AFRICA" },
        { zipCode: "NDJ1234", county: "Chad", streets: ["Avenue Charles de Gaulle", "Rue de la Liberté", "Rue de l'Assemblée"], city: "N'Djamena", country: "Chad", sortAs: "AFRICA" },
        { zipCode: "KM9900", county: "Comoros", streets: ["Rue de la Corniche", "Avenue de l'Aéroport", "Place de l'Indépendance"], city: "Moroni", country: "Comoros", sortAs: "AFRICA" },
        { zipCode: "243101", county: "Democratic Republic of the Congo", streets: ["Avenue des Forces Armées", "Boulevard du 30 Juin", "Rue Kalemie"], city: "Kinshasa", country: "Democratic Republic of the Congo", sortAs: "AFRICA" },
        { zipCode: "242001", county: "Republic of the Congo", streets: ["Avenue de l'Amitié", "Boulevard Denis Sassou Nguesso", "Rue Kouyou"], city: "Brazzaville", country: "Republic of the Congo", sortAs: "AFRICA" },
        { zipCode: "225", county: "Côte d'Ivoire", streets: ["Boulevard Valéry Giscard d'Estaing", "Rue du Commerce", "Avenue du Président Houphouët-Boigny"], city: "Abidjan", country: "Côte d'Ivoire", sortAs: "AFRICA" },
        { zipCode: "DJI123", county: "Djibouti", streets: ["Rue de Paris", "Boulevard de la République", "Rue de Venise"], city: "Djibouti", country: "Djibouti", sortAs: "AFRICA" },
        { zipCode: "11511", county: "Egypt", streets: ["Tahrir Square", "Sharia Al-Muizz", "Corniche El-Nil"], city: "Cairo", country: "Egypt", sortAs: "AFRICA" },
        { zipCode: "24000", county: "Equatorial Guinea", streets: ["Avenida Hassan II", "Calle de la Libertad", "Calle Mongomo"], city: "Malabo", country: "Equatorial Guinea", sortAs: "AFRICA" },
        { zipCode: "ERI001", county: "Eritrea", streets: ["Harnet Avenue", "Sematat Avenue", "Godena Harnet"], city: "Asmara", country: "Eritrea", sortAs: "AFRICA" },
        { zipCode: "H100", county: "Eswatini", streets: ["Allister Miller Street", "Mzilikazi Street", "Gwamile Street"], city: "Mbabane", country: "Eswatini", sortAs: "AFRICA" },
        { zipCode: "1000", county: "Ethiopia", streets: ["Churchill Avenue", "Bole Road", "Africa Avenue"], city: "Addis Ababa", country: "Ethiopia", sortAs: "AFRICA" },
        { zipCode: "24101", county: "Gabon", streets: ["Boulevard Triomphal", "Rue d’Omnisport", "Avenue Léon Mba"], city: "Libreville", country: "Gabon", sortAs: "AFRICA" },
        { zipCode: "2200", county: "Gambia", streets: ["Kairaba Avenue", "Jimpex Road", "Independence Drive"], city: "Banjul", country: "Gambia", sortAs: "AFRICA" },
        { zipCode: "233", county: "Ghana", streets: ["Oxford Street", "Kojo Thompson Road", "Independence Avenue"], city: "Accra", country: "Ghana", sortAs: "AFRICA" },
        { zipCode: "GN001", county: "Guinea", streets: ["Rue du Niger", "Avenue de la République", "Boulevard Telly Diallo"], city: "Conakry", country: "Guinea", sortAs: "AFRICA" },
        { zipCode: "GW101", county: "Guinea-Bissau", streets: ["Avenida Amílcar Cabral", "Rua de Bissau", "Praça dos Heróis Nacionais"], city: "Bissau", country: "Guinea-Bissau", sortAs: "AFRICA" },
        { zipCode: "KE00100", county: "Kenya", streets: ["Moi Avenue", "Kenyatta Avenue", "Haile Selassie Avenue"], city: "Nairobi", country: "Kenya", sortAs: "AFRICA" },
        { zipCode: "100", county: "Lesotho", streets: ["Kingsway Road", "Pioneer Road", "Moshoeshoe Road"], city: "Maseru", country: "Lesotho", sortAs: "AFRICA" },
        { zipCode: "LIB101", county: "Liberia", streets: ["Broad Street", "UN Drive", "Randall Street"], city: "Monrovia", country: "Liberia", sortAs: "AFRICA" },
        { zipCode: "LY901", county: "Libya", streets: ["First of September Street", "Gargaresh Road", "Tripoli Street"], city: "Tripoli", country: "Libya", sortAs: "AFRICA" },
        { zipCode: "MG101", county: "Madagascar", streets: ["Rue de l'Indépendance", "Avenue de l’Indépendance", "Rue Rakotozafy"], city: "Antananarivo", country: "Madagascar", sortAs: "AFRICA" },
        { zipCode: "2010", county: "Malawi", streets: ["Kamuzu Procession Road", "Independence Drive", "Chilambula Road"], city: "Lilongwe", country: "Malawi", sortAs: "AFRICA" },
        { zipCode: "BP124", county: "Mali", streets: ["Rue Baba Diarra", "Avenue de l’Indépendance", "Rue Mohamed V"], city: "Bamako", country: "Mali", sortAs: "AFRICA" },
        { zipCode: "001", county: "Mauritania", streets: ["Avenue Abdel Nasser", "Boulevard de la Résistance", "Rue de l'Hôpital"], city: "Nouakchott", country: "Mauritania", sortAs: "AFRICA" },
        { zipCode: "MU001", county: "Mauritius", streets: ["Sir William Newton Street", "Royal Road", "Queen Street"], city: "Port Louis", country: "Mauritius", sortAs: "AFRICA" },
        { zipCode: "20000", county: "Morocco", streets: ["Avenue Hassan II", "Boulevard Mohammed V", "Rue de Paris"], city: "Casablanca", country: "Morocco", sortAs: "AFRICA" },
        { zipCode: "MAP101", county: "Mozambique", streets: ["Avenida Julius Nyerere", "Avenida Eduardo Mondlane", "Avenida Samora Machel"], city: "Maputo", country: "Mozambique", sortAs: "AFRICA" },
        { zipCode: "WIND100", county: "Namibia", streets: ["Independence Avenue", "Robert Mugabe Avenue", "Sam Nujoma Drive"], city: "Windhoek", country: "Namibia", sortAs: "AFRICA" },
        { zipCode: "NE101", county: "Niger", streets: ["Boulevard de l'Indépendance", "Avenue du Président Kennedy", "Rue de l’Hôpital"], city: "Niamey", country: "Niger", sortAs: "AFRICA" },
        { zipCode: "234001", county: "Nigeria", streets: ["Broad Street", "Awolowo Road", "Ahmadu Bello Way"], city: "Lagos", country: "Nigeria", sortAs: "AFRICA" },
        { zipCode: "RW250", county: "Rwanda", streets: ["Avenue de l'Indépendance", "KG 7 Avenue", "KN 5 Road"], city: "Kigali", country: "Rwanda", sortAs: "AFRICA" },
        { zipCode: "STP001", county: "São Tomé and Príncipe", streets: ["Avenida Marginal 12 de Julho", "Rua de Santo António", "Praça da Independência"], city: "São Tomé", country: "São Tomé and Príncipe", sortAs: "AFRICA" },
        { zipCode: "SN123", county: "Senegal", streets: ["Rue Moussé Diop", "Boulevard du Général de Gaulle", "Avenue Blaise Diagne"], city: "Dakar", country: "Senegal", sortAs: "AFRICA" },
        { zipCode: "SC001", county: "Seychelles", streets: ["Independence Avenue", "Francis Rachel Street", "Revolution Avenue"], city: "Victoria", country: "Seychelles", sortAs: "AFRICA" },
        { zipCode: "SL102", county: "Sierra Leone", streets: ["Lumley Beach Road", "Wilkinson Road", "Fourah Bay Road"], city: "Freetown", country: "Sierra Leone", sortAs: "AFRICA" },
        { zipCode: "SOM001", county: "Somalia", streets: ["Wadada Wadnaha", "Hamar Weyne Street", "Shabelle Street"], city: "Mogadishu", country: "Somalia", sortAs: "AFRICA" },
        { zipCode: "ZA101", county: "South Africa", streets: ["Nelson Mandela Square", "Long Street", "Vilakazi Street"], city: "Johannesburg", country: "South Africa", sortAs: "AFRICA" },
        { zipCode: "JUB01", county: "South Sudan", streets: ["Juba Town Road", "Nimule Street", "Unity Avenue"], city: "Juba", country: "South Sudan", sortAs: "AFRICA" },
        { zipCode: "KHRT01", county: "Sudan", streets: ["Nile Street", "Airport Road", "Sharia Al-Souk"], city: "Khartoum", country: "Sudan", sortAs: "AFRICA" },
        { zipCode: "TZ255", county: "Tanzania", streets: ["Samora Avenue", "Lumumba Street", "Ali Hassan Mwinyi Road"], city: "Dar es Salaam", country: "Tanzania", sortAs: "AFRICA" },
        { zipCode: "TG456", county: "Togo", streets: ["Rue du Commerce", "Boulevard de la Paix", "Rue de la Bourse"], city: "Lomé", country: "Togo", sortAs: "AFRICA" },
        { zipCode: "1001", county: "Tunisia", streets: ["Avenue Habib Bourguiba", "Rue de Marseille", "Avenue de France"], city: "Tunis", country: "Tunisia", sortAs: "AFRICA" },
        { zipCode: "UG256", county: "Uganda", streets: ["Kampala Road", "Jinja Road", "Bombo Road"], city: "Kampala", country: "Uganda", sortAs: "AFRICA" },
        { zipCode: "2601", county: "Zambia", streets: ["Cairo Road", "Great East Road", "Lumumba Road"], city: "Lusaka", country: "Zambia", sortAs: "AFRICA" },
        { zipCode: "ZW02", county: "Zimbabwe", streets: ["Robert Mugabe Road", "Samora Machel Avenue", "Julius Nyerere Way"], city: "Harare", country: "Zimbabwe", sortAs: "AFRICA" }
    ],
    "Level 11": [
        { zipCode: "10400", county: "Cuba", streets: ["Calle 23", "Calle Obispo", "Malecón"], city: "Havana", country: "Cuba", sortAs: "CRBN" },
        { zipCode: "HT6120", county: "Haiti", streets: ["Rue du Magasin de l'État", "Boulevard Toussaint Louverture", "Rue Capois"], city: "Port-au-Prince", country: "Haiti", sortAs: "CRBN" },
        { zipCode: "11501", county: "Dominican Republic", streets: ["El Conde Street", "Churchill Avenue", "Las Damas Street"], city: "Santo Domingo", country: "Dominican Republic", sortAs: "CRBN" },
        { zipCode: "JMACE17", county: "Jamaica", streets: ["Half Way Tree Road", "Knutsford Boulevard", "Marcus Garvey Drive"], city: "Kingston", country: "Jamaica", sortAs: "CRBN" },
        { zipCode: "00901", county: "Puerto Rico", streets: ["Calle Fortaleza", "Ashford Avenue", "Calle San Sebastián"], city: "San Juan", country: "Puerto Rico", sortAs: "CRBN" },
        { zipCode: "N-3919", county: "Bahamas", streets: ["Bay Street", "Cable Beach Road", "Market Street"], city: "Nassau", country: "Bahamas", sortAs: "CRBN" },
        { zipCode: "BB11114", county: "Barbados", streets: ["Broad Street", "High Street", "Bay Street"], city: "Bridgetown", country: "Barbados", sortAs: "CRBN" },
        { zipCode: "TT150602", county: "Trinidad and Tobago", streets: ["Frederick Street", "Ariapita Avenue", "Independence Square"], city: "Port of Spain", country: "Trinidad and Tobago", sortAs: "CRBN" },
        { zipCode: "GD12345", county: "Grenada", streets: ["Melville Street", "Carenage Road", "Lagoon Road"], city: "St. George's", country: "Grenada", sortAs: "CRBN" },
        { zipCode: "VC0102", county: "Saint Vincent and the Grenadines", streets: ["Bay Street", "Grenville Street", "Middle Street"], city: "Kingstown", country: "Saint Vincent and the Grenadines", sortAs: "CRBN" },
        { zipCode: "LC04 301", county: "Saint Lucia", streets: ["Bridge Street", "Bourbon Street", "Chisel Street"], city: "Castries", country: "Saint Lucia", sortAs: "CRBN" },
        { zipCode: "KN0101", county: "Saint Kitts and Nevis", streets: ["Fort Street", "Cayon Street", "Bay Road"], city: "Basseterre", country: "Saint Kitts and Nevis", sortAs: "CRBN" },
        { zipCode: "A1-200", county: "Antigua and Barbuda", streets: ["Market Street", "High Street", "Long Street"], city: "St. John's", country: "Antigua and Barbuda", sortAs: "CRBN" },
        { zipCode: "DM003", county: "Dominica", streets: ["King George V Street", "Hillsborough Street", "Bay Front"], city: "Roseau", country: "Dominica", sortAs: "CRBN" }
    ],
    "Level 12": [
        { zipCode: "10101", county: "Costa Rica", streets: ["Avenida Central", "Calle 5", "Paseo Colón"], city: "San José", country: "Costa Rica", sortAs: "C-AM" },
        { zipCode: "01010", county: "Guatemala", streets: ["Avenida La Reforma", "Calle 6", "Calle 18"], city: "Guatemala City", country: "Guatemala", sortAs: "C-AM" },
        { zipCode: "11101", county: "Honduras", streets: ["Boulevard Morazan", "Calle 10", "Avenida La Paz"], city: "Tegucigalpa", country: "Honduras", sortAs: "C-AM" },
        { zipCode: "20001", county: "Nicaragua", streets: ["Calle 1", "Avenida Bolívar", "Calle El Carmen"], city: "Managua", country: "Nicaragua", sortAs: "C-AM" },
        { zipCode: "0801", county: "Panama", streets: ["Calle 50", "Avenida Balboa", "Calle 5 de Mayo"], city: "Panama City", country: "Panama", sortAs: "C-AM" },
        { zipCode: "BELZ01", county: "Belize", streets: ["Albert Street", "Princess Margaret Drive", "Earl's Court"], city: "Belmopan", country: "Belize", sortAs: "C-AM" },
        { zipCode: "1000", county: "El Salvador", streets: ["Calle Arce", "Boulevard Los Héroes", "Avenida Las Delicias"], city: "San Salvador", country: "El Salvador", sortAs: "C-AM" }
    ],
    "Level 13": [
        { zipCode: "2000", county: "New South Wales", streets: ["Oxford Street", "Bondi Beach", "Circular Quay"], city: "Sydney", country: "Australia", sortAs: "OCN" },
        { zipCode: "3000", county: "Victoria", streets: ["Flinders Street", "Federation Square", "Queen Victoria Market"], city: "Melbourne", country: "Australia", sortAs: "OCN" },
        { zipCode: "4000", county: "Queensland", streets: ["Brisbane River", "South Bank", "Queen Street Mall"], city: "Brisbane", country: "Australia", sortAs: "OCN" },
        { zipCode: "5000", county: "South Australia", streets: ["North Terrace", "Rundle Mall", "Glenelg Beach"], city: "Adelaide", country: "Australia", sortAs: "OCN" },
        { zipCode: "6000", county: "Western Australia", streets: ["Kings Park", "Elizabeth Quay", "Hay Street"], city: "Perth", country: "Australia", sortAs: "OCN" },
        { zipCode: "7000", county: "Tasmania", streets: ["Sullivan's Cove", "Salamanca Place", "Hobart Waterfront"], city: "Hobart", country: "Australia", sortAs: "OCN" },
        { zipCode: "2600", county: "Australian Capital Territory", streets: ["Parliament House", "Lake Burley Griffin", "Canberra Centre"], city: "Canberra", country: "Australia", sortAs: "OCN" },
        { zipCode: "3004", county: "Victoria", streets: ["South Melbourne Market", "Albert Park", "St. Kilda Beach"], city: "Melbourne", country: "Australia", sortAs: "OCN" },
        { zipCode: "96850", county: "Hawaii", streets: ["Waikiki Beach", "Diamond Head", "Ala Moana"], city: "Honolulu", country: "USA", sortAs: "OCN" },
        { zipCode: "7000", county: "Fiji", streets: ["Suva Street", "Albert Park", "Saraswati College"], city: "Suva", country: "Fiji", sortAs: "OCN" },
        { zipCode: "680", county: "Kiribati", streets: ["Tarawa", "Bairiki", "Betio", "Anewa"], city: "Tarawa", country: "Kiribati", sortAs: "OCN" },
        { zipCode: "96960", county: "Marshall Islands", streets: ["Delap", "Majuro", "Ebeye"], city: "Majuro", country: "Marshall Islands", sortAs: "OCN" },
        { zipCode: "96941", county: "Micronesia", streets: ["Pohnpei", "Kolonia", "Sokehs", "Nett"], city: "Kolonia", country: "Micronesia", sortAs: "OCN" },
        { zipCode: "03000", county: "Nauru", streets: ["Boe", "Yaren", "Aiwo"], city: "Yaren", country: "Nauru", sortAs: "OCN" },
        { zipCode: "0001", county: "New Zealand", streets: ["Queen Street", "Auckland Domain", "Sky Tower"], city: "Auckland", country: "New Zealand", sortAs: "OCN" },
        { zipCode: "6011", county: "Wellington", streets: ["Cuba Street", "Mount Victoria", "Wellington Waterfront"], city: "Wellington", country: "New Zealand", sortAs: "OCN" },
        { zipCode: "7010", county: "Tasman", streets: ["Nelson Harbour", "Tahunanui Beach", "Richmond Park"], city: "Nelson", country: "New Zealand", sortAs: "OCN" },
        { zipCode: "96940", county: "Palau", streets: ["Koror", "Melekeok", "Ngerulmud"], city: "Koror", country: "Palau", sortAs: "OCN" },
        { zipCode: "1000", county: "Papua New Guinea", streets: ["Port Moresby", "Moresby Arts Theatre", "Konedobu"], city: "Port Moresby", country: "Papua New Guinea", sortAs: "OCN" },
        { zipCode: "0002", county: "Samoa", streets: ["Apia", "Mulinu'u", "Vailima"], city: "Apia", country: "Samoa", sortAs: "OCN" },
        { zipCode: "880", county: "Solomon Islands", streets: ["Honiara", "Chinatown", "Point Cruz"], city: "Honiara", country: "Solomon Islands", sortAs: "OCN" },
        { zipCode: "950", county: "Tonga", streets: ["Nuku'alofa", "Talafo'ou", "Kolomotu'a"], city: "Nuku'alofa", country: "Tonga", sortAs: "OCN" },
        { zipCode: "9999", county: "Tuvalu", streets: ["Funafuti", "Vaiaku", "Nanumea"], city: "Funafuti", country: "Tuvalu", sortAs: "OCN" },
        { zipCode: "0000", county: "Vanuatu", streets: ["Port Vila", "Erakor Lagoon", "Mele Bay"], city: "Port Vila", country: "Vanuatu", sortAs: "OCN" }
    ],
    "Level 14": [
        { sortAs: "BIN" }
    ]
};



export const firstNames = [
    "Adam", "Albin", "Alfred", "Alma", "Alvar", "Alve", "Amir", "Anna", "Anton", "Aron", "Astrid",
    "August", "Axel", "Benjamin", "Bill", "Björn", "Charlie", "Christina", "Casper", "Dante", "Ebba",
    "Ebbi", "Eduard", "Elias", "Elina", "Ellie", "Emma", "Emil", "Erik", "Eva", "Filip", "Folke", "Frans",
    "Gabriel", "Gustav", "Hanna", "Harry", "Henry", "Hjalmar", "Hugo", "Ivar", "Jack", "Jan", "Johan", "Joel",
    "Julian", "Karin", "Karl", "Kerstin", "Kian", "Knut", "Lars", "Levi", "Liam", "Lena", "Leo", "Leon", "Lili",
    "Lina", "Linnéa", "Lisa", "Liva", "Loke", "Love", "Lucas", "Ludvig", "Lukas", "Luna", "Madeleine", "Malte",
    "Maria", "Marie", "Matheo", "Max", "Melker", "Melvin", "Mikael", "Milan", "Milo", "Milton", "Nils", "Noel",
    "Omar", "Oliver", "Olle", "Otis", "Otto", "Oskar", "Per", "Peter", "Philip", "Sam", "Sara", "Sigge", "Sixten",
    "Sophia", "Theo", "Thomas", "Valter", "Vera", "Viggo", "Vincent", "William", "Wilhelm", "Walter", "Xavier",
    "Ylva", "Åke", "Ava", "Liam", "Zara", "Ibrahim", "Hiroshi", "Fatima", "Carlos", "Mohammed", "Priya", "Luca",
    "Elena", "Maya", "Amira", "Sebastian", "Lucas", "Leo", "Kai", "Ximena", "Youssef", "Ayaan", "Kofi", "Jade",
    "Xander", "Nia", "Thalia", "Noah", "Keisha", "Santiago", "Leila", "Evelyn", "Tariq", "Sanaa", "Soraya",
    "Matteo", "Jin", "Tenzin", "Jun", "Ravi", "Gita", "Chinonso", "Oluwaseun", "Dinesh", "Rhea", "Javier",
    "Zane", "Tariq", "Hassan", "Arvind", "Ramon", "Tomas", "Lina", "Juan", "Alicia", "Carmen", "Lucia", "Zara",
    "Mariam", "Khalid", "Asma", "Sami", "Hassan", "Yara", "Chloe", "Noelle", "Anjali", "Indira", "Ayesha", "Anwar",
    "Rashid", "Zubair", "Matilda", "Sven", "Isha", "Benedicta", "Chetan", "Kwame", "Musa", "Kwabena", "Felix",
    "Zahra", "Isabella", "Nadia", "Eloise", "Oscar", "Eva", "Jasmin", "Diana", "Karim", "Zoya", "Nina", "Hadiya",
    "Lorenzo", "Esme", "Leandro", "Aurelia", "Boris", "Omar", "Mira", "Raj", "Yasmin", "Diana", "Gustavo", "Tunde",
    "Lola", "Dimitri", "Ksenia", "Sasha", "Nikolai", "Svetlana", "Darya", "Rostislav", "Karolina", "Zbigniew",
    "Andrei", "Elena", "Milena", "Zofia", "Lucian", "Bogdan", "Aditya", "Disha", "Pooja", "Lalita", "Swati", "Manoj",
    "Alejandro", "Leonardo", "Marcelo", "Francisco", "Andres", "Violet", "Fernanda", "Luz", "Joaquin", "Victoria",
    "Marta", "Carla", "Lucas", "Giulia", "Matilde", "Luisa", "Mia", "Sofia", "Gabriela", "Camila", "Isadora", "Anya",
    "Sofia", "Giovanni", "Zoe", "Camila", "Anastasia", "Rania", "Katerina", "Elif", "Leyla", "Mira", "Nina"
];

export const lastNames = [
    "Abrahamsson", "Ahmed", "Ali", "Andreasson", "Arvidsson", "Axelsson", "Bengtsson", "Berger", "Berggren",
    "Bergkvist", "Bergman", "Bergström", "Blom", "Blomberg", "Blomkvist", "Blomquist", "Blomqvist", "Björk",
    "Björklund", "Björnsson", "Claesson", "Danielsson", "Dahlberg", "Ek", "Ekberg", "Ekblad", "Ekholm", "Ekström",
    "Eliasson", "Engström", "Eriksson", "Eklund", "Fallberg", "Fredriksson", "Fransson", "Frantzén", "Frisk",
    "Gunnarsson", "Gustafsson", "Gyllenhaal", "Hallberg", "Hansson", "Hedberg", "Hellström", "Henriksson",
    "Hermansson", "Holberg", "Holmgren", "Holmqvist", "Hultén", "Hägg", "Hällström", "Jakobsson", "Jansson",
    "Johansson", "Jonsson", "Jönsson", "Karlsson", "Klintberg", "Klingberg", "Klintström", "Knutsson", "Krüger",
    "Kullberg", "Kullén", "Kurck", "Larsson", "Lindberg", "Lindblad", "Lindell", "Lindgren", "Lindholm", "Lindkvist",
    "Lindner", "Lindroos", "Lindström", "Lindqvist", "Lindsten", "Lindwall", "Ljungberg", "Ljunggren", "Löfgren",
    "Lundberg", "Lundgren", "Lundkvist", "Lundmark", "Lundström", "Magnusson", "Mattsson", "Malmberg", "Malmgren",
    "Malmqvist", "Malmström", "Månsson", "Martinsson", "Melin", "Mellberg", "Mellgren", "Mellqvist", "Mellström",
    "Mohamed", "Molin", "Moller", "Mörner", "Mörtberg", "Mörtén", "Mörtstedt", "Norberg", "Nordin", "Nyberg",
    "Nyström", "Olsson", "Olofsson", "Persson", "Pettersson", "Pålsson", "Sandberg", "Sandström", "Sjögren",
    "Sjöberg", "Ström", "Strömberg", "Sundberg", "Sundström", "Söderberg", "Tage", "Viklund", "Wallin", "Åberg",
    "Åkesson", "Åström", "Nguyen", "Tanaka", "Li", "Wang", "Chavez", "Ramirez", "Gomez", "Hernandez", "Lopez",
    "Martinez", "Perez", "Garcia", "Rodriguez", "Kim", "Park", "Choi", "Lee", "Jang", "Song", "Kang", "Yang",
    "Kumar", "Patel", "Sharma", "Singh", "Mehta", "Gupta", "Reddy", "Naidu", "Ibrahim", "Abdullah", "Aliyu",
    "Mohammed", "Bello", "Aminu", "Zhang", "Xu", "Chen", "Liu", "Mao", "Zhao", "Wang", "Tan", "Ng", "Tan", "Khoo",
    "Fong", "Jansen", "De Vries", "Van den Berg", "De Jong", "Smit", "Bakker", "Hofman", "Visser", "Van Dijk",
    "Schmidt", "Müller", "Schneider", "Weber", "Fischer", "Becker", "Wagner", "Hoffmann", "Klein", "Zimmermann",
    "Schulz", "Bauer", "Weiss", "Meier", "Böhm", "Krause", "Steiner", "Schwarz", "Hartmann", "Bauer", "Hansen",
    "Johansen", "Olsen", "Eriksen", "Nilsen", "Andersen", "Larsen", "Jensen", "Pedersen", "Kristensen", "Wang",
    "Tso", "Lau", "Wu", "Yip", "Cheng", "Shen", "Tanaka", "Abe", "Takeda", "Nakamura", "Yamamoto", "Matsumoto",
    "Inoue", "Fujimoto", "Kobayashi", "Yoshida", "Chung", "Yip", "Hong", "Huang", "Nguyen", "Tran", "Pham", "Luu",
    "Fong", "Yeo", "Liu", "Lin", "Sullivan", "Kelly", "O'Connor", "Murphy", "Smith", "Davis", "Miller", "Wilson",
    "Taylor", "Moore", "Clark", "Johnson", "Lewis", "Scott", "Roberts", "Walker", "Young", "Allen", "Harris",
    "Baker", "Gonzalez", "Ramirez", "Adams", "Nelson", "Hill", "Carter", "Mitchell", "Perez", "Green", "Phillips",
    "King", "Campbell", "Davis", "Evans", "Turner", "Thomas", "Bashir", "Aliyev", "Khan", "Khoury", "Sanchez"
];

