export const messages = {

    labels: {
        name: "Name",
        street: "Street",
        zipCode: "Zip Code",
        county: "County",
        location: "Location"
    },
    headerTitle: "PIGEONHOLED",
    startGame: "Level 1",
    levelUp: "Level ",

    level1Dialog: "Welcome to the post office! 🎉 Sort the letters by the last two digits of the zipcode. Place the letter in the box that matches those digits. 📮 More instructions will follow soon!",
    level2Dialog: "Great job on Stockholm! 🎉 Now, you'll also need to sort letters for other cities in Sweden 🇸🇪. Look at the city name on the letter. If it's not Stockholm, sort it into the 'SE' box! 📨",
    level3Dialog: "We're adding the other Nordic countries now 🏔️. Sort Denmark, Norway, Finland, Iceland into the NORD box! 🌍",
    level4Dialog: "Let's get global! 🌐 Sort letters from other European countries into the EUR box. 🇪🇺",
    level5Dialog: "Time to get fancy! 🇬🇧 Sort all letters from the British Isles (UK & Ireland) into the UK-I box. God save the postman! 📬",
    level6Dialog: "Cross the pond! 🌎 Put all North American letters (USA, Canada, Mexico) into the N-AM box. 🍁",
    level7Dialog: "South America is calling! 🌞 Sort cities from Brazil, Argentina, Chile etc. into the S-AM box. Don't forget your sunblock! 🏖️",
    level8Dialog: "Asia awaits! 🏙️ Remember that some countries belong to multiple continents and pay attention to the letter details. 🏯",
    level9Dialog: "Next stop: Africa! 🦁 Sort letters from African cities into the AFR box. You've got this - from Cairo to Cape Town! 🌍",
    level10Dialog: "Central America time! 🌴 Sort cities from Guatemala, Costa Rica, Panama etc. into the C-AM box. Things are getting hard now so here's an extra life! 🌞",
    level11Dialog: "The Caribbean is calling! 🏖️ Sort cities from Jamaica, Cuba, Bahamas, and more into the CRBN box. Here's another extra life for you! 🌴",
    level12Dialog: "Oceania is next! 🏄‍♂️ Sort cities from Australia, New Zealand, and all the Polynesian islands into the OCN box. Time to ride the waves! And have another life on us 🌊",
    lastLevelDialog: "Pay attention! If a letter is missing any details, it goes in the BIN box. This is the final level so take one last life and let's see how long you'll last! 🚮",

    correctMessage: "Correct!",
    incorrectMessage: "Incorrect.",
    incorrectAnswerMessage: "The correct box was {correctAnswer}.",
    firedOutOfTimeMessage: "YOU'RE FIRED! Too slow!",
    firedMistakesMessage: "YOU'RE FIRED! You made too many mistakes!",

    livesMessage: "Lives: {lives}",
    cashMessage: "Cash: ${cash}",
    timerMessage: "Time remaining: {time} seconds",
};

export const addresses = {
    "Level 1": [
        { zipCode: "182 20", county: "Danderyd", streets: ["Danderyds Torg", "Bergsängsvägen", "Högberga Allé"], city: "Stockholm", country: "Sweden", sortAs: "20" },
        { zipCode: "143 23", county: "Vårby", streets: ["Vårby Gårdsvägen", "Vårby Allé", "Bäckvägen"], city: "Stockholm", country: "Sweden", sortAs: "23" },
        { zipCode: "197 27", county: "Ekerö", streets: ["Ekerö Centrum", "Strandvägen", "Ekerö Torg"], city: "Stockholm", country: "Sweden", sortAs: "27" },
        { zipCode: "198 28", county: "Järfälla", streets: ["Järfälla Centrum", "Järfällagatan", "Rissne"], city: "Stockholm", country: "Sweden", sortAs: "28" },
        { zipCode: "149 20", county: "Nynashamn", streets: ["Nynäs Gårdsväg", "Nynäsbaden", "Nynäsgatan"], city: "Stockholm", country: "Sweden", sortAs: "20" },
        { zipCode: "143 31", county: "Vårby", streets: ["Vårby Allé", "Vårbergsplan", "Vårby Gårdsväg"], city: "Stockholm", country: "Sweden", sortAs: "31" },
        { zipCode: "137 32", county: "Västerhaninge", streets: ["Älgvägen", "Vargvägen", "Rådjursvägen"], city: "Stockholm", country: "Sweden", sortAs: "32" },
        { zipCode: "137 32", county: "Västerhaninge", streets: ["Kvartärvägen", "Björnvägen", "Åbylundsvägen"], city: "Stockholm", country: "Sweden", sortAs: "32" },
        { zipCode: "129 33", county: "Hägersten", streets: ["Boktryckarvägen", "Bäckvägen", "Bokbindarvägen"], city: "Stockholm", country: "Sweden", sortAs: "33" },
        { zipCode: "129 33", county: "Hägersten", streets: ["Arvodesvägen", "Stiltgjutarvägen", "Kontovägen"], city: "Stockholm", country: "Sweden", sortAs: "33" },
        { zipCode: "129 37", county: "Hägersten", streets: ["Selmedalsvägen", "Hägerstens allé", "Hägerstensbrinken"], city: "Stockholm", country: "Sweden", sortAs: "37" },
        { zipCode: "117 44", county: "Liljeholmen", streets: ["Liljeholmsvägen", "Västerbroplan", "Hälsingegatan"], city: "Stockholm", country: "Sweden", sortAs: "44" },
        { zipCode: "128 51", county: "Högdalen", streets: ["Högdalsvägen", "Högdalstorget", "Högdalsparken"], city: "Stockholm", country: "Sweden", sortAs: "51" },
        { zipCode: "126 58", county: "Västertorp", streets: ["Västertorpsvägen", "Borgarskolan", "Västertorpstorg"], city: "Stockholm", country: "Sweden", sortAs: "58" },
        { zipCode: "126 60", county: "Hägersten", streets: ["Hägersjövägen", "Hägersjöplan", "Lillholmstorget"], city: "Stockholm", country: "Sweden", sortAs: "60" },
        { zipCode: "123 61", county: "Farsta", streets: ["Farstatorget", "Farstavägen", "Farstabergsplan"], city: "Stockholm", country: "Sweden", sortAs: "61" },
        { zipCode: "145 70", county: "Norsborg", streets: ["Iduns väg", "Höders väg", "Heimdals väg"], city: "Stockholm", country: "Sweden", sortAs: "70" },
        { zipCode: "145 71", county: "Norsborg", streets: ["Balders väg", "Odens väg", "Tors väg"], city: "Stockholm", country: "Sweden", sortAs: "71" },
        { zipCode: "145 76", county: "Norsborg", streets: ["Hundhamravägen", "Källåkersvägen", "Tomtbergavägen"], city: "Stockholm", country: "Sweden", sortAs: "76" },
    ],

    "Level 2": [
        { zipCode: "753 10", county: "Fålhagen", streets: ["Stora Torget", "Dragarbrunnsgatan", "Sankt Olofsgatan"], city: "Uppsala", country: "Sweden", sortAs: "SE" },
        { zipCode: "411 04", county: "Haga", streets: ["Avenyn", "Lilla Torget", "Magasinsgatan"], city: "Göteborg", country: "Sweden", sortAs: "SE" },
        { zipCode: "211 45", county: "Södervärn", streets: ["Södra Förstadsgatan", "Pildammsparken", "Linnégatan"], city: "Malmö", country: "Sweden", sortAs: "SE" },
        { zipCode: "222 21", county: "Mårtenstorget", streets: ["Stora Torget", "Kyrkogatan", "Bankgatan"], city: "Lund", country: "Sweden", sortAs: "SE" },
        { zipCode: "722 13", county: "Öster Mälarstrand", streets: ["Stora Gatan", "Sundbyvägen", "Fristadstorget"], city: "Västerås", country: "Sweden", sortAs: "SE" },
        { zipCode: "902 40", county: "Västra Ersboda", streets: ["Rådhusesplanaden", "Västerbottensvägen", "Storgatan"], city: "Umeå", country: "Sweden", sortAs: "SE" },
        { zipCode: "371 33", county: "Trossö", streets: ["Fiskaregatan", "Trossövägen", "Ronnebygatan"], city: "Karlskrona", country: "Sweden", sortAs: "SE" },
        { zipCode: "421 32", county: "Kungsbacka Centrum", streets: ["Storgatan", "Brogatan", "Södra Vägen"], city: "Kungsbacka", country: "Sweden", sortAs: "SE" },
        { zipCode: "831 33", county: "Storsjö", streets: ["Prästgatan", "Kyrkgatan", "Storgatan"], city: "Östersund", country: "Sweden", sortAs: "SE" },
        { zipCode: "611 31", county: "Arnö", streets: ["Västra Storgatan", "Nyköpingsvägen", "Stora Torget"], city: "Nyköping", country: "Sweden", sortAs: "SE" },
        { zipCode: "652 25", county: "Viken", streets: ["Östra Torggatan", "Stora Nygatan", "Hagaborgsgatan"], city: "Karlstad", country: "Sweden", sortAs: "SE" },
        { zipCode: "802 50", county: "Sätra", streets: ["Staketgatan", "Nygatan", "Södra Kungsgatan"], city: "Gävle", country: "Sweden", sortAs: "SE" },
        { zipCode: "252 25", county: "Sundstorget", streets: ["Järnvägsgatan", "Drottninggatan", "Södra Storgatan"], city: "Helsingborg", country: "Sweden", sortAs: "SE" },
        { zipCode: "504 47", county: "Byttorp", streets: ["Alingsåsvägen", "Västerbrogatan", "Brogatan"], city: "Borås", country: "Sweden", sortAs: "SE" },
        { zipCode: "211 43", county: "Västra Hamnen", streets: ["Östra Varvsgatan", "Masttorget", "Lilla Varvsgatan"], city: "Malmö", country: "Sweden", sortAs: "SE" },
        { zipCode: "702 23", county: "Haga", streets: ["Kungsgatan", "Stortorget", "Södra Grev Rosengatan"], city: "Örebro", country: "Sweden", sortAs: "SE" },
        { zipCode: "972 32", county: "Innerstaden", streets: ["Storgatan", "Skeppsbrogatan", "Stationsgatan"], city: "Luleå", country: "Sweden", sortAs: "SE" },
        { zipCode: "581 83", county: "Valla", streets: ["Liedbergsgatan", "Tornhagsvägen", "Trädgårdsgatan"], city: "Linköping", country: "Sweden", sortAs: "SE" },
        { zipCode: "441 30", county: "Södra Torget", streets: ["Västerlånggatan", "Borgmästaregatan", "Storgatan"], city: "Alingsås", country: "Sweden", sortAs: "SE" }
    ],

    "Level 3": [
        { zipCode: "0100", county: "Oslo County", streets: ["Karl Johans Gate", "Akershus Festning", "Stortinget"], city: "Oslo", country: "Norway", sortAs: "NORD" },
        { zipCode: "5001", county: "Hordaland", streets: ["Bryggen", "Fløibanen", "Torgallmenningen"], city: "Bergen", country: "Norway", sortAs: "NORD" },
        { zipCode: "4002", county: "Rogaland", streets: ["Vikingveien", "Sandnesgaten", "Torpveien"], city: "Stavanger", country: "Norway", sortAs: "NORD" },
        { zipCode: "7010", county: "Trøndelag", streets: ["Bakklandet", "St. Olavs Gate", "Torget"], city: "Trondheim", country: "Norway", sortAs: "NORD" },
        { zipCode: "9012", county: "Troms og Finnmark", streets: ["Storgata", "Hurtigrutekaia", "Sjøgata"], city: "Tromsø", country: "Norway", sortAs: "NORD" },
        { zipCode: "8005", county: "Nordland", streets: ["Storgata", "Rønvikveien", "Nyholmen"], city: "Bodø", country: "Norway", sortAs: "NORD" },
        { zipCode: "3021", county: "Viken", streets: ["Bragernes Torg", "Storgata", "Strømsø"], city: "Drammen", country: "Norway", sortAs: "NORD" },
        { zipCode: "2004", county: "Viken", streets: ["Storgata", "Akershusveien", "Gågata"], city: "Lillestrøm", country: "Norway", sortAs: "NORD" },
        { zipCode: "1705", county: "Østfold", streets: ["Kirkegata", "Vesterøyveien", "Hafslundveien"], city: "Sarpsborg", country: "Norway", sortAs: "NORD" },
        { zipCode: "1604", county: "Østfold", streets: ["Brogata", "Storgata", "Folkets Hus"], city: "Fredrikstad", country: "Norway", sortAs: "NORD" },
        { zipCode: "5528", county: "Rogaland", streets: ["Kirkegata", "Vågen", "Torggata"], city: "Haugesund", country: "Norway", sortAs: "NORD" },
        { zipCode: "1001", county: "Hovedstaden", streets: ["Nyhavn", "Strøget", "Vesterbrogade"], city: "Copenhagen", country: "Denmark", sortAs: "NORD" },
        { zipCode: "8000", county: "Midtjylland", streets: ["Aarhus Ø", "Strandvejen", "Søndergade"], city: "Aarhus", country: "Denmark", sortAs: "NORD" },
        { zipCode: "5000", county: "Syddanmark", streets: ["Kongensgade", "Havnegade", "Vesterbro"], city: "Odense", country: "Denmark", sortAs: "NORD" },
        { zipCode: "9000", county: "Nordjylland", streets: ["Sankt Marie Gade", "Bollerslev", "Jens Bangs Stenhus"], city: "Aalborg", country: "Denmark", sortAs: "NORD" },
        { zipCode: "6700", county: "Syddanmark", streets: ["Kongensgade", "Skolegade", "Grønningen"], city: "Esbjerg", country: "Denmark", sortAs: "NORD" },
        { zipCode: "6000", county: "Syddanmark", streets: ["Helligkorsgade", "Vesterbrogade", "Slotssøvejen"], city: "Kolding", country: "Denmark", sortAs: "NORD" },
        { zipCode: "7000", county: "Syddanmark", streets: ["Vestre Ringvej", "Søndergade", "Jernbanegade"], city: "Fredericia", country: "Denmark", sortAs: "NORD" },
        { zipCode: "8960", county: "Midtjylland", streets: ["Niels Ebbesens Gade", "Vestergrav", "Glamsbjergvej"], city: "Randers", country: "Denmark", sortAs: "NORD" },
        { zipCode: "00250", county: "Uusimaa", streets: ["Esplanadi", "Aleksanterinkatu", "Mannerheimintie"], city: "Helsinki", country: "Finland", sortAs: "NORD" },
        { zipCode: "33100", county: "Pirkanmaa", streets: ["Hämeenkatu", "Tammelan Puistokatu", "Kalevantie"], city: "Tampere", country: "Finland", sortAs: "NORD" },
        { zipCode: "90100", county: "Pohjois-Pohjanmaa", streets: ["Rotuaari", "Pakkahuoneenkatu", "Rantakatu"], city: "Oulu", country: "Finland", sortAs: "NORD" },
        { zipCode: "20100", county: "Varsinais-Suomi", streets: ["Aurakatu", "Eerikinkatu", "Linnankatu"], city: "Turku", country: "Finland", sortAs: "NORD" },
        { zipCode: "00510", county: "Kallio", streets: ["Hämeentie", "Fleminginkatu", "Porthaninkatu"], city: "Helsinki", country: "Finland", sortAs: "NORD" },
        { zipCode: "40720", county: "Keski-Suomi", streets: ["Vapaudenkatu", "Kauppakatu", "Jyväskylänkatu"], city: "Jyväskylä", country: "Finland", sortAs: "NORD" },
        { zipCode: "65100", county: "Pohjanmaa", streets: ["Hovioikeudenpuistikko", "Vaasanpuistikko", "Koulukatu"], city: "Vaasa", country: "Finland", sortAs: "NORD" },
        { zipCode: "90120", county: "Pohjois-Pohjanmaa", streets: ["Kajaaninkatu", "Kirkkokatu", "Torikatu"], city: "Oulu", country: "Finland", sortAs: "NORD" },
        { zipCode: "24100", county: "Satakunta", streets: ["Satamakatu", "Porintie", "Karjalankatu"], city: "Salo", country: "Finland", sortAs: "NORD" },
        { zipCode: "101", county: "Höfuðborgarsvæðið", streets: ["Laugavegur", "Bankastræti", "Austurstræti"], city: "Reykjavík", country: "Iceland", sortAs: "NORD" },
        { zipCode: "600", county: "Norðurland Eystra", streets: ["Glerárgata", "Hafnarstræti", "Skógarhlíð"], city: "Akureyri", country: "Iceland", sortAs: "NORD" },
        { zipCode: "740", county: "Suðurland", streets: ["Eyravegur", "Tryggvagata", "Heiðmörk"], city: "Selfoss", country: "Iceland", sortAs: "NORD" },
        { zipCode: "220", county: "Reykjanesbær", streets: ["Hafnargata", "Fjardarhraun", "Krossmói"], city: "Keflavík", country: "Iceland", sortAs: "NORD" },
        { zipCode: "300", county: "Vesturland", streets: ["Skúlagata", "Ólafsbraut", "Hlíðarvegur"], city: "Akranes", country: "Iceland", sortAs: "NORD" },
        { zipCode: "710", county: "Austurland", streets: ["Bjólfsgata", "Norðurgata", "Eyrarvegur"], city: "Seyðisfjörður", country: "Iceland", sortAs: "NORD" },
        { zipCode: "420", county: "Vestfirðir", streets: ["Hlíðarvegur", "Garðavegur", "Ísafjarðarvegur"], city: "Ísafjörður", country: "Iceland", sortAs: "NORD" },
        { zipCode: "800", county: "Suðurland", streets: ["Austurvegur", "Engjavegur", "Seljalandsvegur"], city: "Vík", country: "Iceland", sortAs: "NORD" }
    ],

    "Level 4": [
        { zipCode: "3000", county: "Harjumaa", streets: ["Tallinna vanalinn", "Viru tänav", "Toompea loss"], city: "Tallinn", country: "Estonia", sortAs: "EUR" },
        { zipCode: "4000", county: "Rīga Municipality", streets: ["Brīvības piemineklis", "Vecrīga", "Alberta iela"], city: "Riga", country: "Latvia", sortAs: "EUR" },
        { zipCode: "5000", county: "Vilnius", streets: ["Gedimino prospektas", "Vilniaus katedra", "Pilies gatvė"], city: "Vilnius", country: "Lithuania", sortAs: "EUR" },
        { zipCode: "5430", county: "Kaunas", streets: ["Laisvės alėja", "Kauno pilis", "Maironio gatvė"], city: "Kaunas", country: "Lithuania", sortAs: "EUR" },
        { zipCode: "6110", county: "Klaipėda", streets: ["Tiltų gatvė", "Klaipėdos senamiestis", "Herkaus Manto gatvė"], city: "Klaipėda", country: "Lithuania", sortAs: "EUR" },
        { zipCode: "7110", county: "Mažeikiai", streets: ["Draugystės gatvė", "Vilniaus gatvė", "Žemaitijos gatvė"], city: "Mažeikiai", country: "Lithuania", sortAs: "EUR" },
        { zipCode: "1001", county: "Tirana", streets: ["Rruga e Durrësit", "Rruga Myslym Shyri", "Bulevardi Zogu I"], city: "Tirana", country: "Albania", sortAs: "EUR" },
        { zipCode: "AD500", county: "Andorra la Vella Parish", streets: ["Avinguda Meritxell", "Carrer de la Unió", "Carrer Prat de la Creu"], city: "Andorra la Vella", country: "Andorra", sortAs: "EUR" },
        { zipCode: "0010", county: "Yerevan", streets: ["Mashtots Avenue", "Tigran Mets Avenue", "Northern Avenue"], city: "Yerevan", country: "Armenia", sortAs: "EUR" },
        { zipCode: "1010", county: "Vienna", streets: ["Graben", "Mariahilfer Straße", "Ringstraße"], city: "Vienna", country: "Austria", sortAs: "EUR" },
        { zipCode: "AZ1001", county: "Baku", streets: ["Nizami Street", "Heydar Aliyev Avenue", "Fuzuli Square"], city: "Baku", country: "Azerbaijan", sortAs: "EUR" },
        { zipCode: "220030", county: "Minsk", streets: ["Independence Avenue", "Zybitskaya Street", "Pobeditelei Avenue"], city: "Minsk", country: "Belarus", sortAs: "EUR" },
        { zipCode: "1000", county: "Brussels", streets: ["Rue Neuve", "Avenue Louise", "Rue des Bouchers"], city: "Brussels", country: "Belgium", sortAs: "EUR" },
        { zipCode: "71000", county: "Sarajevo", streets: ["Ferhadija Street", "Titova Street", "Maršala Tita"], city: "Sarajevo", country: "Bosnia and Herzegovina", sortAs: "EUR" },
        { zipCode: "1000", county: "Sofia", streets: ["Vitosha Boulevard", "Dondukov Boulevard", "Tsarigradsko Shose"], city: "Sofia", country: "Bulgaria", sortAs: "EUR" },
        { zipCode: "10000", county: "Zagreb", streets: ["Ilica Street", "Radiceva Street", "Tkalciceva Street"], city: "Zagreb", country: "Croatia", sortAs: "EUR" },
        { zipCode: "1097", county: "Nicosia (European Cyprus)", streets: ["Makarios Avenue", "Ledra Street", "Archbishop Kyprianou Street"], city: "Nicosia", country: "Cyprus", sortAs: "EUR" },
        { zipCode: "11000", county: "Prague", streets: ["Wenceslas Square", "Parizska Street", "Karlova Street"], city: "Prague", country: "Czech Republic", sortAs: "EUR" },
        { zipCode: "75001", county: "Paris", streets: ["Champs-Élysées", "Rue de Rivoli", "Boulevard Haussmann"], city: "Paris", country: "France", sortAs: "EUR" },
        { zipCode: "0101", county: "Tbilisi (European Georgia)", streets: ["Rustaveli Avenue", "Chavchavadze Avenue", "Agmashenebeli Avenue"], city: "Tbilisi", country: "Georgia", sortAs: "EUR" },
        { zipCode: "10115", county: "Berlin", streets: ["Unter den Linden", "Kurfürstendamm", "Friedrichstraße"], city: "Berlin", country: "Germany", sortAs: "EUR" },
        { zipCode: "10552", county: "Athens", streets: ["Ermou Street", "Panepistimiou Street", "Adrianou Street"], city: "Athens", country: "Greece", sortAs: "EUR" },
        { zipCode: "84700", county: "Cyclades", streets: ["Kamari Beach", "Perissa Beach", "Fira"], city: "Santorini", country: "Greece", sortAs: "EUR" },
        { zipCode: "72053", county: "Crete", streets: ["El. Venizelou", "Kornarou Square", "Platanias"], city: "Heraklion", country: "Greece", sortAs: "EUR" },
        { zipCode: "720 55", county: "Makrigialos", streets: ["Limanaki", "Pefki", "Diaskari"], city: "Sitia", country: "Greece", sortAs: "EUR" },
        { zipCode: "85100", county: "Dodecanese", streets: ["Mandraki", "Hippocrates Square", "Evdoxou"], city: "Rhodes", country: "Greece", sortAs: "EUR" },
        { zipCode: "60100", county: "Thessaloniki", streets: ["Thessaloniki City Center", "Aristotelous Square", "Tsimiski"], city: "Thessaloniki", country: "Greece", sortAs: "EUR" },
        { zipCode: "1051", county: "Budapest", streets: ["Andrássy Avenue", "Váci Street", "Rákóczi Road"], city: "Budapest", country: "Hungary", sortAs: "EUR" },
        { zipCode: "00184", county: "Rome", streets: ["Via del Corso", "Via Veneto", "Via Condotti"], city: "Rome", country: "Italy", sortAs: "EUR" },
        { zipCode: "9490", county: "Vaduz", streets: ["Städtle", "Fürst-Franz-Josef-Strasse", "Herrengasse"], city: "Vaduz", country: "Liechtenstein", sortAs: "EUR" },
        { zipCode: "L-1510", county: "Luxembourg City", streets: ["Avenue de la Liberté", "Rue des Bains", "Grand-Rue"], city: "Luxembourg", country: "Luxembourg", sortAs: "EUR" },
        { zipCode: "VLT 1110", county: "Valletta", streets: ["Republic Street", "Merchant Street", "St. Paul’s Street"], city: "Valletta", country: "Malta", sortAs: "EUR" },
        { zipCode: "2001", county: "Chisinau", streets: ["Stefan cel Mare Boulevard", "Puskin Street", "Negruzzi Boulevard"], city: "Chisinau", country: "Moldova", sortAs: "EUR" },
        { zipCode: "98000", county: "Monaco", streets: ["Avenue Princesse Grace", "Rue Grimaldi", "Boulevard des Moulins"], city: "Monaco", country: "Monaco", sortAs: "EUR" },
        { zipCode: "81000", county: "Podgorica", streets: ["Njegoševa Street", "Hercegovačka Street", "Slobode Boulevard"], city: "Podgorica", country: "Montenegro", sortAs: "EUR" },
        { zipCode: "1011", county: "Amsterdam", streets: ["Damrak", "Kalverstraat", "Leidsestraat"], city: "Amsterdam", country: "Netherlands", sortAs: "EUR" },
        { zipCode: "1000", county: "Skopje", streets: ["Macedonia Street", "Ilindenska Boulevard", "Dimitrie Chupovski"], city: "Skopje", country: "North Macedonia", sortAs: "EUR" },
        { zipCode: "00-001", county: "Warsaw", streets: ["Nowy Świat", "Krakowskie Przedmieście", "Marszałkowska"], city: "Warsaw", country: "Poland", sortAs: "EUR" },
        { zipCode: "1100-000", county: "Lisbon", streets: ["Rua Augusta", "Avenida da Liberdade", "Rua do Carmo"], city: "Lisbon", country: "Portugal", sortAs: "EUR" },
        { zipCode: "010001", county: "Bucharest", streets: ["Calea Victoriei", "Bulevardul Magheru", "Bulevardul Unirii"], city: "Bucharest", country: "Romania", sortAs: "EUR" },
        { zipCode: "101000", county: "Moscow (European Russia)", streets: ["Arbat Street", "Tverskaya Street", "Kuznetsky Most"], city: "Moscow", country: "Russia", sortAs: "EUR" },
        { zipCode: "47890", county: "San Marino", streets: ["Via Eugippo", "Contrada Omerelli", "Piazzale della Libertà"], city: "San Marino", country: "San Marino", sortAs: "EUR" },
        { zipCode: "11000", county: "Belgrade", streets: ["Knez Mihailova Street", "Nikola Tesla Boulevard", "Skadarlija", "Bulevar Kralja Aleksandra"], city: "Belgrade", country: "Serbia", sortAs: "EUR" },
        { zipCode: "1000", county: "Bratislava", streets: ["Obchodná Street", "Hlavná ulica", "Karadžičova"], city: "Bratislava", country: "Slovakia", sortAs: "EUR" },
        { zipCode: "01000", county: "Ljubljana", streets: ["Trg Prešerna", "Cesta V Doliču", "Bavarski Dvor"], city: "Ljubljana", country: "Slovenia", sortAs: "EUR" },
        { zipCode: "1000", county: "Zürich", streets: ["Bahnhofstrasse", "Kreis 1", "Lake Zürich"], city: "Zürich", country: "Switzerland", sortAs: "EUR" },
        { zipCode: "22000", county: "Edirne (European Turkey)", streets: ["Karaağaç Street", "Meriç River Street", "Süleymanpaşa Street"], city: "Edirne", country: "Turkey", sortAs: "EUR" },
        { zipCode: "08001", county: "Barcelona", streets: ["La Rambla", "Passeig de Gràcia", "Plaça de Catalunya"], city: "Barcelona", country: "Spain", sortAs: "EUR" },
    ],

    "Level 5": [
        { zipCode: "E1", county: "London", streets: ["Oxford Street", "Baker Street", "Trafalgar Square"], city: "London", country: "England", sortAs: "UK-I" },
        { zipCode: "M1", county: "Greater Manchester", streets: ["Deansgate", "Oxford Road", "Piccadilly"], city: "Manchester", country: "England", sortAs: "UK-I" },
        { zipCode: "B1", county: "West Midlands", streets: ["Broad Street", "Jewellery Quarter", "Digbeth"], city: "Birmingham", country: "England", sortAs: "UK-I" },
        { zipCode: "LS1", county: "West Yorkshire", streets: ["Briggate", "Kirkgate Market", "Headingley Lane"], city: "Leeds", country: "England", sortAs: "UK-I" },
        { zipCode: "L1", county: "Merseyside", streets: ["Penny Lane", "Albert Dock", "Bold Street"], city: "Liverpool", country: "England", sortAs: "UK-I" },
        { zipCode: "SO1", county: "South Hampshire", streets: ["Above Bar Street", "Highfield Lane", "Ocean Village"], city: "Southampton", country: "England", sortAs: "UK-I" },
        { zipCode: "NE1", county: "Tyne and Wear", streets: ["Grey Street", "Quayside", "Osborne Road"], city: "Newcastle", country: "England", sortAs: "UK-I" },
        { zipCode: "NG1", county: "Nottinghamshire", streets: ["Victoria Street", "Maid Marian Way", "Trent Bridge"], city: "Nottingham", country: "England", sortAs: "UK-I" },
        { zipCode: "S1", county: "South Yorkshire", streets: ["The Moor", "Ecclesall Road", "Kelham Island"], city: "Sheffield", country: "England", sortAs: "UK-I" },
        { zipCode: "BS1", county: "Avon", streets: ["Clifton Village", "Park Street", "Gloucester Road"], city: "Bristol", country: "England", sortAs: "UK-I" },
        { zipCode: "LE1", county: "Leicestershire", streets: ["Belgrave Road", "Granby Street", "Abbey Park"], city: "Leicester", country: "England", sortAs: "UK-I" },
        { zipCode: "BN1", county: "East Sussex", streets: ["North Laine", "The Lanes", "Western Road"], city: "Brighton and Hove", country: "England", sortAs: "UK-I" },
        { zipCode: "BH1", county: "Dorset", streets: ["Westover Road", "Bournemouth Gardens", "Alum Chine"], city: "Bournemouth", country: "England", sortAs: "UK-I" },
        { zipCode: "TS1", county: "Teesside", streets: ["Linthorpe Road", "Albert Park", "Stockton High Street"], city: "Middlesbrough", country: "England", sortAs: "UK-I" },
        { zipCode: "ST1", county: "Staffordshire", streets: ["Hanley Road", "Trinity Street", "Etruria Park"], city: "Stoke-on-Trent", country: "England", sortAs: "UK-I" },
        { zipCode: "CV1", county: "West Midlands", streets: ["Warwick Row", "Sky Blue Way", "Foleshill Road"], city: "Coventry", country: "England", sortAs: "UK-I" },
        { zipCode: "SR1", county: "Tyne and Wear", streets: ["High Street West", "Roker Avenue", "Hylton Road"], city: "Sunderland", country: "England", sortAs: "UK-I" },
        { zipCode: "CH1", county: "Merseyside", streets: ["Hamilton Square", "Woodside Ferry", "Conway Street"], city: "Birkenhead", country: "England", sortAs: "UK-I" },
        { zipCode: "RG1", county: "Berkshire", streets: ["Broad Street", "Friar Street", "Caversham Road"], city: "Reading", country: "England", sortAs: "UK-I" },
        { zipCode: "HU1", county: "Yorkshire", streets: ["Humber Street", "Whitefriargate", "Ferensway"], city: "Hull", country: "England", sortAs: "UK-I" },
        { zipCode: "PR1", county: "Lancashire", streets: ["Fishergate", "Garstang Road", "Avenham Park"], city: "Preston", country: "England", sortAs: "UK-I" },
        { zipCode: "SS1", county: "Essex", streets: ["High Street", "Marine Parade", "Southchurch Road"], city: "Southend-on-Sea", country: "England", sortAs: "UK-I" },
        { zipCode: "DE1", county: "Derbyshire", streets: ["Sadler Gate", "Derwent Street", "Alfreton Road"], city: "Derby", country: "England", sortAs: "UK-I" },
        { zipCode: "PL1", county: "Devon", streets: ["Union Street", "The Hoe", "New George Street"], city: "Plymouth", country: "England", sortAs: "UK-I" },
        { zipCode: "LU1", county: "Bedfordshire", streets: ["Dunstable Road", "George Street", "Chapel Street"], city: "Luton", country: "England", sortAs: "UK-I" },
        { zipCode: "BT1", county: "Antrim", streets: ["Royal Avenue", "Falls Road", "Lisburn Road"], city: "Belfast", country: "Northern Ireland", sortAs: "UK-I" },
        { zipCode: "D1", county: "Leinster", streets: ["O'Connell Street", "Grafton Street", "Temple Bar"], city: "Dublin", country: "Ireland", sortAs: "UK-I" },
        { zipCode: "G1", county: "Glasgow City", streets: ["Argyle Street", "Buchanan Street", "Sauchiehall Street"], city: "Glasgow", country: "Scotland", sortAs: "UK-I" },
        { zipCode: "EH1", county: "Lothian", streets: ["Princes Street", "The Royal Mile", "Leith Walk"], city: "Edinburgh", country: "Scotland", sortAs: "UK-I" },
        { zipCode: "CF1", county: "South Glamorgan", streets: ["Queen Street", "Cardiff Bay", "Cathedral Road"], city: "Cardiff", country: "Wales", sortAs: "UK-I" },
        { zipCode: "SA1", county: "West Glamorgan", streets: ["Wind Street", "The Kingsway", "Swansea Marina"], city: "Swansea", country: "Wales", sortAs: "UK-I" }
    ],

    "Level 6": [
        { zipCode: "10001", county: "New York", streets: ["5th Avenue", "Broadway", "Times Square"], city: "New York", country: "USA", sortAs: "N-AM" },
        { zipCode: "30301", county: "Georgia", streets: ["Peachtree Street", "Buckhead", "Midtown"], city: "Atlanta", country: "USA", sortAs: "N-AM" },
        { zipCode: "94110", county: "California", streets: ["Fisherman's Wharf", "Golden Gate Park", "Mission District"], city: "San Francisco", country: "USA", sortAs: "N-AM" },
        { zipCode: "02118", county: "Massachusetts", streets: ["Back Bay", "Beacon Hill", "Fenway Park"], city: "Boston", country: "USA", sortAs: "N-AM" },
        { zipCode: "60601", county: "Illinois", streets: ["Michigan Avenue", "Willis Tower", "Navy Pier"], city: "Chicago", country: "USA", sortAs: "N-AM" },
        { zipCode: "73301", county: "Texas", streets: ["Congress Avenue", "6th Street", "Texas State Capitol"], city: "Austin", country: "USA", sortAs: "N-AM" },
        { zipCode: "33101", county: "Florida", streets: ["Ocean Drive", "South Beach", "Little Havana"], city: "Miami", country: "USA", sortAs: "N-AM" },
        { zipCode: "90001", county: "California", streets: ["Sunset Boulevard", "Hollywood Boulevard", "Venice Beach"], city: "Los Angeles", country: "USA", sortAs: "N-AM" },
        { zipCode: "75201", county: "Texas", streets: ["Main Street", "Klyde Warren Park", "Deep Ellum"], city: "Dallas", country: "USA", sortAs: "N-AM" },
        { zipCode: "94103", county: "California", streets: ["Castro District", "Golden Gate Bridge", "Twin Peaks"], city: "San Francisco", country: "USA", sortAs: "N-AM" },
        { zipCode: "80202", county: "Colorado", streets: ["LoDo District", "16th Street Mall", "Union Station"], city: "Denver", country: "USA", sortAs: "N-AM" },
        { zipCode: "63101", county: "Missouri", streets: ["Gateway Arch", "Forest Park", "Washington Avenue"], city: "St. Louis", country: "USA", sortAs: "N-AM" },
        { zipCode: "94102", county: "California", streets: ["Hayes Valley", "Civic Center", "Opera House"], city: "San Francisco", country: "USA", sortAs: "N-AM" },
        { zipCode: "98101", county: "Washington", streets: ["Pike Place Market", "Space Needle", "Chinatown"], city: "Seattle", country: "USA", sortAs: "N-AM" },
        { zipCode: "43201", county: "Ohio", streets: ["Short North", "High Street", "Arena District"], city: "Columbus", country: "USA", sortAs: "N-AM" },
        { zipCode: "30303", county: "Georgia", streets: ["Centennial Olympic Park", "Georgia State University", "Underground Atlanta"], city: "Atlanta", country: "USA", sortAs: "N-AM" },
        { zipCode: "89109", county: "Nevada", streets: ["Las Vegas Boulevard", "The Strip", "Fremont Street"], city: "Las Vegas", country: "USA", sortAs: "N-AM" },
        { zipCode: "94109", county: "California", streets: ["Nob Hill", "Chinatown", "North Beach"], city: "San Francisco", country: "USA", sortAs: "N-AM" },
        { zipCode: "20001", county: "District of Columbia", streets: ["Dupont Circle", "The White House", "National Mall"], city: "Washington D.C.", country: "USA", sortAs: "N-AM" },
        { zipCode: "85001", county: "Arizona", streets: ["Camelback Mountain", "Desert Botanical Garden", "Downtown Phoenix"], city: "Phoenix", country: "USA", sortAs: "N-AM" },
        { zipCode: "38103", county: "Tennessee", streets: ["Beale Street", "Sun Studio", "Graceland"], city: "Memphis", country: "USA", sortAs: "N-AM" },
        { zipCode: "53202", county: "Wisconsin", streets: ["Lakefront", "Brady Street", "Third Ward"], city: "Milwaukee", country: "USA", sortAs: "N-AM" },
        { zipCode: "44101", county: "Ohio", streets: ["Cleveland Browns Stadium", "Rock and Roll Hall of Fame", "West Side Market"], city: "Cleveland", country: "USA", sortAs: "N-AM" },
        { zipCode: "2000", county: "Ontario", streets: ["Queen Street", "King Street", "University Avenue"], city: "Toronto", country: "Canada", sortAs: "N-AM" },
        { zipCode: "H3A 1B7", county: "Quebec", streets: ["Rue Sainte-Catherine", "Avenue des Pins", "Montreal Street"], city: "Montreal", country: "Canada", sortAs: "N-AM" },
        { zipCode: "75001", county: "Mexico City", streets: ["Avenida Reforma", "Calle 5 de Febrero", "Avenida Insurgentes"], city: "Mexico City", country: "Mexico", sortAs: "N-AM" },
        { zipCode: "64000", county: "Nuevo León", streets: ["Avenida Juárez", "Calle Madero", "Calle Padre Mier"], city: "Monterrey", country: "Mexico", sortAs: "N-AM" },
        { zipCode: "98000", county: "Baja California", streets: ["Boulevard Costero", "Calle Primera", "Avenida Revolución"], city: "Tijuana", country: "Mexico", sortAs: "N-AM" },
        { zipCode: "V6B 1A1", county: "British Columbia", streets: ["Granville Street", "Robson Street", "Stanley Park"], city: "Vancouver", country: "Canada", sortAs: "N-AM" },
        { zipCode: "K1A 0B1", county: "Ontario", streets: ["Wellington Street", "Rideau Street", "Parliament Hill"], city: "Ottawa", country: "Canada", sortAs: "N-AM" },
        { zipCode: "T2P 3T1", county: "Alberta", streets: ["Stephen Avenue", "6th Avenue SW", "Prince Island Park"], city: "Calgary", country: "Canada", sortAs: "N-AM" },
        { zipCode: "M5A 1A1", county: "Ontario", streets: ["Front Street", "St. Lawrence Market", "Toronto Islands"], city: "Toronto", country: "Canada", sortAs: "N-AM" },
        { zipCode: "R3C 1S1", county: "Manitoba", streets: ["Portage Avenue", "Assiniboine Park", "The Forks"], city: "Winnipeg", country: "Canada", sortAs: "N-AM" },
        { zipCode: "99501", county: "Alaska", streets: ["Downtown Anchorage", "4th Avenue", "Kincaid Park"], city: "Anchorage", country: "USA", sortAs: "N-AM" },
        { zipCode: "99701", county: "Alaska", streets: ["College Road", "Northrim Bank", "Chena River"], city: "Fairbanks", country: "USA", sortAs: "N-AM" },
        { zipCode: "99723", county: "Alaska", streets: ["Main Street", "Fort Greely", "Sullivan Road"], city: "Delta Junction", country: "USA", sortAs: "N-AM" },
        { zipCode: "99801", county: "Alaska", streets: ["Douglas Island", "Downtown Juneau", "Gold Creek"], city: "Juneau", country: "USA", sortAs: "N-AM" },
        { zipCode: "99775", county: "Alaska", streets: ["Kuskokwim River", "Bethel", "Ekwok"], city: "Bethel", country: "USA", sortAs: "N-AM" }
    ],


    "Level 7": [
        { zipCode: "C1000AA", county: "Buenos Aires Metropolitan", streets: ["Avenida 9 de Julio", "Avenida Corrientes", "Calle Florida"], city: "Buenos Aires", country: "Argentina", sortAs: "S-AM" },
        { zipCode: "LP1010", county: "La Paz Capital District", streets: ["El Prado", "Calle Jaén", "Avenida Arce"], city: "La Paz", country: "Bolivia", sortAs: "S-AM" },
        { zipCode: "01310-000", county: "São Paulo State", streets: ["Avenida Paulista", "Copacabana Beach", "Ipanema Beach"], city: "Brasília", country: "Brazil", sortAs: "S-AM" },
        { zipCode: "7550000", county: "Santiago Metropolitan Region", streets: ["Avenida Apoquindo", "Barrio Bellavista", "Paseo Ahumada"], city: "Santiago", country: "Chile", sortAs: "S-AM" },
        { zipCode: "110111", county: "Cundinamarca", streets: ["Carrera Séptima", "Calle 26", "Zona Rosa"], city: "Bogotá", country: "Colombia", sortAs: "S-AM" },
        { zipCode: "170102", county: "Pichincha", streets: ["Avenida de los Shyris", "Calle García Moreno", "Calle Benalcázar"], city: "Quito", country: "Ecuador", sortAs: "S-AM" },
        { zipCode: "GE0001", county: "Georgetown Capital District", streets: ["Main Street", "Camp Street", "Brickdam"], city: "Georgetown", country: "Guyana", sortAs: "S-AM" },
        { zipCode: "8000", county: "Asunción Capital", streets: ["Avenida Mariscal López", "Calle Palma", "Avenida Eusebio Ayala"], city: "Asunción", country: "Paraguay", sortAs: "S-AM" },
        { zipCode: "LIMA15000", county: "Lima Region", streets: ["Jirón de la Unión", "Avenida Arequipa", "Malecón de Miraflores"], city: "Lima", country: "Peru", sortAs: "S-AM" },
        { zipCode: "SR1200", county: "Paramaribo", streets: ["Domineestraat", "Heerenstraat", "Kwattaweg"], city: "Paramaribo", country: "Suriname", sortAs: "S-AM" },
        { zipCode: "11200", county: "Montevideo Department", streets: ["Avenida 18 de Julio", "Rambla de Montevideo", "Peatonal Sarandí"], city: "Montevideo", country: "Uruguay", sortAs: "S-AM" },
        { zipCode: "CC2001", county: "Caracas Municipality", streets: ["Avenida Bolívar", "Avenida Urdaneta", "Paseo Los Próceres"], city: "Caracas", country: "Venezuela", sortAs: "S-AM" }
    ],

    "Level 8": [
        { zipCode: "1001", county: "Afghanistan", streets: ["Kabul Road", "Shah-e-Do Shamshira Street", "Jade Maiwand"], city: "Kabul", country: "Afghanistan", sortAs: "ASIA" },
        { zipCode: "0002", county: "Armenia", streets: ["Mashtots Avenue", "Tigran Mets Avenue", "Northern Avenue"], city: "Yerevan", country: "Armenia", sortAs: "ASIA" },
        { zipCode: "AZ1000", county: "Azerbaijan", streets: ["Nizami Street", "Heydar Aliyev Avenue", "Azadliq Square"], city: "Baku", country: "Azerbaijan", sortAs: "ASIA" },
        { zipCode: "PO Box 1234", county: "Bahrain", streets: ["Manama Avenue", "Shaikh Khalifa Road", "Budaiya Highway"], city: "Manama", country: "Bahrain", sortAs: "ASIA" },
        { zipCode: "1207", county: "Bangladesh", streets: ["Dhanmondi 27", "Gulshan Avenue", "Motijheel"], city: "Dhaka", country: "Bangladesh", sortAs: "ASIA" },
        { zipCode: "11001", county: "Bhutan", streets: ["Norzin Lam", "Chorten Lam", "Chang Lam"], city: "Thimphu", country: "Bhutan", sortAs: "ASIA" },
        { zipCode: "BB3713", county: "Brunei", streets: ["Jalan Sultan", "Jalan Residency", "Jalan Tutong"], city: "Bandar Seri Begawan", country: "Brunei", sortAs: "ASIA" },
        { zipCode: "12000", county: "Cambodia", streets: ["Norodom Boulevard", "Preah Sisowath Quay", "Monivong Boulevard"], city: "Phnom Penh", country: "Cambodia", sortAs: "ASIA" },
        { zipCode: "100000", county: "China", streets: ["Wangfujing Street", "Nanjing Road", "Chang'an Avenue"], city: "Beijing", country: "China", sortAs: "ASIA" },
        { zipCode: "9900", county: "Famagusta (Asian Cyprus)", streets: ["Salamis Road", "Deryneia Road", "Famagusta Beach Road"], city: "Famagusta", country: "Cyprus", sortAs: "ASIA" },
        { zipCode: "6000", county: "Batumi (Asian Georgia)", streets: ["Rustaveli Avenue", "Ninoshvili Street", "Gonio Road"], city: "Batumi", country: "Georgia", sortAs: "ASIA" },
        { zipCode: "110001", county: "India", streets: ["Connaught Place", "Janpath", "MG Road"], city: "New Delhi", country: "India", sortAs: "ASIA" },
        { zipCode: "10110", county: "Indonesia", streets: ["Jalan Sudirman", "Jalan Thamrin", "Jalan Medan Merdeka"], city: "Jakarta", country: "Indonesia", sortAs: "ASIA" },
        { zipCode: "11365", county: "Iran", streets: ["Valiasr Street", "Enghelab Street", "Shariati Street"], city: "Tehran", country: "Iran", sortAs: "ASIA" },
        { zipCode: "10011", county: "Iraq", streets: ["Al-Rasheed Street", "Sadoun Street", "Haifa Street"], city: "Baghdad", country: "Iraq", sortAs: "ASIA" },
        { zipCode: "91950", county: "Israel", streets: ["Ben Yehuda Street", "Jaffa Road", "Herzl Boulevard"], city: "Jerusalem", country: "Israel", sortAs: "ASIA" },
        { zipCode: "100-0001", county: "Japan", streets: ["Ginza Street", "Shibuya Crossing", "Omotesando Avenue"], city: "Tokyo", country: "Japan", sortAs: "ASIA" },
        { zipCode: "11118", county: "Jordan", streets: ["Rainbow Street", "Abdullah Ghosheh Street", "Zahran Street"], city: "Amman", country: "Jordan", sortAs: "ASIA" },
        { zipCode: "050000", county: "Kazakhstan", streets: ["Abay Avenue", "Al-Farabi Avenue", "Dostyk Street"], city: "Almaty", country: "Kazakhstan", sortAs: "ASIA" },
        { zipCode: "13000", county: "Kuwait", streets: ["Gulf Road", "Al-Shuhada Street", "Soor Street"], city: "Kuwait City", country: "Kuwait", sortAs: "ASIA" },
        { zipCode: "720001", county: "Kyrgyzstan", streets: ["Chuy Avenue", "Manas Avenue", "Molodaya Gvardiya Boulevard"], city: "Bishkek", country: "Kyrgyzstan", sortAs: "ASIA" },
        { zipCode: "01000", county: "Laos", streets: ["Lane Xang Avenue", "Setthathirath Road", "Samsenthai Road"], city: "Vientiane", country: "Laos", sortAs: "ASIA" },
        { zipCode: "1107", county: "Lebanon", streets: ["Hamra Street", "Beirut Souks", "Mar Mikhael Street"], city: "Beirut", country: "Lebanon", sortAs: "ASIA" },
        { zipCode: "50088", county: "Malaysia", streets: ["Bukit Bintang", "Jalan Raja Laut", "Petaling Street"], city: "Kuala Lumpur", country: "Malaysia", sortAs: "ASIA" },
        { zipCode: "20002", county: "Maldives", streets: ["Fareedhee Magu", "Orchid Magu", "Majeedhee Magu"], city: "Malé", country: "Maldives", sortAs: "ASIA" },
        { zipCode: "976001", county: "Mongolia", streets: ["Peace Avenue", "Sukhbaatar Square", "Chinggis Avenue"], city: "Ulaanbaatar", country: "Mongolia", sortAs: "ASIA" },
        { zipCode: "11201", county: "Myanmar", streets: ["Shwe Bontha Street", "Anawrahta Road", "Kandawgyi Road"], city: "Yangon", country: "Myanmar", sortAs: "ASIA" },
        { zipCode: "44600", county: "Nepal", streets: ["Durbar Marg", "New Road", "Thamel"], city: "Kathmandu", country: "Nepal", sortAs: "ASIA" },
        { zipCode: "999700", county: "North Korea", streets: ["Kim Il-sung Square", "Ryomyong Street", "Tongil Street"], city: "Pyongyang", country: "North Korea", sortAs: "ASIA" },
        { zipCode: "113", county: "Oman", streets: ["Sultan Qaboos Street", "Ruwi Street", "Al Khuwair Street"], city: "Muscat", country: "Oman", sortAs: "ASIA" },
        { zipCode: "54000", county: "Pakistan", streets: ["Mall Road", "MM Alam Road", "Gulberg Main"], city: "Lahore", country: "Pakistan", sortAs: "ASIA" },
        { zipCode: "1001", county: "Philippines", streets: ["Roxas Boulevard", "Ayala Avenue", "Katipunan Avenue"], city: "Manila", country: "Philippines", sortAs: "ASIA" },
        { zipCode: "12345", county: "Qatar", streets: ["Corniche Street", "Salwa Road", "Al Waab Street"], city: "Doha", country: "Qatar", sortAs: "ASIA" },
        { zipCode: "100000", county: "Vladivostok (Asian Russia)", streets: ["Russkaya Street", "Svetlanskaya Street", "Fokina Street"], city: "Vladivostok", country: "Russia", sortAs: "ASIA" },
        { zipCode: "11564", county: "Saudi Arabia", streets: ["King Fahd Road", "Tahlia Street", "Olaya Street"], city: "Riyadh", country: "Saudi Arabia", sortAs: "ASIA" },
        { zipCode: "639798", county: "Singapore", streets: ["Orchard Road", "Clarke Quay", "Marina Bay"], city: "Singapore", country: "Singapore", sortAs: "ASIA" },
        { zipCode: "04524", county: "South Korea", streets: ["Gangnam Boulevard", "Insadong Street", "Myeongdong"], city: "Seoul", country: "South Korea", sortAs: "ASIA" },
        { zipCode: "00200", county: "Sri Lanka", streets: ["Galle Road", "Bauddhaloka Mawatha", "Marine Drive"], city: "Colombo", country: "Sri Lanka", sortAs: "ASIA" },
        { zipCode: "8001", county: "Syria", streets: ["Abu Roumaneh", "Hamra Street", "Al Thawra Street"], city: "Damascus", country: "Syria", sortAs: "ASIA" },
        { zipCode: "734000", county: "Tajikistan", streets: ["Somoni Avenue", "Rudaki Avenue", "Hovaron Street"], city: "Dushanbe", country: "Tajikistan", sortAs: "ASIA" },
        { zipCode: "10110", county: "Thailand", streets: ["Sukhumvit Road", "Khao San Road", "Silom Road"], city: "Bangkok", country: "Thailand", sortAs: "ASIA" },
        { zipCode: "670-1", county: "Timor-Leste", streets: ["Rua de Direito", "Avenida Nicolau Lobato", "Rua Dom Boa Ventura"], city: "Dili", country: "Timor-Leste", sortAs: "ASIA" },
        { zipCode: "06000", county: "Ankara (Asian Turkey)", streets: ["Atatürk Boulevard", "Tunali Hilmi Street", "Kocatepe Street"], city: "Ankara", country: "Turkey", sortAs: "ASIA" },
        { zipCode: "744000", county: "Turkmenistan", streets: ["Galkynysh Avenue", "Archabil Avenue", "Magtymguly Avenue"], city: "Ashgabat", country: "Turkmenistan", sortAs: "ASIA" },
        { zipCode: "00001", county: "United Arab Emirates", streets: ["Sheikh Zayed Road", "Jumeirah Beach Road", "Al Khail Road"], city: "Dubai", country: "United Arab Emirates", sortAs: "ASIA" },
        { zipCode: "100100", county: "Uzbekistan", streets: ["Amir Timur Street", "Sharaf Rashidov Street", "Independence Square"], city: "Tashkent", country: "Uzbekistan", sortAs: "ASIA" },
        { zipCode: "700000", county: "Vietnam", streets: ["Nguyen Hue Street", "Pham Ngu Lao Street", "Le Duan Boulevard"], city: "Ho Chi Minh City", country: "Vietnam", sortAs: "ASIA" },
        { zipCode: "8911", county: "Yemen", streets: ["Al Zubayri Street", "Hadda Street", "Al Sabeen Street"], city: "Sanaa", country: "Yemen", sortAs: "ASIA" }
    ],

    "Level 9": [
        { zipCode: "16000", county: "Algeria", streets: ["Rue Didouche Mourad", "Boulevard Mohammed V", "Place des Martyrs"], city: "Algiers", country: "Algeria", sortAs: "AFR" },
        { zipCode: "2000", county: "Angola", streets: ["Rua Hoji Ya Henda", "Avenida Deolinda Rodrigues", "Rua Rainha Ginga"], city: "Luanda", country: "Angola", sortAs: "AFR" },
        { zipCode: "01BP123", county: "Benin", streets: ["Rue des Martyrs", "Avenue Steinmetz", "Boulevard de la Marina"], city: "Cotonou", country: "Benin", sortAs: "AFR" },
        { zipCode: "0000", county: "Botswana", streets: ["Nelson Mandela Drive", "Khama Crescent", "Independence Avenue"], city: "Gaborone", country: "Botswana", sortAs: "AFR" },
        { zipCode: "01BP456", county: "Burkina Faso", streets: ["Avenue Kwamé Nkrumah", "Rue de la Grande Mosquée", "Rue de l'Université"], city: "Ouagadougou", country: "Burkina Faso", sortAs: "AFR" },
        { zipCode: "BJM120", county: "Burundi", streets: ["Avenue de la Révolution", "Boulevard Patrice Lumumba", "Rue de l'Indépendance"], city: "Bujumbura", country: "Burundi", sortAs: "AFR" },
        { zipCode: "237001", county: "Cameroon", streets: ["Boulevard de l'Avenue Kennedy", "Rue Joseph Essono", "Avenue des Banques"], city: "Yaoundé", country: "Cameroon", sortAs: "AFR" },
        { zipCode: "7600", county: "Cape Verde", streets: ["Rua 5 de Julho", "Avenida Amílcar Cabral", "Rua Pedonal"], city: "Praia", country: "Cape Verde", sortAs: "AFR" },
        { zipCode: "236", county: "Central African Republic", streets: ["Avenue de l'Indépendance", "Boulevard des Martyrs", "Rue de l'Évêché"], city: "Bangui", country: "Central African Republic", sortAs: "AFR" },
        { zipCode: "NDJ1234", county: "Chad", streets: ["Avenue Charles de Gaulle", "Rue de la Liberté", "Rue de l'Assemblée"], city: "N'Djamena", country: "Chad", sortAs: "AFR" },
        { zipCode: "KM9900", county: "Comoros", streets: ["Rue de la Corniche", "Avenue de l'Aéroport", "Place de l'Indépendance"], city: "Moroni", country: "Comoros", sortAs: "AFR" },
        { zipCode: "243101", county: "Democratic Republic of the Congo", streets: ["Avenue des Forces Armées", "Boulevard du 30 Juin", "Rue Kalemie"], city: "Kinshasa", country: "DR Congo", sortAs: "AFR" },
        { zipCode: "242001", county: "Republic of the Congo", streets: ["Avenue de l'Amitié", "Boulevard Denis Sassou Nguesso", "Rue Kouyou"], city: "Brazzaville", country: "Congo", sortAs: "AFR" },
        { zipCode: "225", county: "Côte d'Ivoire", streets: ["Boulevard Valéry Giscard d'Estaing", "Rue du Commerce", "Avenue du Président Houphouët-Boigny"], city: "Abidjan", country: "Côte d'Ivoire", sortAs: "AFR" },
        { zipCode: "DJI123", county: "Djibouti", streets: ["Rue de Paris", "Boulevard de la République", "Rue de Venise"], city: "Djibouti", country: "Djibouti", sortAs: "AFR" },
        { zipCode: "11511", county: "Egypt", streets: ["Tahrir Square", "Sharia Al-Muizz", "Corniche El-Nil"], city: "Cairo", country: "Egypt", sortAs: "AFR" },
        { zipCode: "24000", county: "Equatorial Guinea", streets: ["Avenida Hassan II", "Calle de la Libertad", "Calle Mongomo"], city: "Malabo", country: "Equatorial Guinea", sortAs: "AFR" },
        { zipCode: "ERI001", county: "Eritrea", streets: ["Harnet Avenue", "Sematat Avenue", "Godena Harnet"], city: "Asmara", country: "Eritrea", sortAs: "AFR" },
        { zipCode: "H100", county: "Eswatini", streets: ["Allister Miller Street", "Mzilikazi Street", "Gwamile Street"], city: "Mbabane", country: "Eswatini", sortAs: "AFR" },
        { zipCode: "1000", county: "Ethiopia", streets: ["Churchill Avenue", "Bole Road", "Africa Avenue"], city: "Addis Ababa", country: "Ethiopia", sortAs: "AFR" },
        { zipCode: "24101", county: "Gabon", streets: ["Boulevard Triomphal", "Rue d’Omnisport", "Avenue Léon Mba"], city: "Libreville", country: "Gabon", sortAs: "AFR" },
        { zipCode: "2200", county: "Gambia", streets: ["Kairaba Avenue", "Jimpex Road", "Independence Drive"], city: "Banjul", country: "Gambia", sortAs: "AFR" },
        { zipCode: "233", county: "Ghana", streets: ["Oxford Street", "Kojo Thompson Road", "Independence Avenue"], city: "Accra", country: "Ghana", sortAs: "AFR" },
        { zipCode: "GN001", county: "Guinea", streets: ["Rue du Niger", "Avenue de la République", "Boulevard Telly Diallo"], city: "Conakry", country: "Guinea", sortAs: "AFR" },
        { zipCode: "GW101", county: "Guinea-Bissau", streets: ["Avenida Amílcar Cabral", "Rua de Bissau", "Praça dos Heróis Nacionais"], city: "Bissau", country: "Guinea-Bissau", sortAs: "AFR" },
        { zipCode: "KE00100", county: "Kenya", streets: ["Moi Avenue", "Kenyatta Avenue", "Haile Selassie Avenue"], city: "Nairobi", country: "Kenya", sortAs: "AFR" },
        { zipCode: "100", county: "Lesotho", streets: ["Kingsway Road", "Pioneer Road", "Moshoeshoe Road"], city: "Maseru", country: "Lesotho", sortAs: "AFR" },
        { zipCode: "LIB101", county: "Liberia", streets: ["Broad Street", "UN Drive", "Randall Street"], city: "Monrovia", country: "Liberia", sortAs: "AFR" },
        { zipCode: "LY901", county: "Libya", streets: ["First of September Street", "Gargaresh Road", "Tripoli Street"], city: "Tripoli", country: "Libya", sortAs: "AFR" },
        { zipCode: "MG101", county: "Madagascar", streets: ["Rue de l'Indépendance", "Avenue de l’Indépendance", "Rue Rakotozafy"], city: "Antananarivo", country: "Madagascar", sortAs: "AFR" },
        { zipCode: "2010", county: "Malawi", streets: ["Kamuzu Procession Road", "Independence Drive", "Chilambula Road"], city: "Lilongwe", country: "Malawi", sortAs: "AFR" },
        { zipCode: "BP124", county: "Mali", streets: ["Rue Baba Diarra", "Avenue de l’Indépendance", "Rue Mohamed V"], city: "Bamako", country: "Mali", sortAs: "AFR" },
        { zipCode: "001", county: "Mauritania", streets: ["Avenue Abdel Nasser", "Boulevard de la Résistance", "Rue de l'Hôpital"], city: "Nouakchott", country: "Mauritania", sortAs: "AFR" },
        { zipCode: "MU001", county: "Mauritius", streets: ["Sir William Newton Street", "Royal Road", "Queen Street"], city: "Port Louis", country: "Mauritius", sortAs: "AFR" },
        { zipCode: "20000", county: "Morocco", streets: ["Avenue Hassan II", "Boulevard Mohammed V", "Rue de Paris"], city: "Casablanca", country: "Morocco", sortAs: "AFR" },
        { zipCode: "MAP101", county: "Mozambique", streets: ["Avenida Julius Nyerere", "Avenida Eduardo Mondlane", "Avenida Samora Machel"], city: "Maputo", country: "Mozambique", sortAs: "AFR" },
        { zipCode: "WIND100", county: "Namibia", streets: ["Independence Avenue", "Robert Mugabe Avenue", "Sam Nujoma Drive"], city: "Windhoek", country: "Namibia", sortAs: "AFR" },
        { zipCode: "NE101", county: "Niger", streets: ["Boulevard de l'Indépendance", "Avenue du Président Kennedy", "Rue de l’Hôpital"], city: "Niamey", country: "Niger", sortAs: "AFR" },
        { zipCode: "234001", county: "Nigeria", streets: ["Broad Street", "Awolowo Road", "Ahmadu Bello Way"], city: "Lagos", country: "Nigeria", sortAs: "AFR" },
        { zipCode: "RW250", county: "Rwanda", streets: ["Avenue de l'Indépendance", "KG 7 Avenue", "KN 5 Road"], city: "Kigali", country: "Rwanda", sortAs: "AFR" },
        { zipCode: "STP001", county: "São Tomé and Príncipe", streets: ["Avenida Marginal 12 de Julho", "Rua de Santo António", "Praça da Independência"], city: "São Tomé", country: "São Tomé and Príncipe", sortAs: "AFR" },
        { zipCode: "SN123", county: "Senegal", streets: ["Rue Moussé Diop", "Boulevard du Général de Gaulle", "Avenue Blaise Diagne"], city: "Dakar", country: "Senegal", sortAs: "AFR" },
        { zipCode: "SC001", county: "Seychelles", streets: ["Independence Avenue", "Francis Rachel Street", "Revolution Avenue"], city: "Victoria", country: "Seychelles", sortAs: "AFR" },
        { zipCode: "SL102", county: "Sierra Leone", streets: ["Lumley Beach Road", "Wilkinson Road", "Fourah Bay Road"], city: "Freetown", country: "Sierra Leone", sortAs: "AFR" },
        { zipCode: "SOM001", county: "Somalia", streets: ["Wadada Wadnaha", "Hamar Weyne Street", "Shabelle Street"], city: "Mogadishu", country: "Somalia", sortAs: "AFR" },
        { zipCode: "ZA101", county: "South Africa", streets: ["Nelson Mandela Square", "Long Street", "Vilakazi Street"], city: "Johannesburg", country: "South Africa", sortAs: "AFR" },
        { zipCode: "JUB01", county: "South Sudan", streets: ["Juba Town Road", "Nimule Street", "Unity Avenue"], city: "Juba", country: "South Sudan", sortAs: "AFR" },
        { zipCode: "KHRT01", county: "Sudan", streets: ["Nile Street", "Airport Road", "Sharia Al-Souk"], city: "Khartoum", country: "Sudan", sortAs: "AFR" },
        { zipCode: "TZ255", county: "Tanzania", streets: ["Samora Avenue", "Lumumba Street", "Ali Hassan Mwinyi Road"], city: "Dar es Salaam", country: "Tanzania", sortAs: "AFR" },
        { zipCode: "TG456", county: "Togo", streets: ["Rue du Commerce", "Boulevard de la Paix", "Rue de la Bourse"], city: "Lomé", country: "Togo", sortAs: "AFR" },
        { zipCode: "1001", county: "Tunisia", streets: ["Avenue Habib Bourguiba", "Rue de Marseille", "Avenue de France"], city: "Tunis", country: "Tunisia", sortAs: "AFR" },
        { zipCode: "UG256", county: "Uganda", streets: ["Kampala Road", "Jinja Road", "Bombo Road"], city: "Kampala", country: "Uganda", sortAs: "AFR" },
        { zipCode: "2601", county: "Zambia", streets: ["Cairo Road", "Great East Road", "Lumumba Road"], city: "Lusaka", country: "Zambia", sortAs: "AFR" },
        { zipCode: "ZW02", county: "Zimbabwe", streets: ["Robert Mugabe Road", "Samora Machel Avenue", "Julius Nyerere Way"], city: "Harare", country: "Zimbabwe", sortAs: "AFR" }
    ],
    "Level 10": [
        { zipCode: "10101", county: "Costa Rica", streets: ["Avenida Central", "Calle 5", "Paseo Colón"], city: "San José", country: "Costa Rica", sortAs: "C-AM" },
        { zipCode: "01010", county: "Guatemala", streets: ["Avenida La Reforma", "Calle 6", "Calle 18"], city: "Guatemala City", country: "Guatemala", sortAs: "C-AM" },
        { zipCode: "11101", county: "Honduras", streets: ["Boulevard Morazan", "Calle 10", "Avenida La Paz"], city: "Tegucigalpa", country: "Honduras", sortAs: "C-AM" },
        { zipCode: "20001", county: "Nicaragua", streets: ["Calle 1", "Avenida Bolívar", "Calle El Carmen"], city: "Managua", country: "Nicaragua", sortAs: "C-AM" },
        { zipCode: "0801", county: "Panama", streets: ["Calle 50", "Avenida Balboa", "Calle 5 de Mayo"], city: "Panama City", country: "Panama", sortAs: "C-AM" },
        { zipCode: "BELZ01", county: "Belize", streets: ["Albert Street", "Princess Margaret Drive", "Earl's Court"], city: "Belmopan", country: "Belize", sortAs: "C-AM" },
        { zipCode: "1000", county: "El Salvador", streets: ["Calle Arce", "Boulevard Los Héroes", "Avenida Las Delicias"], city: "San Salvador", country: "El Salvador", sortAs: "C-AM" }
    ],
    "Level 11": [
        { zipCode: "10400", county: "Cuba", streets: ["Calle 23", "Calle Obispo", "Malecón"], city: "Havana", country: "Cuba", sortAs: "CRBN" },
        { zipCode: "HT6120", county: "Haiti", streets: ["Rue du Magasin de l'État", "Boulevard Toussaint Louverture", "Rue Capois"], city: "Port-au-Prince", country: "Haiti", sortAs: "CRBN" },
        { zipCode: "11501", county: "Dominican Republic", streets: ["El Conde Street", "Churchill Avenue", "Las Damas Street"], city: "Santo Domingo", country: "Dominican Republic", sortAs: "CRBN" },
        { zipCode: "JMACE17", county: "Jamaica", streets: ["Half Way Tree Road", "Knutsford Boulevard", "Marcus Garvey Drive"], city: "Kingston", country: "Jamaica", sortAs: "CRBN" },
        { zipCode: "00901", county: "Puerto Rico", streets: ["Calle Fortaleza", "Ashford Avenue", "Calle San Sebastián"], city: "San Juan", country: "Puerto Rico", sortAs: "CRBN" },
        { zipCode: "N-3919", county: "Bahamas", streets: ["Bay Street", "Cable Beach Road", "Market Street"], city: "Nassau", country: "Bahamas", sortAs: "CRBN" },
        { zipCode: "BB11114", county: "Barbados", streets: ["Broad Street", "High Street", "Bay Street"], city: "Bridgetown", country: "Barbados", sortAs: "CRBN" },
        { zipCode: "TT150602", county: "Trinidad and Tobago", streets: ["Frederick Street", "Ariapita Avenue", "Independence Square"], city: "Port of Spain", country: "Trinidad and Tobago", sortAs: "CRBN" },
        { zipCode: "GD12345", county: "Grenada", streets: ["Melville Street", "Carenage Road", "Lagoon Road"], city: "St. George's", country: "Grenada", sortAs: "CRBN" },
        { zipCode: "VC0102", county: "Saint Vincent and the Grenadines", streets: ["Bay Street", "Grenville Street", "Middle Street"], city: "Kingstown", country: "Saint Vincent and the Grenadines", sortAs: "CRBN" },
        { zipCode: "LC04 301", county: "Saint Lucia", streets: ["Bridge Street", "Bourbon Street", "Chisel Street"], city: "Castries", country: "Saint Lucia", sortAs: "CRBN" },
        { zipCode: "KN0101", county: "Saint Kitts and Nevis", streets: ["Fort Street", "Cayon Street", "Bay Road"], city: "Basseterre", country: "Saint Kitts and Nevis", sortAs: "CRBN" },
        { zipCode: "A1-200", county: "Antigua and Barbuda", streets: ["Market Street", "High Street", "Long Street"], city: "St. John's", country: "Antigua and Barbuda", sortAs: "CRBN" },
        { zipCode: "DM003", county: "Dominica", streets: ["King George V Street", "Hillsborough Street", "Bay Front"], city: "Roseau", country: "Dominica", sortAs: "CRBN" }
    ],
    "Level 12": [
        { zipCode: "2000", county: "New South Wales", streets: ["Oxford Street", "Bondi Beach", "Circular Quay"], city: "Sydney", country: "Australia", sortAs: "OCN" },
        { zipCode: "3000", county: "Victoria", streets: ["Flinders Street", "Federation Square", "Queen Victoria Market"], city: "Melbourne", country: "Australia", sortAs: "OCN" },
        { zipCode: "4000", county: "Queensland", streets: ["Brisbane River", "South Bank", "Queen Street Mall"], city: "Brisbane", country: "Australia", sortAs: "OCN" },
        { zipCode: "5000", county: "South Australia", streets: ["North Terrace", "Rundle Mall", "Glenelg Beach"], city: "Adelaide", country: "Australia", sortAs: "OCN" },
        { zipCode: "6000", county: "Western Australia", streets: ["Kings Park", "Elizabeth Quay", "Hay Street"], city: "Perth", country: "Australia", sortAs: "OCN" },
        { zipCode: "7000", county: "Tasmania", streets: ["Sullivan's Cove", "Salamanca Place", "Hobart Waterfront"], city: "Hobart", country: "Australia", sortAs: "OCN" },
        { zipCode: "2600", county: "Australian Capital Territory", streets: ["Parliament House", "Lake Burley Griffin", "Canberra Centre"], city: "Canberra", country: "Australia", sortAs: "OCN" },
        { zipCode: "3004", county: "Victoria", streets: ["South Melbourne Market", "Albert Park", "St. Kilda Beach"], city: "Melbourne", country: "Australia", sortAs: "OCN" },
        { zipCode: "96850", county: "Hawaii", streets: ["Waikiki Beach", "Diamond Head", "Ala Moana"], city: "Honolulu", country: "USA", sortAs: "OCN" },
        { zipCode: "7000", county: "Fiji", streets: ["Suva Street", "Albert Park", "Saraswati College"], city: "Suva", country: "Fiji", sortAs: "OCN" },
        { zipCode: "680", county: "Kiribati", streets: ["Tarawa", "Bairiki", "Betio", "Anewa"], city: "Tarawa", country: "Kiribati", sortAs: "OCN" },
        { zipCode: "96960", county: "Marshall Islands", streets: ["Delap", "Majuro", "Ebeye"], city: "Majuro", country: "Marshall Islands", sortAs: "OCN" },
        { zipCode: "96941", county: "Micronesia", streets: ["Pohnpei", "Kolonia", "Sokehs", "Nett"], city: "Kolonia", country: "Micronesia", sortAs: "OCN" },
        { zipCode: "03000", county: "Nauru", streets: ["Boe", "Yaren", "Aiwo"], city: "Yaren", country: "Nauru", sortAs: "OCN" },
        { zipCode: "0001", county: "New Zealand", streets: ["Queen Street", "Auckland Domain", "Sky Tower"], city: "Auckland", country: "New Zealand", sortAs: "OCN" },
        { zipCode: "6011", county: "Wellington", streets: ["Cuba Street", "Mount Victoria", "Wellington Waterfront"], city: "Wellington", country: "New Zealand", sortAs: "OCN" },
        { zipCode: "7010", county: "Tasman", streets: ["Nelson Harbour", "Tahunanui Beach", "Richmond Park"], city: "Nelson", country: "New Zealand", sortAs: "OCN" },
        { zipCode: "96940", county: "Palau", streets: ["Koror", "Melekeok", "Ngerulmud"], city: "Koror", country: "Palau", sortAs: "OCN" },
        { zipCode: "1000", county: "Papua New Guinea", streets: ["Port Moresby", "Moresby Arts Theatre", "Konedobu"], city: "Port Moresby", country: "Papua New Guinea", sortAs: "OCN" },
        { zipCode: "0002", county: "Samoa", streets: ["Apia", "Mulinu'u", "Vailima"], city: "Apia", country: "Samoa", sortAs: "OCN" },
        { zipCode: "880", county: "Solomon Islands", streets: ["Honiara", "Chinatown", "Point Cruz"], city: "Honiara", country: "Solomon Islands", sortAs: "OCN" },
        { zipCode: "950", county: "Tonga", streets: ["Nuku'alofa", "Talafo'ou", "Kolomotu'a"], city: "Nuku'alofa", country: "Tonga", sortAs: "OCN" },
        { zipCode: "9999", county: "Tuvalu", streets: ["Funafuti", "Vaiaku", "Nanumea"], city: "Funafuti", country: "Tuvalu", sortAs: "OCN" },
        { zipCode: "0000", county: "Vanuatu", streets: ["Port Vila", "Erakor Lagoon", "Mele Bay"], city: "Port Vila", country: "Vanuatu", sortAs: "OCN" }
    ],
    "Level 13": [
        { sortAs: "BIN" }
    ]
};

export const firstNames = [
    "Aaliyah",
    "Abdallah",
    "Abdul",
    "Abigail",
    "Abiola",
    "Adanna",
    "Addison",
    "Adebayo",
    "Adeel",
    "Adewale",
    "Adriana",
    "Adrián",
    "Aftab",
    "Agnes",
    "Ahmad",
    "Aiden",
    "Ajani",
    "Akira",
    "Aksel",
    "Alberto",
    "Albin",
    "Alejandro",
    "Alessandra",
    "Alessandro",
    "Alessia",
    "Alfons",
    "Alfred",
    "Alfreda",
    "Alfredo",
    "Ali",
    "Alice",
    "Alicia",
    "Alina",
    "Alma",
    "Alvaro",
    "Alvin",
    "Alyssa",
    "Ama",
    "Amanda",
    "Amara",
    "Amelia",
    "Amelie",
    "Amin",
    "Amina",
    "Amir",
    "Amit",
    "Amna",
    "Amparo",
    "Ana",
    "Anders",
    "Andrea",
    "Andrés",
    "Angel",
    "Angelica",
    "Anika",
    "Anjali",
    "Anna",
    "Anton",
    "Antonia",
    "Antonio",
    "Anushka",
    "Archer",
    "Ariana",
    "Arif",
    "Arun",
    "Arvid",
    "Ashish",
    "Asta",
    "Astrid",
    "Ava",
    "Avery",
    "Axel",
    "Ayaan",
    "Ayesha",
    "Ayodele",
    "Ayotunde",
    "Aysha",
    "Azubuike",
    "Bamidele",
    "Beatrice",
    "Beatriz",
    "Belen",
    "Benjamin",
    "Bethany",
    "Binta",
    "Björn",
    "Caden",
    "Caitlyn",
    "Camila",
    "Carla",
    "Carlo",
    "Carlos",
    "Carmen",
    "Carmine",
    "Carolina",
    "Carter",
    "Celia",
    "Charles",
    "Charlotte",
    "Chiamaka",
    "Chiara",
    "Chidera",
    "Chijioke",
    "Chike",
    "Chinonso",
    "Chloe",
    "Chukwuemeka",
    "Clara",
    "Claudia",
    "Cora",
    "Cristian",
    "Cristiano",
    "Cristina",
    "Daisy",
    "Daniel",
    "Dante",
    "Dara",
    "David",
    "Diana",
    "Diego",
    "Divya",
    "Ebba",
    "Eduardo",
    "Edward",
    "Edwin",
    "Efe",
    "Eleanor",
    "Elena",
    "Elias",
    "Elin",
    "Elina",
    "Eliza",
    "Ella",
    "Ellen",
    "Elsa",
    "Emeka",
    "Emil",
    "Emilia",
    "Emily",
    "Emma",
    "Emmanuel",
    "Enrico",
    "Enrique",
    "Erik",
    "Esteban",
    "Ethan",
    "Eva",
    "Evelyn",
    "Fabiola",
    "Faisal",
    "Farah",
    "Fatima",
    "Federico",
    "Felipe",
    "Fernanda",
    "Fernando",
    "Filip",
    "Filippa",
    "Filippo",
    "Flora",
    "Florencia",
    "Fola",
    "Francesca",
    "Francesco",
    "Francisco",
    "Fredrik",
    "Freja",
    "Freya",
    "Frida",
    "Gabriel",
    "Gabriela",
    "George",
    "Georgia",
    "Georgina",
    "Giada",
    "Gianna",
    "Giorgia",
    "Giorgio",
    "Giovanni",
    "Gita",
    "Giulia",
    "Giuliana",
    "Giuliano",
    "Giuseppe",
    "Giuseppina",
    "Grace",
    "Gracie",
    "Greta",
    "Guadalupe",
    "Gustav",
    "Hanna",
    "Hannah",
    "Harper",
    "Harriet",
    "Harry",
    "Hassan",
    "Hattie",
    "Hazel",
    "Henrik",
    "Hernán",
    "Hilda",
    "Holly",
    "Hugo",
    "Hunter",
    "Ibrahim",
    "Ida",
    "Idris",
    "Ife",
    "Ifeanyi",
    "Ifeoma",
    "Ifunanya",
    "Iker",
    "Imran",
    "Indira",
    "Ingrid",
    "Inés",
    "Irene",
    "Iris",
    "Isabel",
    "Isabela",
    "Isabella",
    "Isabelle",
    "Isak",
    "Isha",
    "Ishaan",
    "Ishmael",
    "Ivan",
    "Ivar",
    "Ivy",
    "Izzy",
    "Jabari",
    "Jack",
    "Jackson",
    "Jacob",
    "Jai",
    "Jaime",
    "James",
    "Jameson",
    "Javier",
    "Jens",
    "Jibola",
    "Jin",
    "Joel",
    "Johan",
    "Johanna",
    "Johannes",
    "John",
    "Jorge",
    "Joseph",
    "Joshua",
    "José",
    "Juan",
    "Julia",
    "Julian",
    "Julius",
    "Juni",
    "Kaitlyn",
    "Karin",
    "Kasper",
    "Katherine",
    "Katrin",
    "Kavya",
    "Kehinde",
    "Khan",
    "Khushi",
    "Kiran",
    "Klara",
    "Kofi",
    "Kosi",
    "Kwaku",
    "Kwame",
    "Lara",
    "Lars",
    "Laura",
    "Lauren",
    "Laxmi",
    "Leah",
    "Leila",
    "Leo",
    "Leon",
    "Leonard",
    "Leonardo",
    "Levi",
    "Lia",
    "Liam",
    "Lidia",
    "Lila",
    "Lily",
    "Linnea",
    "Linus",
    "Logan",
    "Loke",
    "Lola",
    "Loredana",
    "Lorenzo",
    "Lova",
    "Lovisa",
    "Luca",
    "Lucas",
    "Lucia",
    "Luciana",
    "Lucy",
    "Lucía",
    "Ludvig",
    "Luigi",
    "Luis",
    "Lukas",
    "Luna",
    "Mackenzie",
    "Madeline",
    "Madhuri",
    "Madison",
    "Magnus",
    "Maja",
    "Manuel",
    "Marco",
    "Margarita",
    "Maria",
    "Mariana",
    "Marina",
    "Marta",
    "Martha",
    "Martin",
    "Martina",
    "Martín",
    "María",
    "Mason",
    "Massimo",
    "Mateo",
    "Matilda",
    "Matilde",
    "Mats",
    "Matteo",
    "Mauro",
    "Max",
    "Maxim",
    "Maximilian",
    "Maya",
    "Megan",
    "Meher",
    "Melvin",
    "Mia",
    "Michael",
    "Micheal",
    "Miguel",
    "Mikael",
    "Mikayla",
    "Mila",
    "Milo",
    "Mio",
    "Mira",
    "Moa",
    "Mohammed",
    "Molly",
    "Monica",
    "Muneer",
    "Musa",
    "Märta",
    "Mónica",
    "Nasim",
    "Natalie",
    "Nazia",
    "Neha",
    "Nerea",
    "Ngozi",
    "Nia",
    "Nicola",
    "Nikhil",
    "Nils",
    "Nina",
    "Nisha",
    "Nkem",
    "Nneka",
    "Nnenna",
    "Noel",
    "Noelle",
    "Nolan",
    "Noor",
    "Nora",
    "Nuria",
    "Obinna",
    "Olamide",
    "Ole",
    "Oliver",
    "Olivia",
    "Olle",
    "Olumide",
    "Oluwadamilola",
    "Oluwakemi",
    "Oluwaseun",
    "Oluwatobi",
    "Oluwatomiwa",
    "Omar",
    "Oscar",
    "Oskar",
    "Owen",
    "Pablo",
    "Paige",
    "Paola",
    "Paolo",
    "Patricia",
    "Paula",
    "Pedro",
    "Peyton",
    "Pierre",
    "Poppy",
    "Priya",
    "Rachel",
    "Rafael",
    "Raffaella",
    "Ragnar",
    "Raj",
    "Rajat",
    "Ralph",
    "Ramiro",
    "Ramón",
    "Rani",
    "Raquel",
    "Rashid",
    "Rasmus",
    "Raul",
    "Ravi",
    "Rehana",
    "Redas",
    "Renato",
    "Ricardo",
    "Riley",
    "Rishi",
    "Rita",
    "Robert",
    "Roberta",
    "Roberto",
    "Rocío",
    "Rohan",
    "Rohit",
    "Rosa",
    "Rosie",
    "Ruben",
    "Ruby",
    "Sabrina",
    "Sadiya",
    "Saga",
    "Sahar",
    "Saima",
    "Salvatore",
    "Samantha",
    "Sami",
    "Samuel",
    "Sana",
    "Sandeep",
    "Sandra",
    "Saniya",
    "Sanjay",
    "Santiago",
    "Sara",
    "Sasi",
    "Savannah",
    "Scarlett",
    "Sebastian",
    "Selma",
    "Shaan",
    "Shahida",
    "Shahzad",
    "Shan",
    "Sienna",
    "Signe",
    "Sigrid",
    "Silvia",
    "Simon",
    "Simona",
    "Siri",
    "Siti",
    "Sofia",
    "Sol",
    "Sonia",
    "Sophia",
    "Sophie",
    "Stefan",
    "Stefania",
    "Stefano",
    "Stella",
    "Stellan",
    "Stina",
    "Suman",
    "Sunil",
    "Sven",
    "Tahira",
    "Taiwo",
    "Tanvi",
    "Tariq",
    "Tenzin",
    "Teodor",
    "Teresa",
    "Thea",
    "Theo",
    "Thomas",
    "Tilda",
    "Tilde",
    "Tilly",
    "Tim",
    "Titi",
    "Tobias",
    "Tolu",
    "Toluwa",
    "Tomas",
    "Tommaso",
    "Tomás",
    "Tove",
    "Tsambika",
    "Tyra",
    "Uche",
    "Uchechi",
    "Ugo",
    "Valentina",
    "Valerio",
    "Valter",
    "Vera",
    "Veronica",
    "Victor",
    "Victoria",
    "Viggo",
    "Viktor",
    "Viktoria",
    "Vilma",
    "Vilmer",
    "Vincenza",
    "Vincenzo",
    "Vishal",
    "Vittoria",
    "William",
    "Wilma",
    "Wilmer",
    "Wyatt",
    "Xander",
    "Ximena",
    "Yara",
    "Yasmin",
    "Ylva",
    "Zahra",
    "Zain",
    "Zainab",
    "Zara",
    "Zoe",
    "Zubair",
    "Álvaro",
    "Ángel"
]

export const lastNames = [
    "Abdi",
    "Abdullah",
    "Adams",
    "Adamu",
    "Adler",
    "Afolabi",
    "Ahlberg",
    "Ahmed",
    "Akpan",
    "Albrecht",
    "Alexander",
    "Ali",
    "Allen",
    "Alvarez",
    "Anastasiou",
    "Andersen",
    "Anderson",
    "Andersson",
    "Andrei",
    "Arvidsson",
    "Asante",
    "Axel",
    "Axelsson",
    "Ayoade",
    "Backström",
    "Bailey",
    "Bakari",
    "Baker",
    "Balogun",
    "Banda",
    "Barnes",
    "Barrett",
    "Bashir",
    "Bauer",
    "Bautista",
    "Becker",
    "Bediako",
    "Bell",
    "Bello",
    "Bengtsson",
    "Bennett",
    "Berg",
    "Berger",
    "Berglund",
    "Bergman",
    "Bergström",
    "Bertrand",
    "Bianchi",
    "Birk",
    "Bishop",
    "Bjerre",
    "Björk",
    "Björklund",
    "Björn",
    "Björnsson",
    "Blake",
    "Bognár",
    "Bowen",
    "Bravo",
    "Bredal",
    "Brooks",
    "Brown",
    "Bryant",
    "Butler",
    "Bárth",
    "Bäcker",
    "Börjesson",
    "Bøge",
    "Cacciatore",
    "Caldwell",
    "Cameron",
    "Campbell",
    "Carlsen",
    "Carlsson",
    "Carrillo",
    "Carter",
    "Castaño",
    "Castillo",
    "Chambers",
    "Chang",
    "Chapman",
    "Charles",
    "Chavez",
    "Chen",
    "Chijioke",
    "Chirwa",
    "Cho",
    "Choi",
    "Christensen",
    "Cissé",
    "Clark",
    "Collins",
    "Constantin",
    "Conti",
    "Cook",
    "Cooper",
    "Costa",
    "Costache",
    "Córdoba",
    "Davidson",
    "Davies",
    "Davis",
    "Deng",
    "Diabate",
    "Diaz",
    "Diouf",
    "Dixon",
    "Dlamini",
    "Dobre",
    "Douglas",
    "Duncan",
    "Díaz",
    "Ehlers",
    "Eklund",
    "Elofsson",
    "Enescu",
    "Eriksen",
    "Eriksson",
    "Escobar",
    "Evans",
    "Fadl",
    "Falk",
    "Fang",
    "Farkas",
    "Fayad",
    "Fernandez",
    "Fernández",
    "Ferrari",
    "Fischer",
    "Fisher",
    "Fletcher",
    "Flores",
    "Fofana",
    "Ford",
    "Foster",
    "Fransson",
    "Fredriksson",
    "Frisk",
    "Fujimoto",
    "Fujita",
    "Galarza",
    "Gallo",
    "Garcia",
    "García",
    "Garza",
    "Gbagbo",
    "Georgescu",
    "Gibson",
    "Giordano",
    "Giovanni",
    "Gomez",
    "Gonzalez",
    "González",
    "Gordon",
    "Graham",
    "Grant",
    "Graves",
    "Gray",
    "Green",
    "Griffin",
    "Grönberg",
    "Gueye",
    "Guo",
    "Gupta",
    "Gustafsson",
    "Gutiérrez",
    "Gómez",
    "Göransson",
    "Hagström",
    "Hall",
    "Hallberg",
    "Hamada",
    "Hammarström",
    "Hansen",
    "Hansson",
    "Harper",
    "Harris",
    "Harrison",
    "Hassan",
    "Hayes",
    "He",
    "Hegedűs",
    "Hellström",
    "Hemming",
    "Henderson",
    "Henry",
    "Hernandez",
    "Hernández",
    "Herrmann",
    "Hoffmann",
    "Holm",
    "Holmberg",
    "Hong",
    "Horváth",
    "Howard",
    "Huang",
    "Hughes",
    "Hunter",
    "Hussein",
    "Håkansson",
    "Högberg",
    "Höglund",
    "Ibrahim",
    "Imai",
    "Ionescu",
    "Ishida",
    "Ito",
    "Ivan",
    "Iversen",
    "Jackson",
    "Jain",
    "James",
    "Jefisovas",
    "Jenkins",
    "Jensen",
    "Jiang",
    "Jiao",
    "Jiménez",
    "Johannessen",
    "Johannesson",
    "Johansen",
    "Johansson",
    "Johnson",
    "Jones",
    "Jonsson",
    "Juma",
    "Jung",
    "Jönsson",
    "Jørgensen",
    "Kallberg",
    "Kallström",
    "Kamara",
    "Kang",
    "Kante",
    "Karlsson",
    "Karlén",
    "Kato",
    "Kaur",
    "Keita",
    "Keller",
    "Kennedy",
    "Keresztúry",
    "Khalid",
    "Kim",
    "King",
    "Kinoshita",
    "Kiss",
    "Kjällström",
    "Kjær",
    "Kobayashi",
    "Koch",
    "Koffi",
    "Kovács",
    "Kristensen",
    "Krogh",
    "Kumar",
    "Kőrösi",
    "Lagerlöf",
    "Lamb",
    "Lamine",
    "Lang",
    "Lange",
    "Larsen",
    "Larsson",
    "Lauritzen",
    "Lee",
    "Lehmann",
    "Lewis",
    "Li",
    "Liang",
    "Lin",
    "Lind",
    "Lindberg",
    "Lindgren",
    "Lindman",
    "Lindqvist",
    "Lindström",
    "Liu",
    "Lopez",
    "Lowe",
    "Lucia",
    "Luna",
    "Lund",
    "Lundberg",
    "Lundin",
    "Lundqvist",
    "Lupu",
    "László",
    "López",
    "Ma",
    "Madsen",
    "Mahmud",
    "Malm",
    "Mariam",
    "Marin",
    "Marino",
    "Markus",
    "Martin",
    "Martinez",
    "Martín",
    "Martínez",
    "Mason",
    "Matsuda",
    "Mattsson",
    "Mbaye",
    "McDonald",
    "Medina",
    "Mehta",
    "Meier",
    "Melander",
    "Mendoza",
    "Meyer",
    "Mihail",
    "Mikkelsen",
    "Miller",
    "Mills",
    "Mitchell",
    "Mokhtar",
    "Molina",
    "Molnár",
    "Montero",
    "Moon",
    "Moore",
    "Mora",
    "Morales",
    "Moreno",
    "Morgan",
    "Mori",
    "Morris",
    "Mortensen",
    "Murakami",
    "Murphy",
    "Musa",
    "Mårtensson",
    "Méndez",
    "Möller",
    "Møller",
    "Müller",
    "Nagasaki",
    "Nakamura",
    "Nashit",
    "Navarro",
    "Nelson",
    "Niazi",
    "Nielsen",
    "Nilsson",
    "Nishimura",
    "Nkrumah",
    "Nordin",
    "Nordström",
    "Nylund",
    "Nyman",
    "Nyström",
    "Németh",
    "Ogawa",
    "Ohlsson",
    "Ohta",
    "Olawale",
    "Oliver",
    "Olofsson",
    "Olsen",
    "Olsson",
    "Oluwaseun",
    "Omar",
    "Ortíz",
    "Palmer",
    "Paredes",
    "Park",
    "Parker",
    "Patel",
    "Patterson",
    "Pedersen",
    "Peng",
    "Perez",
    "Perry",
    "Persson",
    "Peters",
    "Petersen",
    "Petersson",
    "Petrescu",
    "Pettersson",
    "Phillips",
    "Popescu",
    "Price",
    "Pál",
    "Pérez",
    "Péter",
    "Qian",
    "Radu",
    "Ramirez",
    "Ramsey",
    "Ramírez",
    "Rasmussen",
    "Reddy",
    "Reed",
    "Reid",
    "Reyes",
    "Ricci",
    "Richards",
    "Richardson",
    "Richter",
    "Rivera",
    "Roberts",
    "Rodriguez",
    "Rodríguez",
    "Rogers",
    "Ross",
    "Ruiz",
    "Russell",
    "Rydström",
    "Rydén",
    "Ríos",
    "Rödin",
    "Sahlberg",
    "Saito",
    "Salazar",
    "Salim",
    "Sammy",
    "Sanchez",
    "Sanders",
    "Sandström",
    "Sani",
    "Santiago",
    "Sato",
    "Savage",
    "Schmidt",
    "Schneider",
    "Schultz",
    "Schulz",
    "Schuster",
    "Scott",
    "Seo",
    "Serrano",
    "Sewell",
    "Sharma",
    "Shaw",
    "Shimizu",
    "Shin",
    "Silva",
    "Simmons",
    "Simonsen",
    "Simpson",
    "Singh",
    "Sjöberg",
    "Sjöstrand",
    "Sjöström",
    "Skaarup",
    "Smith",
    "Solís",
    "Sosa",
    "Soto",
    "Stewart",
    "Stoica",
    "Ström",
    "Suarez",
    "Sugimoto",
    "Suleiman",
    "Suleman",
    "Sullivan",
    "Sun",
    "Sundberg",
    "Sundin",
    "Sundström",
    "Sutton",
    "Suárez",
    "Svanberg",
    "Svensson",
    "Sykes",
    "Szabó",
    "Szűcs",
    "Sánchez",
    "Sándor",
    "Sánta",
    "Sørensen",
    "Takahashi",
    "Takeda",
    "Takács",
    "Tanaka",
    "Tang",
    "Tateishi",
    "Tatsuno",
    "Taylor",
    "Thakur",
    "Thomas",
    "Thompson",
    "Thomsen",
    "Tian",
    "Torp",
    "Torres",
    "Toure",
    "Tshabalala",
    "Tucker",
    "Turner",
    "Tóth",
    "Törnqvist",
    "Tønder",
    "Ueda",
    "Valencia",
    "Varga",
    "Vargas",
    "Vaughn",
    "Vega",
    "Verma",
    "Vestergaard",
    "Vik",
    "Vlad",
    "Vásquez",
    "Vázquez",
    "Wagner",
    "Wahab",
    "Walker",
    "Walters",
    "Wang",
    "Ward",
    "Watanabe",
    "Weber",
    "White",
    "Wiklund",
    "Wilkinson",
    "Williams",
    "Wilson",
    "Wood",
    "Wright",
    "Wu",
    "Xu",
    "Yadav",
    "Yamada",
    "Yamamoto",
    "Yang",
    "Yeboah",
    "Yngvesson",
    "Yoo",
    "Yoon",
    "Yoshida",
    "Young",
    "Yusuf",
    "Zakaria",
    "Zhang",
    "Zhao",
    "Zhou",
    "Zhu",
    "Zimmermann",
    "Ávila",
    "Åberg",
    "Åström"
]
